-- ---------------------------------------------------------------------------
-- girias de jogos e esportes eletronicos
--
-- 100 verbetes, 105 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('gg', 'gg', 'gg', 'en', FALSE, FALSE),
    ('brb', 'brb', 'brb', 'en', FALSE, FALSE),
    ('ping', 'ping', 'ping', 'en', FALSE, FALSE),
    ('throw', 'throw', 'throw', 'en', FALSE, FALSE),
    ('carry', 'carry', 'carry', 'en', FALSE, FALSE),
    ('feed', 'feed', 'feed', 'en', FALSE, FALSE),
    ('gank', 'gank', 'gank', 'en', FALSE, FALSE),
    ('aggro', 'aggro', 'aggro', 'en', FALSE, FALSE),
    ('spawn', 'spawn', 'spawn', 'en', FALSE, FALSE),
    ('loot', 'loot', 'loot', 'en', FALSE, FALSE),
    ('grind', 'grind', 'grind', 'en', FALSE, FALSE),
    ('meta', 'meta', 'meta', 'en', FALSE, FALSE),
    ('nolife', 'nolife', 'nolife', 'en', FALSE, FALSE),
    ('wipe', 'wipe', 'wipe', 'en', FALSE, FALSE),
    ('boss', 'boss', 'boss', 'en', FALSE, FALSE),
    ('hitbox', 'hitbox', 'hitbox', 'en', FALSE, FALSE),
    ('buildar', 'buildar', 'buildar', 'pt-BR', FALSE, FALSE),
    ('nerdar', 'nerdar', 'nerdar', 'pt-BR', FALSE, FALSE),
    ('upar', 'upar', 'upar', 'pt-BR', FALSE, FALSE),
    ('rushar', 'rushar', 'rushar', 'pt-BR', FALSE, FALSE),
    ('farmar', 'farmar', 'farmar', 'pt-BR', FALSE, FALSE),
    ('dropar', 'dropar', 'dropar', 'pt-BR', FALSE, FALSE),
    ('castar', 'castar', 'castar', 'pt-BR', FALSE, FALSE),
    ('main', 'main', 'main', 'en', FALSE, FALSE),
    ('op', 'op', 'op', 'en', FALSE, FALSE),
    ('hp', 'hp', 'hp', 'en', FALSE, FALSE),
    ('gg izi', 'gg izi', 'gg izi', 'pt-BR', FALSE, FALSE),
    ('pvp', 'pvp', 'pvp', 'en', FALSE, FALSE),
    ('nick', 'nick', 'nick', 'en', FALSE, FALSE),
    ('lobby', 'lobby', 'lobby', 'en', FALSE, FALSE),
    ('party', 'party', 'party', 'en', FALSE, FALSE),
    ('queue', 'queue', 'queue', 'en', FALSE, FALSE),
    ('hard', 'hard', 'hard', 'en', FALSE, FALSE),
    ('cheater', 'cheater', 'cheater', 'en', FALSE, FALSE),
    ('aimbot', 'aimbot', 'aimbot', 'en', FALSE, FALSE),
    ('wallhack', 'wallhack', 'wallhack', 'en', FALSE, FALSE),
    ('ranqueada', 'ranqueada', 'ranqueada', 'pt-BR', FALSE, FALSE),
    ('elo', 'elo', 'elo', 'en', FALSE, FALSE),
    ('duo', 'duo', 'duo', 'en', FALSE, FALSE),
    ('solo', 'solo', 'solo', 'en', FALSE, FALSE),
    ('tóxico', 'toxico', 'toxico', 'pt-BR', FALSE, FALSE),
    ('reportar', 'reportar', 'reportar', 'pt-BR', FALSE, FALSE),
    ('ban', 'ban', 'ban', 'en', FALSE, FALSE),
    ('combo', 'combo', 'combo', 'en', FALSE, FALSE),
    ('speedrun', 'speedrun', 'speedrun', 'en', FALSE, FALSE),
    ('glitch', 'glitch', 'glitch', 'en', FALSE, FALSE),
    ('bug', 'bug', 'bug', 'en', FALSE, FALSE),
    ('patch', 'patch', 'patch', 'en', FALSE, FALSE),
    ('skin', 'skin', 'skin', 'en', FALSE, FALSE),
    ('f2p', 'f2p', 'f2p', 'en', FALSE, FALSE),
    ('p2w', 'p2w', 'p2w', 'en', FALSE, FALSE),
    ('gacha', 'gacha', 'gacha', 'en', FALSE, FALSE),
    ('sandbox', 'sandbox', 'sandbox', 'en', FALSE, FALSE),
    ('cooldown', 'cooldown', 'cooldown', 'en', FALSE, FALSE),
    ('tryhard', 'tryhard', 'tryhard', 'en', FALSE, FALSE),
    ('casual', 'casual', 'casual', 'en', FALSE, FALSE),
    ('mira', 'mira', 'mira', 'pt-BR', FALSE, FALSE),
    ('ragequit', 'ragequit', 'ragequit', 'en', FALSE, FALSE),
    ('dodgear', 'dodgear', 'dodgear', 'pt-BR', FALSE, FALSE),
    ('one shot', 'one shot', 'one shot', 'en', FALSE, FALSE),
    ('healer', 'healer', 'healer', 'en', FALSE, FALSE),
    ('tank', 'tank', 'tank', 'en', FALSE, FALSE),
    ('dps', 'dps', 'dps', 'en', FALSE, FALSE),
    ('nolan', 'nolan', 'nolan', 'pt-BR', FALSE, FALSE),
    ('gamer', 'gamer', 'gamer', 'en', FALSE, FALSE),
    ('setup', 'setup', 'setup', 'en', FALSE, FALSE),
    ('fps', 'fps', 'fps', 'en', FALSE, FALSE),
    ('mmr', 'mmr', 'mmr', 'en', FALSE, FALSE),
    ('hitar', 'hitar', 'hitar', 'pt-BR', FALSE, FALSE),
    ('pushar', 'pushar', 'pushar', 'pt-BR', FALSE, FALSE),
    ('eco', 'eco', 'eco', 'en', FALSE, FALSE),
    ('ace', 'ace', 'ace', 'en', FALSE, FALSE),
    ('whiff', 'whiff', 'whiff', 'en', FALSE, FALSE),
    ('peekar', 'peekar', 'peekar', 'pt-BR', FALSE, FALSE),
    ('clipar', 'clipar', 'clipar', 'pt-BR', FALSE, FALSE),
    ('montage', 'montage', 'montage', 'en', FALSE, FALSE),
    ('highlight', 'highlight', 'highlight', 'en', FALSE, FALSE),
    ('hardcore', 'hardcore', 'hardcore', 'en', FALSE, FALSE),
    ('go next', 'go next', 'go next', 'en', FALSE, FALSE),
    ('jogar de bot', 'jogar de bot', 'jogar de bot', 'pt-BR', FALSE, FALSE),
    ('sweat', 'sweat', 'sweat', 'en', FALSE, FALSE),
    ('chocar', 'chocar', 'chocar', 'pt-BR', FALSE, FALSE),
    ('que roubo', 'que roubo', 'que roubo', 'pt-BR', FALSE, FALSE),
    ('puxar', 'puxar', 'puxar', 'pt-BR', FALSE, FALSE),
    ('trocar', 'trocar', 'trocar', 'pt-BR', FALSE, FALSE),
    ('abrir', 'abrir', 'abrir', 'pt-BR', FALSE, FALSE),
    ('segurar', 'segurar', 'segurar', 'pt-BR', FALSE, FALSE),
    ('crashar', 'crashar', 'crashar', 'pt-BR', FALSE, FALSE),
    ('otimizado', 'otimizado', 'otimizado', 'pt-BR', FALSE, FALSE),
    ('input lag', 'input lag', 'input lag', 'en', FALSE, FALSE),
    ('macro', 'macro', 'macro', 'en', FALSE, FALSE),
    ('gg wp', 'gg wp', 'gg wp', 'en', FALSE, FALSE),
    ('sniper', 'sniper', 'sniper', 'en', FALSE, FALSE),
    ('rekt', 'rekt', 'rekt', 'en', FALSE, FALSE),
    ('git gud', 'git gud', 'git gud', 'en', FALSE, FALSE),
    ('kd', 'kd', 'kd', 'en', FALSE, FALSE),
    ('wr', 'wr', 'wr', 'en', FALSE, FALSE),
    ('pb', 'pb', 'pb', 'en', FALSE, FALSE),
    ('nerfaram', 'nerfaram', 'nerfaram', 'pt-BR', FALSE, FALSE),
    ('respawnar', 'respawnar', 'respawnar', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('gg', 'en', 'Fora do jogo, quer dizer que algo acabou ou deu errado de vez.', 'Uso ampliado da sigla de fim de partida. Um "gg" solto depois de uma notícia ruim equivale a "acabou", "era isso mesmo".', 'acabou'),
    ('brb', 'en', 'Aviso de que a pessoa volta em poucos minutos.', 'De "be right back", já volto. Mais curto que "afk": indica ausência rápida e com volta prevista.', 'já volto'),
    ('ping', 'en', 'Número que mostra o quanto a internet está demorando para responder.', 'Medido em milésimos de segundo. Quanto menor, melhor: ping alto é a causa mais comum de travamento em jogos pela internet.', 'latência'),
    ('throw', 'en', 'Jogar fora uma partida que já estava ganha.', 'De "throw the game". Pode ser por erro ou de propósito. Quando é de propósito, é considerado sabotagem do próprio time.', 'perder por erro próprio'),
    ('carry', 'en', 'Jogador que ganha a partida praticamente sozinho, puxando o time.', 'De "carry", carregar. Também usado como verbo: "ele carregou" quer dizer que o resto do time contribuiu pouco.', 'puxar o time'),
    ('feed', 'en', 'Morrer muitas vezes e com isso deixar o time adversário mais forte.', 'De "feed", alimentar. Em vários jogos, derrotar alguém dá recursos ao adversário, então morrer demais literalmente alimenta o outro time.', 'favorecer o adversário'),
    ('gank', 'en', 'Atacar alguém de surpresa, em grupo, quando a pessoa está sozinha.', 'Provável junção de "gang" com "kill". É estratégia comum e não é considerada desleal.', 'emboscada em grupo'),
    ('aggro', 'en', 'A atenção dos inimigos do jogo voltada para um jogador específico.', 'De "aggression". "Puxar o aggro" é fazer os inimigos atacarem você em vez do resto do time, geralmente de propósito.', 'atrair os inimigos'),
    ('spawn', 'en', 'O ponto onde o jogador reaparece depois de morrer.', 'De "spawn", surgir. "Spawn kill" é derrubar alguém no exato momento em que reaparece, antes de poder reagir, o que é considerado desleal.', 'ponto de retorno'),
    ('loot', 'en', 'Os itens que o jogador recolhe pelo caminho.', 'De "loot", espólio. Muitos jogos têm "loot box", caixa com itens sorteados, que já foi comparada a jogo de azar em vários países.', 'itens recolhidos'),
    ('grind', 'en', 'Repetir a mesma tarefa muitas vezes para progredir no jogo.', 'De "grind", moer. Fora dos jogos, "grindar" virou sinônimo de trabalhar muito e sem glamour para chegar a algum lugar.', 'repetir para progredir'),
    ('meta', 'en', 'A maneira de jogar que está dando mais certo no momento.', 'De "most effective tactic available", a tática mais eficaz disponível. Muda a cada atualização do jogo. "Fora do meta" é usar algo que a maioria abandonou.', 'estratégia dominante'),
    ('nolife', 'en', 'Alguém que joga tanto que parece não ter mais nada na vida.', 'Quase sempre ofensa, às vezes usada com humor pela própria pessoa. Já foi criticado por tratar dedicação como defeito.', 'viciado em jogo'),
    ('wipe', 'en', 'Quando o time inteiro morre de uma vez.', 'De "wipe", limpar. Em jogos em que se joga em grupo, o wipe geralmente obriga a recomeçar a fase inteira.', 'derrota total do time'),
    ('boss', 'en', 'O inimigo mais forte de uma fase, que fecha aquela etapa do jogo.', 'Em português virou "chefão". Fora dos jogos, "boss" também é usado como elogio a alguém que resolve tudo.', 'inimigo final'),
    ('hitbox', 'en', 'A área invisível do personagem que conta como acerto quando alguém atira.', 'Reclamar da hitbox é reclamar que o tiro deveria ter acertado e não acertou, ou o contrário.', 'área de acerto'),
    ('buildar', 'pt-BR', 'Montar o personagem escolhendo habilidades e equipamentos.', 'Do inglês "build", construir. "Build" é também o resultado: o conjunto de escolhas que a pessoa montou.', 'montar o personagem'),
    ('nerdar', 'pt-BR', 'Passar horas mergulhado em um jogo ou num assunto.', 'De "nerd". Diferente de "nolife", costuma ser usado sem ofensa e até com orgulho.', 'mergulhar no assunto'),
    ('upar', 'pt-BR', 'Subir de nível no jogo.', 'De "level up". Fora do jogo, "upar" ganhou o sentido de melhorar qualquer coisa: "upei meu celular".', 'subir de nível'),
    ('rushar', 'pt-BR', 'Avançar rápido e direto, sem esperar nem se preparar.', 'Do inglês "rush", correr. Fora dos jogos, "rushar" virou fazer qualquer coisa com pressa: "rushei a prova".', 'avançar com pressa'),
    ('farmar', 'pt-BR', 'Repetir tarefas simples no jogo para juntar dinheiro ou itens.', 'De "farm", cultivar. Fora dos jogos virou juntar qualquer coisa aos poucos: "farmar seguidor", "farmar curtida".', 'acumular recursos'),
    ('dropar', 'pt-BR', 'Um item cair do inimigo derrotado.', 'De "drop", soltar. "Dropou" quer dizer que o item apareceu.', 'soltar item'),
    ('dropar', 'pt-BR', 'Fora do jogo, lançar algo novo, como uma música ou um vídeo.', '"Dropou o clipe" quer dizer que o vídeo foi publicado. Uso vindo da indústria da música.', 'lançar'),
    ('castar', 'pt-BR', 'Narrar uma partida ao vivo para quem está assistindo.', 'De "broadcast", transmitir. O "caster" é o narrador de partidas de esporte eletrônico, equivalente ao locutor de futebol.', 'narrar a partida'),
    ('main', 'en', 'O personagem que a pessoa mais usa e conhece melhor.', 'De "main", principal. Virou verbo também: "eu maino esse personagem".', 'personagem principal'),
    ('op', 'en', 'Forte demais, desequilibrado a ponto de estragar o jogo.', 'De "overpowered". Quando muita gente reclama que algo está op, costuma vir um enfraquecimento na atualização seguinte.', 'forte demais'),
    ('hp', 'en', 'A quantidade de vida que resta ao personagem.', 'De "health points", pontos de vida. Fora do jogo, "tô sem hp" virou jeito de dizer que a pessoa está exausta.', 'pontos de vida'),
    ('gg izi', 'pt-BR', 'Provocação dita ao vencer, misturando "bom jogo" com "foi fácil".', 'Junção de "gg" com "ez" escrito à brasileira. Em vários jogos é passível de punição por provocação.', 'foi fácil'),
    ('pvp', 'en', 'Modo em que jogadores enfrentam outros jogadores, e não o computador.', 'De "player versus player". O oposto é "pve", jogador contra o ambiente controlado pela máquina.', 'jogador contra jogador'),
    ('nick', 'en', 'O apelido que a pessoa usa dentro do jogo ou da internet.', 'De "nickname". Muitas vezes é por ele que a pessoa é conhecida, e não pelo nome real.', 'apelido'),
    ('lobby', 'en', 'A sala de espera onde os jogadores se juntam antes da partida começar.', 'De "lobby", saguão. É onde o grupo se organiza e escolhe os personagens.', 'sala de espera'),
    ('party', 'en', 'O grupo de amigos que joga junto na mesma partida.', '"Chama na party" é um convite para jogar junto. Nada a ver com festa, apesar da tradução literal.', 'grupo'),
    ('queue', 'en', 'A fila de espera até o jogo encontrar adversários.', 'Pronuncia-se como a letra Q. "Solo queue" é entrar na fila sozinho e receber companheiros desconhecidos.', 'fila de espera'),
    ('hard', 'en', 'Quer dizer que algo é muito difícil ou muito intenso.', 'Do inglês "hard", duro. Também aparece colado em outra palavra para reforçar: "hard carry" é carregar o time de forma esmagadora.', 'difícil'),
    ('cheater', 'en', 'Quem usa programa proibido para trapacear no jogo.', 'De "cheat", trapaça. Diferente do "smurf", que joga dentro das regras: o cheater quebra as regras e costuma ser banido.', 'trapaceiro'),
    ('aimbot', 'en', 'Programa proibido que faz a mira acertar sozinha.', 'Junção de "aim", mira, com "robot". É das trapaças mais comuns e das mais fáceis de detectar.', 'mira automática'),
    ('wallhack', 'en', 'Programa proibido que deixa a pessoa enxergar os adversários através das paredes.', 'Junto do aimbot, é a trapaça mais reclamada em jogos de tiro.', 'visão através de paredes'),
    ('ranqueada', 'pt-BR', 'Partida que vale posição numa classificação, diferente da partida casual.', 'Do inglês "ranked". Perder na ranqueada faz a pessoa cair de posição, o que explica boa parte da tensão nesse modo.', 'partida classificatória'),
    ('elo', 'en', 'O nível de habilidade que o sistema atribui ao jogador.', 'Nome vindo de Arpad Elo, que criou o sistema de classificação usado no xadrez. "Elo hell" é a sensação de estar preso num nível.', 'nível de classificação'),
    ('duo', 'en', 'Jogar em dupla fixa, sempre com a mesma pessoa.', 'Muitos jogos limitam o duo em modos competitivos, porque dois jogadores combinados têm vantagem sobre desconhecidos.', 'dupla'),
    ('solo', 'en', 'Jogar sozinho, sem amigos no time.', '"Solo queue" é entrar na fila sozinho e receber companheiros que você nunca viu.', 'sozinho'),
    ('toxico', 'pt-BR', 'Jogador que ofende, humilha ou estraga a partida dos outros de propósito.', 'Do inglês "toxic". Fora dos jogos, "pessoa tóxica" é alguém cuja convivência faz mal, e o uso já passou para relações e trabalho.', 'hostil'),
    ('reportar', 'pt-BR', 'Avisar o sistema sobre alguém que quebrou as regras.', 'Do inglês "report", denunciar. Vale para jogos e para redes sociais.', 'denunciar'),
    ('ban', 'en', 'Ser expulso e proibido de voltar.', 'Pode ser temporário ou permanente. Nas redes sociais, "shadowban" é a versão invisível: a pessoa continua publicando, mas quase ninguém vê.', 'banimento'),
    ('combo', 'en', 'Sequência de golpes encaixados um atrás do outro.', 'De "combination". Em jogos de luta, decorar combos é boa parte do aprendizado.', 'sequência de golpes'),
    ('speedrun', 'en', 'Terminar um jogo o mais rápido possível, competindo por tempo.', 'Virou modalidade com regras próprias e recordes verificados por comunidades. Muita gente assiste a speedrun sem nunca ter jogado o jogo.', 'corrida contra o tempo'),
    ('glitch', 'en', 'Falha do jogo que faz algo estranho acontecer.', 'Diferente de "bug" apenas pelo uso: "glitch" costuma descrever a falha visível, engraçada ou aproveitável.', 'falha'),
    ('bug', 'en', 'Erro de programação que faz algo funcionar errado.', 'Em português virou "bugado", que se aplica a qualquer coisa que travou.', 'erro'),
    ('bug', 'en', 'Falando de gente, quer dizer que a pessoa ficou confusa e travou.', '"Fiquei bugada" quer dizer que a pessoa não entendeu nada e não soube o que responder.', 'ficar confuso'),
    ('patch', 'en', 'Atualização que corrige erros ou muda regras do jogo.', 'De "patch", remendo. As "patch notes" são a lista do que mudou, onde aparecem os enfraquecimentos e reforços.', 'atualização'),
    ('skin', 'en', 'Roupa ou aparência diferente para o personagem, que não muda a força dele.', 'De "skin", pele. É o principal produto vendido em jogos gratuitos, e movimenta muito dinheiro.', 'aparência'),
    ('f2p', 'en', 'Jogo de graça para jogar, que ganha dinheiro vendendo itens.', 'De "free to play". Quando os itens vendidos dão vantagem real, o jogo passa a ser chamado de "pay to win".', 'gratuito'),
    ('p2w', 'en', 'Jogo em que quem paga leva vantagem sobre quem não paga.', 'De "pay to win", pagar para vencer. É das críticas mais duras que um jogo pode receber, porque quebra a ideia de competição justa.', 'pagar para vencer'),
    ('gacha', 'en', 'Sistema em que a pessoa paga para sortear um item, sem saber o que vem.', 'Do japonês "gachapon", as máquinas de cápsula. É alvo de regulação em vários países pela semelhança com jogo de azar.', 'sorteio pago'),
    ('sandbox', 'en', 'Jogo sem objetivo fixo, em que a pessoa cria o que quiser.', 'De "sandbox", caixa de areia. Minecraft é o exemplo mais conhecido.', 'jogo livre'),
    ('cooldown', 'en', 'O tempo de espera até poder usar uma habilidade de novo.', 'Fora do jogo virou brincadeira para descanso: "tô em cooldown" quer dizer que a pessoa precisa de um tempo.', 'tempo de recarga'),
    ('tryhard', 'en', 'Quem leva a sério demais um jogo que era só diversão.', 'Costuma ser crítica, mas parte dos jogadores usa como elogio a quem se dedica de verdade.', 'competitivo demais'),
    ('casual', 'en', 'Quem joga por diversão, sem se preocupar em ganhar.', 'O oposto de tryhard. Também nomeia o modo de partida que não vale classificação.', 'descompromissado'),
    ('mira', 'pt-BR', 'A pontaria do jogador em jogos de tiro.', '"Mira de ouro" é elogio a quem acerta sempre; "mira de manteiga" é a piada para quem erra tudo.', 'pontaria'),
    ('ragequit', 'en', 'Ficar tão irritado a ponto de sair do jogo no meio.', 'Do inglês "rage quit", desistir de raiva. Em partidas em equipe, prejudica o time inteiro e costuma render punição.', 'abandonar de raiva'),
    ('dodgear', 'pt-BR', 'Desviar de um golpe.', 'De "dodge", esquivar.', 'esquivar'),
    ('dodgear', 'pt-BR', 'Sair da fila antes da partida começar, para não pegar aquele adversário.', 'Costuma render punição de tempo, justamente para desestimular a prática.', 'abandonar a fila'),
    ('one shot', 'en', 'Derrubar o adversário com um único golpe.', 'Fora dos jogos, "one shot" virou resolver algo de primeira, sem precisar tentar de novo.', 'golpe único'),
    ('healer', 'en', 'O jogador que cura os companheiros em vez de atacar.', 'De "heal", curar. Função pouco reconhecida na hora da vitória e muito cobrada na hora da derrota.', 'curandeiro'),
    ('tank', 'en', 'O jogador que aguenta os ataques no lugar dos outros.', 'De "tank", tanque de guerra.', 'aguentar o dano'),
    ('tank', 'en', 'Fora do jogo, aguentar algo pesado sem desabar.', '"Tankei a semana inteira" quer dizer que a pessoa suportou uma carga difícil.', 'aguentar'),
    ('dps', 'en', 'O quanto de dano um personagem causa por segundo.', 'De "damage per second". Também nomeia a função: o "dps" é quem ataca, em contraste com o tank e o healer.', 'dano por segundo'),
    ('nolan', 'pt-BR', 'Jogada tão confusa que ninguém entendeu como acabou dando certo.', 'Referência ao cineasta Christopher Nolan, conhecido por roteiros complicados. Uso brasileiro, comum em transmissões.', 'jogada confusa'),
    ('gamer', 'en', 'Pessoa que joga videogame com frequência.', 'Virou também rótulo de identidade, e às vezes é usado com ironia por quem acha o rótulo exagerado.', 'jogador'),
    ('setup', 'en', 'O conjunto de computador, cadeira e acessórios que a pessoa usa para jogar.', 'Mostrar o setup é conteúdo comum em vídeos. Também usado fora dos jogos para qualquer arranjo de equipamentos.', 'equipamento'),
    ('fps', 'en', 'Quantos quadros por segundo o jogo consegue mostrar.', 'De "frames per second". Quanto maior, mais suave a imagem.', 'quadros por segundo'),
    ('fps', 'en', 'A mesma sigla nomeia o tipo de jogo de tiro visto pelos olhos do personagem.', 'De "first person shooter", tiro em primeira pessoa. O contexto separa os dois sentidos sem dificuldade.', 'jogo de tiro em primeira pessoa'),
    ('mmr', 'en', 'Nota interna que o jogo usa para escolher adversários do seu nível.', 'De "matchmaking rating". Costuma ser invisível ao jogador, diferente do elo, que aparece na tela.', 'nota de pareamento'),
    ('hitar', 'pt-BR', 'Acertar o golpe ou o tiro.', 'De "hit", acertar. "Não hitou" quer dizer que passou perto e não pegou.', 'acertar'),
    ('pushar', 'pt-BR', 'Avançar com pressão para tomar terreno do adversário.', 'De "push", empurrar. Diferente de "rushar", que é correr sem preparo: pushar é avançar de forma organizada.', 'pressionar'),
    ('eco', 'en', 'Rodada em que o time economiza dinheiro e compra pouco de propósito.', 'De "economy". A ideia é perder uma rodada barata para ter dinheiro forte na próxima.', 'rodada de economia'),
    ('ace', 'en', 'Quando um único jogador derruba o time adversário inteiro.', 'Do baralho, onde o ás é a carta mais forte. É das jogadas mais celebradas em jogos de tiro por equipe.', 'derrubada completa'),
    ('whiff', 'en', 'Errar feio um golpe ou tiro que parecia fácil.', 'Palavra inglesa que imita o som de algo passando no vazio.', 'erro feio'),
    ('peekar', 'pt-BR', 'Espiar rapidamente de trás de uma parede para ver o adversário.', 'De "peek", espiar. Técnica central em jogos de tiro tático, com várias variações de nome próprio.', 'espiar'),
    ('clipar', 'pt-BR', 'Salvar um trecho curto de uma partida ou transmissão.', 'De "clip", recorte. "Clipa isso" é um pedido para gravar o momento antes que ele se perca.', 'gravar o trecho'),
    ('montage', 'en', 'Vídeo com os melhores momentos de um jogador, um atrás do outro.', 'Costuma vir com música e cortes rápidos. É um formato de vídeo muito antigo na cultura de jogos.', 'compilado'),
    ('highlight', 'en', 'O melhor momento de uma partida.', 'De "highlight", destaque. O mesmo termo usado no esporte tradicional para os melhores lances.', 'melhor momento'),
    ('hardcore', 'en', 'Modo de jogo em que morrer apaga tudo e obriga a recomeçar do zero.', 'Fora dos jogos, "hardcore" descreve qualquer coisa levada ao extremo.', 'modo extremo'),
    ('go next', 'en', 'Aceitar que a partida está perdida e já pensar na próxima.', 'Frase comum quando o time desiste mentalmente antes do fim. Virou também jeito de dizer "deixa pra lá" fora do jogo.', 'vamos para a próxima'),
    ('jogar de bot', 'pt-BR', 'Jogar mal, de forma automática, sem prestar atenção.', 'De "bot", o personagem controlado pelo computador, que joga de forma previsível.', 'jogar sem atenção'),
    ('sweat', 'en', 'Jogador que se esforça ao máximo mesmo numa partida sem importância.', 'De "sweat", suor. Primo do "tryhard", com a mesma carga de crítica leve.', 'esforçado demais'),
    ('chocar', 'pt-BR', 'Ficar parado no mesmo lugar sem fazer nada de útil.', 'Uso brasileiro em jogos, por analogia com a galinha que fica sentada no ninho.', 'ficar parado'),
    ('que roubo', 'pt-BR', 'Reclamação de que algo foi injusto no jogo.', 'Na maioria das vezes não acusa trapaça de verdade: é desabafo de quem achou o resultado injusto.', 'que injustiça'),
    ('puxar', 'pt-BR', 'Atrair inimigos de propósito para longe do grupo.', 'Equivalente brasileiro de "pull". Costuma ser combinado antes com o time.', 'atrair'),
    ('trocar', 'pt-BR', 'Cair junto com o adversário, um derrubando o outro quase ao mesmo tempo.', '"Trocou" é considerado resultado neutro em jogos por equipe, porque os dois times perdem um jogador.', 'troca de baixas'),
    ('abrir', 'pt-BR', 'Ser o primeiro a entrar num lugar perigoso, arriscando-se pelo time.', '"Quem abre" é quem toma o primeiro tiro. Função arriscada e valorizada em jogos de tiro tático.', 'entrar primeiro'),
    ('segurar', 'pt-BR', 'Defender uma posição sozinho até os companheiros chegarem.', '"Segura aí" é um pedido de tempo, não de força: o objetivo é atrasar o avanço adversário.', 'defender a posição'),
    ('crashar', 'pt-BR', 'O jogo ou o programa fechar sozinho, do nada.', 'De "crash", colidir. Diferente de travar: no crash o programa some da tela.', 'fechar sozinho'),
    ('otimizado', 'pt-BR', 'Quando o jogo roda bem sem exigir um computador caro.', '"Jogo mal otimizado" é crítica comum: significa que ele pesa mais do que deveria para o que entrega.', 'bem ajustado'),
    ('input lag', 'en', 'O atraso entre apertar o botão e o personagem reagir.', 'Diferente do lag de internet: pode acontecer mesmo jogando sem conexão, por causa da tela ou do controle.', 'atraso de comando'),
    ('macro', 'en', 'Comando gravado que executa várias ações com uma tecla só.', 'Em alguns jogos é permitido; em outros é considerado trapaça, por automatizar o que deveria ser habilidade.', 'comando automático'),
    ('gg wp', 'en', 'Bom jogo e bem jogado, dito no fim da partida.', 'De "good game, well played". É a versão mais educada do "gg", sem margem para ironia.', 'bom jogo, bem jogado'),
    ('sniper', 'en', 'Jogador que atira de longe, escondido, com arma de precisão.', 'Do inglês "sniper", atirador de elite. "Stream sniping" é outra coisa: assistir à transmissão do adversário para saber onde ele está.', 'atirador de longa distância'),
    ('rekt', 'en', 'Provocação dita quando alguém foi derrotado de forma humilhante.', 'Escrita deformada de "wrecked", destruído. Comum como legenda de vídeo de derrota.', 'arrasado'),
    ('git gud', 'en', 'Resposta provocativa a quem reclama: "fica bom", ou seja, treine mais.', 'Escrita deformada de "get good". Virou bordão em comunidades de jogos difíceis.', 'melhore'),
    ('kd', 'en', 'A relação entre quantas vezes o jogador derrubou e foi derrubado.', 'De "kill/death". É a estatística mais citada em jogos de tiro, e também a mais criticada por não medir o que o jogador fez pelo time.', 'proporção de abates'),
    ('wr', 'en', 'Recorde mundial de uma categoria de jogo.', 'De "world record". Em speedrun, cada jogo tem dezenas de categorias, cada uma com seu recorde próprio.', 'recorde mundial'),
    ('pb', 'en', 'O melhor resultado que aquela pessoa já conseguiu.', 'De "personal best". Termo emprestado do atletismo, muito usado em speedrun.', 'melhor marca pessoal'),
    ('nerfaram', 'pt-BR', 'Brincadeira de dizer que algo ficou pior depois de uma mudança.', 'Uso ampliado para fora do jogo: "nerfaram meu café" quer dizer que o café piorou.', 'enfraqueceram'),
    ('respawnar', 'pt-BR', 'Voltar a aparecer depois de sumir.', 'Usado com humor para pessoas: "ele respawnou depois de três meses sumido".', 'reaparecer')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('throw', 'en', 'throwar', 'throwar', 'throwar'),
    ('throw', 'en', 'throwou', 'throwou', 'throwou'),
    ('carry', 'en', 'carregar', 'carregar', 'carregar'),
    ('carry', 'en', 'carregou', 'carregou', 'carregou'),
    ('feed', 'en', 'feedar', 'feedar', 'feedar'),
    ('feed', 'en', 'feedando', 'feedando', 'feedando'),
    ('gank', 'en', 'gankar', 'gankar', 'gankar'),
    ('gank', 'en', 'gankou', 'gankou', 'gankou'),
    ('spawn', 'en', 'spawnar', 'spawnar', 'spawnar'),
    ('spawn', 'en', 'respawn', 'respawn', 'respawn'),
    ('loot', 'en', 'lootar', 'lootar', 'lootar'),
    ('loot', 'en', 'lootando', 'lootando', 'lootando'),
    ('grind', 'en', 'grindar', 'grindar', 'grindar'),
    ('grind', 'en', 'grindando', 'grindando', 'grindando'),
    ('nolife', 'en', 'no life', 'no life', 'no life'),
    ('wipe', 'en', 'wipar', 'wipar', 'wipar'),
    ('wipe', 'en', 'wipamos', 'wipamos', 'wipamos'),
    ('boss', 'en', 'chefão', 'chefao', 'chefao'),
    ('buildar', 'pt-BR', 'build', 'build', 'build'),
    ('upar', 'pt-BR', 'upou', 'upou', 'upou'),
    ('upar', 'pt-BR', 'upando', 'upando', 'upando'),
    ('rushar', 'pt-BR', 'rush', 'rush', 'rush'),
    ('rushar', 'pt-BR', 'rushou', 'rushou', 'rushou'),
    ('farmar', 'pt-BR', 'farm', 'farm', 'farm'),
    ('farmar', 'pt-BR', 'farmando', 'farmando', 'farmando'),
    ('dropar', 'pt-BR', 'drop', 'drop', 'drop'),
    ('dropar', 'pt-BR', 'dropou', 'dropou', 'dropou'),
    ('castar', 'pt-BR', 'caster', 'caster', 'caster'),
    ('castar', 'pt-BR', 'cast', 'cast', 'cast'),
    ('main', 'en', 'mainar', 'mainar', 'mainar'),
    ('gg izi', 'pt-BR', 'gg ez', 'gg ez', 'gg ez'),
    ('gg izi', 'pt-BR', 'ggizi', 'ggizi', 'ggizi'),
    ('queue', 'en', 'queuar', 'queuar', 'queuar'),
    ('cheater', 'en', 'cheat', 'cheat', 'cheat'),
    ('cheater', 'en', 'cheatando', 'cheatando', 'cheatando'),
    ('ranqueada', 'pt-BR', 'ranked', 'ranked', 'ranked'),
    ('ranqueada', 'pt-BR', 'rank', 'rank', 'rank'),
    ('duo', 'en', 'duo queue', 'duo queue', 'duo queue'),
    ('toxico', 'pt-BR', 'toxic', 'toxic', 'toxic'),
    ('reportar', 'pt-BR', 'report', 'report', 'report'),
    ('reportar', 'pt-BR', 'reportado', 'reportado', 'reportado'),
    ('ban', 'en', 'banido', 'banido', 'banido'),
    ('ban', 'en', 'banir', 'banir', 'banir'),
    ('ban', 'en', 'tomou ban', 'tomou ban', 'tomou ban'),
    ('bug', 'en', 'bugado', 'bugado', 'bugado'),
    ('bug', 'en', 'bugar', 'bugar', 'bugar'),
    ('bug', 'en', 'bugou', 'bugou', 'bugou'),
    ('f2p', 'en', 'free to play', 'free to play', 'free to play'),
    ('p2w', 'en', 'pay to win', 'pay to win', 'pay to win'),
    ('cooldown', 'en', 'cd', 'cd', 'cd'),
    ('ragequit', 'en', 'rage quit', 'rage quit', 'rage quit'),
    ('ragequit', 'en', 'dar rage', 'dar rage', 'dar rage'),
    ('dodgear', 'pt-BR', 'dodge', 'dodge', 'dodge'),
    ('dodgear', 'pt-BR', 'dodgeou', 'dodgeou', 'dodgeou'),
    ('one shot', 'en', 'oneshot', 'oneshot', 'oneshot'),
    ('one shot', 'en', 'hitkill', 'hitkill', 'hitkill'),
    ('tank', 'en', 'tankar', 'tankar', 'tankar'),
    ('tank', 'en', 'tankou', 'tankou', 'tankou'),
    ('pushar', 'pt-BR', 'push', 'push', 'push'),
    ('peekar', 'pt-BR', 'peek', 'peek', 'peek'),
    ('clipar', 'pt-BR', 'clip', 'clip', 'clip'),
    ('clipar', 'pt-BR', 'clipe', 'clipe', 'clipe'),
    ('go next', 'en', 'gg go next', 'gg go next', 'gg go next'),
    ('sweat', 'en', 'sweaty', 'sweaty', 'sweaty'),
    ('chocar', 'pt-BR', 'chocando', 'chocando', 'chocando'),
    ('chocar', 'pt-BR', 'chocado', 'chocado', 'chocado'),
    ('crashar', 'pt-BR', 'crash', 'crash', 'crash'),
    ('crashar', 'pt-BR', 'crashou', 'crashou', 'crashou'),
    ('otimizado', 'pt-BR', 'otimizar', 'otimizar', 'otimizar'),
    ('gg wp', 'en', 'ggwp', 'ggwp', 'ggwp'),
    ('rekt', 'en', 'get rekt', 'get rekt', 'get rekt'),
    ('git gud', 'en', 'gitgud', 'gitgud', 'gitgud'),
    ('kd', 'en', 'kda', 'kda', 'kda'),
    ('wr', 'en', 'world record', 'world record', 'world record'),
    ('pb', 'en', 'personal best', 'personal best', 'personal best')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('gg', 'en', 'gaming'),
    ('brb', 'en', 'gaming'),
    ('brb', 'en', 'abreviacao'),
    ('ping', 'en', 'gaming'),
    ('throw', 'en', 'gaming'),
    ('carry', 'en', 'gaming'),
    ('feed', 'en', 'gaming'),
    ('gank', 'en', 'gaming'),
    ('aggro', 'en', 'gaming'),
    ('spawn', 'en', 'gaming'),
    ('loot', 'en', 'gaming'),
    ('grind', 'en', 'gaming'),
    ('meta', 'en', 'gaming'),
    ('nolife', 'en', 'gaming'),
    ('nolife', 'en', 'critica'),
    ('wipe', 'en', 'gaming'),
    ('boss', 'en', 'gaming'),
    ('hitbox', 'en', 'gaming'),
    ('buildar', 'pt-BR', 'gaming'),
    ('nerdar', 'pt-BR', 'gaming'),
    ('upar', 'pt-BR', 'gaming'),
    ('rushar', 'pt-BR', 'gaming'),
    ('farmar', 'pt-BR', 'gaming'),
    ('dropar', 'pt-BR', 'gaming'),
    ('castar', 'pt-BR', 'gaming'),
    ('castar', 'pt-BR', 'esporte'),
    ('main', 'en', 'gaming'),
    ('op', 'en', 'gaming'),
    ('hp', 'en', 'gaming'),
    ('gg izi', 'pt-BR', 'gaming'),
    ('gg izi', 'pt-BR', 'humor'),
    ('pvp', 'en', 'gaming'),
    ('nick', 'en', 'gaming'),
    ('nick', 'en', 'redes'),
    ('lobby', 'en', 'gaming'),
    ('party', 'en', 'gaming'),
    ('queue', 'en', 'gaming'),
    ('hard', 'en', 'gaming'),
    ('cheater', 'en', 'gaming'),
    ('cheater', 'en', 'critica'),
    ('aimbot', 'en', 'gaming'),
    ('aimbot', 'en', 'critica'),
    ('wallhack', 'en', 'gaming'),
    ('wallhack', 'en', 'critica'),
    ('ranqueada', 'pt-BR', 'gaming'),
    ('elo', 'en', 'gaming'),
    ('duo', 'en', 'gaming'),
    ('solo', 'en', 'gaming'),
    ('toxico', 'pt-BR', 'gaming'),
    ('toxico', 'pt-BR', 'critica'),
    ('reportar', 'pt-BR', 'gaming'),
    ('reportar', 'pt-BR', 'redes'),
    ('ban', 'en', 'gaming'),
    ('ban', 'en', 'redes'),
    ('combo', 'en', 'gaming'),
    ('speedrun', 'en', 'gaming'),
    ('glitch', 'en', 'gaming'),
    ('bug', 'en', 'gaming'),
    ('patch', 'en', 'gaming'),
    ('skin', 'en', 'gaming'),
    ('f2p', 'en', 'gaming'),
    ('p2w', 'en', 'gaming'),
    ('p2w', 'en', 'critica'),
    ('gacha', 'en', 'gaming'),
    ('gacha', 'en', 'critica'),
    ('sandbox', 'en', 'gaming'),
    ('cooldown', 'en', 'gaming'),
    ('tryhard', 'en', 'gaming'),
    ('tryhard', 'en', 'critica'),
    ('casual', 'en', 'gaming'),
    ('mira', 'pt-BR', 'gaming'),
    ('ragequit', 'en', 'gaming'),
    ('ragequit', 'en', 'emocao'),
    ('dodgear', 'pt-BR', 'gaming'),
    ('one shot', 'en', 'gaming'),
    ('healer', 'en', 'gaming'),
    ('tank', 'en', 'gaming'),
    ('dps', 'en', 'gaming'),
    ('nolan', 'pt-BR', 'gaming'),
    ('nolan', 'pt-BR', 'humor'),
    ('gamer', 'en', 'gaming'),
    ('setup', 'en', 'gaming'),
    ('fps', 'en', 'gaming'),
    ('mmr', 'en', 'gaming'),
    ('hitar', 'pt-BR', 'gaming'),
    ('pushar', 'pt-BR', 'gaming'),
    ('eco', 'en', 'gaming'),
    ('ace', 'en', 'gaming'),
    ('whiff', 'en', 'gaming'),
    ('peekar', 'pt-BR', 'gaming'),
    ('clipar', 'pt-BR', 'gaming'),
    ('clipar', 'pt-BR', 'streaming'),
    ('montage', 'en', 'gaming'),
    ('highlight', 'en', 'gaming'),
    ('highlight', 'en', 'esporte'),
    ('hardcore', 'en', 'gaming'),
    ('go next', 'en', 'gaming'),
    ('jogar de bot', 'pt-BR', 'gaming'),
    ('jogar de bot', 'pt-BR', 'critica'),
    ('sweat', 'en', 'gaming'),
    ('sweat', 'en', 'critica'),
    ('chocar', 'pt-BR', 'gaming'),
    ('chocar', 'pt-BR', 'humor'),
    ('que roubo', 'pt-BR', 'gaming'),
    ('que roubo', 'pt-BR', 'emocao'),
    ('puxar', 'pt-BR', 'gaming'),
    ('trocar', 'pt-BR', 'gaming'),
    ('abrir', 'pt-BR', 'gaming'),
    ('segurar', 'pt-BR', 'gaming'),
    ('crashar', 'pt-BR', 'gaming'),
    ('otimizado', 'pt-BR', 'gaming'),
    ('input lag', 'en', 'gaming'),
    ('macro', 'en', 'gaming'),
    ('gg wp', 'en', 'gaming'),
    ('sniper', 'en', 'gaming'),
    ('rekt', 'en', 'gaming'),
    ('rekt', 'en', 'humor'),
    ('git gud', 'en', 'gaming'),
    ('git gud', 'en', 'humor'),
    ('kd', 'en', 'gaming'),
    ('wr', 'en', 'gaming'),
    ('wr', 'en', 'esporte'),
    ('pb', 'en', 'gaming'),
    ('pb', 'en', 'esporte'),
    ('nerfaram', 'pt-BR', 'gaming'),
    ('nerfaram', 'pt-BR', 'humor'),
    ('respawnar', 'pt-BR', 'gaming'),
    ('respawnar', 'pt-BR', 'humor')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

