-- ---------------------------------------------------------------------------
-- girias de transmissoes redes e musica
--
-- 108 verbetes, 108 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('live', 'live', 'live', 'en', FALSE, FALSE),
    ('stream', 'stream', 'stream', 'en', FALSE, FALSE),
    ('streamer', 'streamer', 'streamer', 'en', FALSE, FALSE),
    ('chat', 'chat', 'chat', 'en', FALSE, FALSE),
    ('emote', 'emote', 'emote', 'en', FALSE, FALSE),
    ('sub', 'sub', 'sub', 'en', FALSE, FALSE),
    ('raid', 'raid', 'raid', 'en', FALSE, FALSE),
    ('host', 'host', 'host', 'en', FALSE, FALSE),
    ('lurker', 'lurker', 'lurker', 'en', FALSE, FALSE),
    ('mod', 'mod', 'mod', 'en', FALSE, FALSE),
    ('timeout', 'timeout', 'timeout', 'en', FALSE, FALSE),
    ('copium', 'copium', 'copium', 'en', FALSE, FALSE),
    ('hopium', 'hopium', 'hopium', 'en', FALSE, FALSE),
    ('malding', 'malding', 'malding', 'en', FALSE, FALSE),
    ('kekw', 'kekw', 'kekw', 'en', FALSE, FALSE),
    ('monkas', 'monkas', 'monkas', 'en', FALSE, FALSE),
    ('pepega', 'pepega', 'pepega', 'en', FALSE, FALSE),
    ('sadge', 'sadge', 'sadge', 'en', FALSE, FALSE),
    ('based', 'based', 'based', 'en', FALSE, FALSE),
    ('clip it', 'clip it', 'clip it', 'en', FALSE, FALSE),
    ('donate', 'donate', 'donate', 'en', FALSE, FALSE),
    ('bits', 'bits', 'bits', 'en', FALSE, FALSE),
    ('gorjeta', 'gorjeta', 'gorjeta', 'pt-BR', FALSE, FALSE),
    ('vod', 'vod', 'vod', 'en', FALSE, FALSE),
    ('highlight reel', 'highlight reel', 'highlight reel', 'en', FALSE, FALSE),
    ('sub only', 'sub only', 'sub only', 'en', FALSE, FALSE),
    ('slow mode', 'slow mode', 'slow mode', 'en', FALSE, FALSE),
    ('spam', 'spam', 'spam', 'en', FALSE, FALSE),
    ('stream sniping', 'stream sniping', 'stream sniping', 'en', FALSE, FALSE),
    ('cortes', 'cortes', 'cortes', 'pt-BR', FALSE, FALSE),
    ('react', 'react', 'react', 'en', FALSE, FALSE),
    ('colab', 'colab', 'colab', 'pt-BR', FALSE, FALSE),
    ('engajamento', 'engajamento', 'engajamento', 'pt-BR', FALSE, FALSE),
    ('algoritmo', 'algoritmo', 'algoritmo', 'pt-BR', FALSE, FALSE),
    ('viralizar', 'viralizar', 'viralizar', 'pt-BR', FALSE, FALSE),
    ('hype', 'hype', 'hype', 'en', FALSE, FALSE),
    ('overhype', 'overhype', 'overhype', 'en', FALSE, FALSE),
    ('banger', 'banger', 'banger', 'en', FALSE, FALSE),
    ('cover', 'cover', 'cover', 'en', FALSE, FALSE),
    ('playlist', 'playlist', 'playlist', 'en', FALSE, FALSE),
    ('feat', 'feat', 'feat', 'en', FALSE, FALSE),
    ('flow', 'flow', 'flow', 'en', FALSE, FALSE),
    ('drop', 'drop', 'drop', 'en', FALSE, FALSE),
    ('remix', 'remix', 'remix', 'en', FALSE, FALSE),
    ('setlist', 'setlist', 'setlist', 'en', FALSE, FALSE),
    ('podcast', 'podcast', 'podcast', 'en', FALSE, FALSE),
    ('shorts', 'shorts', 'shorts', 'en', FALSE, FALSE),
    ('thumb', 'thumb', 'thumb', 'en', FALSE, FALSE),
    ('clickbait', 'clickbait', 'clickbait', 'en', FALSE, FALSE),
    ('unboxing', 'unboxing', 'unboxing', 'en', FALSE, FALSE),
    ('publi', 'publi', 'publi', 'pt-BR', FALSE, FALSE),
    ('recebidos', 'recebidos', 'recebidos', 'pt-BR', FALSE, FALSE),
    ('nicho', 'nicho', 'nicho', 'pt-BR', FALSE, FALSE),
    ('cancelamento', 'cancelamento', 'cancelamento', 'pt-BR', FALSE, FALSE),
    ('polêmica', 'polemica', 'polemica', 'pt-BR', FALSE, FALSE),
    ('print', 'print', 'print', 'en', FALSE, FALSE),
    ('expor', 'expor', 'expor', 'pt-BR', FALSE, FALSE),
    ('indireta', 'indireta', 'indireta', 'pt-BR', FALSE, FALSE),
    ('vaza', 'vaza', 'vaza', 'pt-BR', FALSE, FALSE),
    ('seguidor', 'seguidor', 'seguidor', 'pt-BR', FALSE, FALSE),
    ('unfollow', 'unfollow', 'unfollow', 'en', FALSE, FALSE),
    ('mutar', 'mutar', 'mutar', 'pt-BR', FALSE, FALSE),
    ('bloquear', 'bloquear', 'bloquear', 'pt-BR', FALSE, FALSE),
    ('close friends', 'close friends', 'close friends', 'en', FALSE, FALSE),
    ('fake', 'fake', 'fake', 'en', FALSE, FALSE),
    ('bot', 'bot', 'bot', 'en', FALSE, FALSE),
    ('trend', 'trend', 'trend', 'en', FALSE, FALSE),
    ('meme', 'meme', 'meme', 'en', FALSE, FALSE),
    ('zoar', 'zoar', 'zoar', 'pt-BR', FALSE, FALSE),
    ('hate', 'hate', 'hate', 'en', FALSE, FALSE),
    ('fandom', 'fandom', 'fandom', 'en', FALSE, FALSE),
    ('stan', 'stan', 'stan', 'en', FALSE, FALSE),
    ('shippar', 'shippar', 'shippar', 'pt-BR', FALSE, FALSE),
    ('canon', 'canon', 'canon', 'en', FALSE, FALSE),
    ('spoiler', 'spoiler', 'spoiler', 'en', FALSE, FALSE),
    ('teoria', 'teoria', 'teoria', 'pt-BR', FALSE, FALSE),
    ('easter egg', 'easter egg', 'easter egg', 'en', FALSE, FALSE),
    ('crossover', 'crossover', 'crossover', 'en', FALSE, FALSE),
    ('arco', 'arco', 'arco', 'pt-BR', FALSE, FALSE),
    ('plot twist', 'plot twist', 'plot twist', 'en', FALSE, FALSE),
    ('npc', 'npc', 'npc', 'en', FALSE, FALSE),
    ('main character', 'main character', 'main character', 'en', FALSE, FALSE),
    ('pov', 'pov', 'pov', 'en', FALSE, FALSE),
    ('storytime', 'storytime', 'storytime', 'en', FALSE, FALSE),
    ('grwm', 'grwm', 'grwm', 'en', FALSE, FALSE),
    ('vlog', 'vlog', 'vlog', 'en', FALSE, FALSE),
    ('tutorial', 'tutorial', 'tutorial', 'pt-BR', FALSE, FALSE),
    ('tier list', 'tier list', 'tier list', 'en', FALSE, FALSE),
    ('top tier', 'top tier', 'top tier', 'en', FALSE, FALSE),
    ('goat', 'goat', 'goat', 'en', FALSE, FALSE),
    ('underrated', 'underrated', 'underrated', 'en', FALSE, FALSE),
    ('overrated', 'overrated', 'overrated', 'en', FALSE, FALSE),
    ('mid', 'mid', 'mid', 'en', FALSE, FALSE),
    ('peak', 'peak', 'peak', 'en', FALSE, FALSE),
    ('core', 'core', 'core', 'en', FALSE, FALSE),
    ('aesthetic', 'aesthetic', 'aesthetic', 'en', FALSE, FALSE),
    ('vibe', 'vibe', 'vibe', 'en', FALSE, FALSE),
    ('mood', 'mood', 'mood', 'en', FALSE, FALSE),
    ('relatable', 'relatable', 'relatable', 'en', FALSE, FALSE),
    ('red flag', 'red flag', 'red flag', 'en', FALSE, FALSE),
    ('green flag', 'green flag', 'green flag', 'en', FALSE, FALSE),
    ('beige flag', 'beige flag', 'beige flag', 'en', FALSE, FALSE),
    ('icônico', 'iconico', 'iconico', 'pt-BR', FALSE, FALSE),
    ('lenda', 'lenda', 'lenda', 'pt-BR', FALSE, FALSE),
    ('chocante', 'chocante', 'chocante', 'pt-BR', FALSE, FALSE),
    ('chorei', 'chorei', 'chorei', 'pt-BR', FALSE, FALSE),
    ('passei mal', 'passei mal', 'passei mal', 'pt-BR', FALSE, FALSE),
    ('surtei', 'surtei', 'surtei', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('live', 'en', 'Transmissão de vídeo ao vivo pela internet, que qualquer um pode assistir na hora.', 'Do inglês "live", ao vivo. Diferente de um vídeo gravado: quem assiste pode conversar com quem transmite pelo chat.', 'transmissão ao vivo'),
    ('stream', 'en', 'O mesmo que transmissão ao vivo pela internet.', 'Do inglês "stream", fluxo. Virou verbo em português: "ele streama todo dia".', 'transmissão'),
    ('streamer', 'en', 'Pessoa que faz transmissões ao vivo pela internet, geralmente jogando.', 'Para muita gente virou profissão. A renda vem de anúncios, doações e assinaturas do público.', 'transmissor'),
    ('chat', 'en', 'A janela de conversa ao lado da transmissão, onde o público escreve.', 'É de onde saem a maior parte das gírias de internet. "O chat tá pegando fogo" quer dizer que muita gente está escrevendo ao mesmo tempo.', 'conversa'),
    ('emote', 'en', 'Figurinha pequena que aparece no lugar de uma palavra, dentro do chat.', 'Cada canal pode ter os seus. Muitas gírias famosas, como "pog" e "kekw", começaram como nome de emote.', 'figurinha'),
    ('sub', 'en', 'Quem paga uma assinatura mensal para apoiar quem transmite.', 'De "subscriber", assinante. Em troca costuma ganhar figurinhas exclusivas e um selo ao lado do nome no chat.', 'assinante'),
    ('raid', 'en', 'Quando quem transmite manda sua plateia para o canal de outra pessoa.', 'Prática comum ao encerrar uma transmissão: é uma forma de apresentar um colega ao próprio público.', 'envio de audiência'),
    ('host', 'en', 'Exibir a transmissão de outra pessoa no próprio canal.', 'Parecido com a raid, mas sem levar o público junto: o canal continua sendo o seu, mostrando conteúdo alheio.', 'hospedar'),
    ('lurker', 'en', 'Quem acompanha mas nunca escreve nada.', 'De "lurk", espreitar. Não tem sentido negativo: é simplesmente quem assiste em silêncio, e costuma ser a maioria do público.', 'espectador silencioso'),
    ('mod', 'en', 'Pessoa encarregada de manter a ordem no chat, apagando ofensas.', 'De "moderator". Costuma ser voluntário escolhido pelo próprio criador, e tem poder de silenciar ou expulsar quem passa dos limites.', 'moderador'),
    ('timeout', 'en', 'Castigo temporário que impede a pessoa de escrever no chat por alguns minutos.', 'Punição mais leve que o banimento. Serve como aviso antes de uma expulsão definitiva.', 'silenciamento temporário'),
    ('copium', 'en', 'Ironia com quem se ilude para não aceitar uma derrota.', 'Junção de "cope", aguentar, com o sufixo de remédio. A piada é tratar a negação como se fosse um calmante que a pessoa toma.', 'autoengano'),
    ('hopium', 'en', 'Esperança exagerada em algo que provavelmente não vai acontecer.', 'Formado como "copium", trocando "cope" por "hope", esperança. Usado quando o time está perdendo feio e alguém ainda acredita na virada.', 'esperança exagerada'),
    ('malding', 'en', 'Alguém muito irritado com algo pequeno, geralmente num jogo.', 'Junção de "mad", bravo, com "balding", ficando careca. A piada é que a pessoa se irrita tanto que perderia cabelo.', 'irritado'),
    ('kekw', 'en', 'Serve para dizer que algo foi muito engraçado, como um "kkkk".', 'Nasceu em chats de transmissão ao vivo. O "kek" vem de comunidades de jogos e equivale ao nosso "kkk"; o "W" foi acrescentado pelo nome de uma figurinha de risada.', 'que engraçado'),
    ('monkas', 'en', 'Reação de nervosismo, quando o público está tenso com o que vai acontecer.', 'Nome de uma figurinha de sapo suando. Aparece no chat em momentos de suspense, como uma jogada decisiva.', 'que tensão'),
    ('pepega', 'en', 'Jeito de dizer que alguém fez uma bobagem, sem ofender de verdade.', 'Nome de figurinha, deformação proposital da palavra "pepe". É zoação leve entre quem já se conhece.', 'que bobagem'),
    ('sadge', 'en', 'Reação de tristeza no chat, quando algo dá errado.', 'De "sad", triste, com terminação inventada. É o equivalente escrito de um suspiro de decepção.', 'que pena'),
    ('based', 'en', 'Elogio a quem fala o que pensa sem se importar com a opinião alheia.', 'Começou como gíria de rua nos Estados Unidos e foi ressignificado na internet. O oposto costuma ser "cringe".', 'autêntico'),
    ('clip it', 'en', 'Pedido no chat para alguém gravar o momento antes que ele se perca.', 'Transmissões ao vivo somem depois de um tempo, então o público pede o recorte quando acontece algo memorável.', 'grave esse trecho'),
    ('donate', 'en', 'Dinheiro que o público manda para quem transmite, junto de uma mensagem lida ao vivo.', 'É uma das principais fontes de renda de quem transmite. A mensagem costuma aparecer na tela e ser lida em voz alta.', 'doação'),
    ('bits', 'en', 'Moeda comprada dentro do site de transmissão para apoiar quem transmite.', 'Funciona como uma doação com figurinha animada. O criador recebe uma parte do valor, e o site fica com o resto.', 'moeda de apoio'),
    ('gorjeta', 'pt-BR', 'Pequena quantia enviada para quem transmite, como agradecimento.', 'Termo em português para o que em inglês se chama "tip". Menor e mais informal que uma doação anunciada.', 'gorjeta'),
    ('vod', 'en', 'A gravação de uma transmissão, que fica salva para assistir depois.', 'De "video on demand". Quem perdeu a transmissão ao vivo assiste o vod, geralmente adiantando as partes paradas.', 'gravação'),
    ('highlight reel', 'en', 'Vídeo curto com os melhores momentos de uma transmissão longa.', 'Transmissões duram horas; o compilado condensa em minutos o que valeu a pena. É o formato que mais circula em outras redes.', 'compilado de melhores momentos'),
    ('sub only', 'en', 'Modo em que só quem paga assinatura pode escrever no chat.', 'Usado para conter enxurrada de mensagens ou ataque coordenado. Quem não assina continua assistindo, mas não escreve.', 'só para assinantes'),
    ('slow mode', 'en', 'Modo que obriga a esperar alguns segundos entre uma mensagem e outra no chat.', 'Serve para o chat ficar legível quando há muita gente assistindo ao mesmo tempo.', 'modo lento'),
    ('spam', 'en', 'Repetir a mesma mensagem várias vezes, enchendo a tela.', 'Nas transmissões costuma ser brincadeira coletiva; em outros contextos é mensagem indesejada em massa, geralmente publicidade.', 'mensagem repetida'),
    ('stream sniping', 'en', 'Assistir à transmissão de alguém para descobrir onde a pessoa está no jogo e persegui-la.', 'É trapaça, porque usa informação que só existe fora da partida. Muitos criadores atrasam a imagem de propósito para se proteger.', 'espionar pela transmissão'),
    ('cortes', 'pt-BR', 'Trechos curtos tirados de uma transmissão longa e publicados separados.', 'Virou um formato próprio no Brasil, com canais dedicados só a recortar transmissões alheias. Costuma ser autorizado pelo criador original.', 'recortes'),
    ('react', 'en', 'Vídeo em que a pessoa assiste a outro conteúdo e comenta enquanto vê.', 'Formato muito popular e muito criticado, porque parte do valor vem do trabalho de quem fez o vídeo original.', 'vídeo de reação'),
    ('colab', 'pt-BR', 'Quando dois criadores fazem um conteúdo juntos.', 'De "collaboration". Serve para os dois apresentarem o público um do outro.', 'colaboração'),
    ('engajamento', 'pt-BR', 'O quanto as pessoas curtem, comentam e compartilham um conteúdo.', 'É a medida que os aplicativos usam para decidir o que mostrar para mais gente. Boa parte do comportamento estranho da internet existe para aumentar esse número.', 'interação do público'),
    ('algoritmo', 'pt-BR', 'O programa que decide quais vídeos e publicações aparecem para cada pessoa.', '"O algoritmo não entregou" quer dizer que o aplicativo mostrou o conteúdo para pouca gente. Virou explicação para tudo que dá errado nas redes.', 'sistema de recomendação'),
    ('viralizar', 'pt-BR', 'Quando algo se espalha muito rápido e é visto por muita gente.', 'Metáfora com vírus: passa de pessoa para pessoa. Pode ser bom ou péssimo, dependendo do motivo.', 'espalhar rapidamente'),
    ('hype', 'en', 'Empolgação coletiva com algo que ainda vai acontecer.', 'Do inglês "hype", exagero publicitário. "Tô hypado" quer dizer ansioso e animado. "Hype morreu" é quando a empolgação passou.', 'empolgação'),
    ('overhype', 'en', 'Empolgação exagerada que faz a coisa decepcionar quando chega.', 'O problema não é a qualidade do que veio, e sim o tamanho da expectativa criada antes.', 'expectativa exagerada'),
    ('banger', 'en', 'Música ou conteúdo muito bom, que empolga de primeira.', 'De "bang", estrondo. Usado principalmente para música, mas também para vídeos e partidas memoráveis.', 'excelente'),
    ('cover', 'en', 'Versão de uma música conhecida cantada por outra pessoa.', 'Diferente de plágio: o cover assume abertamente que a música é de outro artista.', 'regravação'),
    ('playlist', 'en', 'Lista de músicas montada para tocar em sequência.', 'Virou também forma de expressão: as pessoas montam listas com nome e tema, e compartilham como quem empresta um disco.', 'lista de músicas'),
    ('feat', 'en', 'Música em que dois artistas cantam juntos.', 'Abreviação de "featuring", participação. Aparece no título da música, entre os nomes dos artistas.', 'participação'),
    ('flow', 'en', 'O jeito e o ritmo com que a pessoa canta ou fala, principalmente no rap.', 'Do inglês "flow", fluxo. "Flow bom" é elogio ao ritmo e ao encaixe das palavras, não à letra em si.', 'cadência'),
    ('drop', 'en', 'O momento da música em que a batida entra com tudo.', 'Muito usado em música eletrônica. É o ponto que o público espera e que costuma aparecer nos vídeos curtos.', 'virada'),
    ('remix', 'en', 'Versão modificada de uma música, com batida ou arranjo diferentes.', 'Diferente do cover, que regrava: o remix reaproveita a gravação original e altera partes dela.', 'versão remixada'),
    ('setlist', 'en', 'A ordem das músicas que o artista vai tocar num show.', 'Divulgar a setlist antes do show é assunto de discussão entre fãs, porque tira a surpresa.', 'repertório'),
    ('podcast', 'en', 'Programa de conversa gravado, que a pessoa escuta quando quiser.', 'Junção de "iPod" com "broadcast". Hoje boa parte é gravada em vídeo também, e o nome ficou mesmo assim.', 'programa de áudio'),
    ('shorts', 'en', 'Vídeos bem curtos, de segundos, que passam um atrás do outro.', 'Formato criado pelo TikTok e copiado pelas outras redes. É onde nasce boa parte das gírias novas hoje.', 'vídeo curto'),
    ('thumb', 'en', 'A imagem de capa que aparece antes de a pessoa clicar no vídeo.', 'De "thumbnail", miniatura. É o que mais influencia se alguém vai clicar, e por isso costuma ser exagerada de propósito.', 'capa do vídeo'),
    ('clickbait', 'en', 'Título ou capa que promete muito mais do que o vídeo entrega.', 'De "click" com "bait", isca. É crítica: o conteúdo não corresponde ao que foi anunciado.', 'isca de clique'),
    ('unboxing', 'en', 'Vídeo em que a pessoa abre um produto pela primeira vez diante da câmera.', 'Formato antigo e ainda popular. Muitas vezes o produto foi enviado de graça pela marca, o que deveria ser informado.', 'abertura de produto'),
    ('publi', 'pt-BR', 'Conteúdo pago por uma marca, que a pessoa publica como se fosse comum.', 'Abreviação de "publicidade". No Brasil o Conar exige que seja identificado, mas nem sempre é.', 'publicidade paga'),
    ('recebidos', 'pt-BR', 'Produtos que marcas mandaram de graça para o criador mostrar.', 'Vídeos de "recebidos" são um formato próprio. Não são obrigatoriamente publicidade paga, mas a relação com a marca existe.', 'produtos enviados'),
    ('nicho', 'pt-BR', 'O assunto específico sobre o qual um criador fala.', '"Achar seu nicho" é encontrar um público pequeno mas fiel, em vez de tentar agradar todo mundo.', 'área de atuação'),
    ('cancelamento', 'pt-BR', 'Quando muita gente decide parar de apoiar alguém por causa de algo que a pessoa fez ou disse.', 'O efeito real varia muito: às vezes a carreira acaba, às vezes passa em uma semana. O termo é usado tanto por quem apoia quanto por quem critica a prática.', 'boicote coletivo'),
    ('polemica', 'pt-BR', 'Discussão pública grande envolvendo pessoas conhecidas na internet.', 'Tem ciclo previsível: acusação, resposta em vídeo, prints antigos, e esquecimento em poucos dias.', 'controvérsia'),
    ('print', 'en', 'Foto da tela, usada como prova de uma conversa.', 'De "print screen". "Tem print" quer dizer que a pessoa guardou a evidência.', 'captura de tela'),
    ('expor', 'pt-BR', 'Tornar público algo particular sobre alguém, geralmente para prejudicar.', 'Do inglês "expose". Pode ser denúncia legítima ou vingança pessoal, e a diferença nem sempre fica clara para quem assiste.', 'expor publicamente'),
    ('indireta', 'pt-BR', 'Mensagem que critica alguém sem dizer o nome, mas todo mundo entende para quem é.', 'Formato antigo que a internet ampliou. "Mandar indireta" é comum em publicações depois de uma briga.', 'crítica velada'),
    ('vaza', 'pt-BR', 'Quando algo particular acaba se tornando público sem autorização.', 'Vale para música antes do lançamento, conversa privada ou dado pessoal. Nos dois últimos casos, é crime no Brasil.', 'divulgação não autorizada'),
    ('seguidor', 'pt-BR', 'Quem escolheu acompanhar as publicações de alguém.', 'Número de seguidores virou medida informal de importância, apesar de dizer pouco sobre quantas pessoas realmente prestam atenção.', 'seguidor'),
    ('unfollow', 'en', 'Parar de acompanhar as publicações de alguém.', 'Diferente de bloquear: a pessoa ainda pode ver seu perfil, só não recebe mais suas publicações.', 'deixar de seguir'),
    ('mutar', 'pt-BR', 'Continuar seguindo alguém mas parar de ver o que a pessoa publica.', 'Serve para evitar constrangimento: a pessoa não descobre, porque continua na lista de seguidores.', 'silenciar'),
    ('bloquear', 'pt-BR', 'Impedir completamente que alguém veja seu perfil ou fale com você.', 'A medida mais forte. Diferente de silenciar, é visível: a pessoa percebe que foi bloqueada.', 'bloquear'),
    ('close friends', 'en', 'Lista restrita de pessoas que veem publicações que os outros seguidores não veem.', 'Recurso do Instagram, marcado com um círculo verde. Virou espaço para conteúdo mais pessoal ou mais solto.', 'lista restrita'),
    ('fake', 'en', 'Perfil falso, com nome e foto que não são da pessoa real.', 'Pode ser inofensivo, para acompanhar alguém sem ser reconhecido, ou usado para golpe e perseguição.', 'perfil falso'),
    ('bot', 'en', 'Conta automática, controlada por programa, que não é uma pessoa de verdade.', 'Usadas para inflar número de seguidores ou espalhar mensagem em massa. "Comentário de bot" costuma ser genérico e repetido.', 'conta automática'),
    ('trend', 'en', 'Assunto ou brincadeira que muita gente está repetindo no momento.', 'Nos vídeos curtos, participar de uma trend é refazer o mesmo formato com a mesma música. Dura poucos dias.', 'tendência'),
    ('meme', 'en', 'Imagem, frase ou vídeo engraçado que muita gente repete e adapta.', 'A palavra é anterior à internet: foi criada em 1976 pelo biólogo Richard Dawkins para descrever ideias que se espalham como genes.', 'piada repetida'),
    ('zoar', 'pt-BR', 'Fazer piada com alguém ou com alguma situação.', 'Nem sempre é agressivo, mas o limite entre zoar e ofender é justamente o que costuma gerar briga.', 'brincar'),
    ('hate', 'en', 'Comentários de ódio dirigidos a alguém.', '"Receber hate" é ser alvo de ataques; "hater" é quem faz isso de forma constante, quase como um hábito.', 'ataques'),
    ('fandom', 'en', 'O conjunto de fãs de alguma coisa, tratado como uma comunidade com regras próprias.', 'Junção de "fan" com "kingdom". Fandoms grandes têm vocabulário, brigas internas e memória coletiva próprios.', 'comunidade de fãs'),
    ('stan', 'en', 'Fã muito dedicado a alguém.', 'Vem de uma música do ano 2000 que narra um fã obsessivo. Hoje é usado também como verbo: "eu stano".', 'fã dedicado'),
    ('shippar', 'pt-BR', 'Torcer para que duas pessoas fiquem juntas.', 'Do inglês "relationship". Aplica-se a personagens de ficção e também a pessoas reais, o que às vezes incomoda os envolvidos.', 'torcer pelo casal'),
    ('canon', 'en', 'O que é oficialmente verdade dentro de uma história.', 'O oposto é o que os fãs inventam por conta própria. "Virou canon" quer dizer que a obra confirmou algo que era só teoria.', 'oficial'),
    ('spoiler', 'en', 'Contar o final ou uma surpresa de algo que a pessoa ainda não viu.', 'De "spoil", estragar. Virou verbo em português: "não me spoila".', 'revelação indevida'),
    ('teoria', 'pt-BR', 'Palpite dos fãs sobre o que vai acontecer numa história.', 'Formato de conteúdo próprio: canais inteiros vivem de montar teorias sobre séries e jogos.', 'hipótese de fã'),
    ('easter egg', 'en', 'Detalhe escondido de propósito, para quem prestar muita atenção encontrar.', 'De "ovo de Páscoa", pela brincadeira de esconder ovos. Comum em jogos e filmes.', 'detalhe escondido'),
    ('crossover', 'en', 'Quando personagens de histórias diferentes aparecem juntos.', 'Do inglês "cross over", atravessar. Fora da ficção, também descreve encontros inesperados entre pessoas de mundos diferentes.', 'encontro de universos'),
    ('arco', 'pt-BR', 'Uma fase da vida de alguém, contada como se fosse capítulo de história.', 'Vem de "arco narrativo". "Tô no meu arco de estudos" é jeito bem-humorado de dizer que a pessoa entrou numa fase nova.', 'fase'),
    ('plot twist', 'en', 'Reviravolta inesperada numa história ou numa situação real.', 'Usado com humor no dia a dia: "plot twist: era eu quem estava errado".', 'reviravolta'),
    ('npc', 'en', 'Pessoa que age no automático, sem opinião própria.', 'Nos jogos, NPC é um personagem controlado pelo computador, com falas repetidas. Aplicado a uma pessoa, é crítica.', 'sem opinião própria'),
    ('main character', 'en', 'Quem age como se o mundo girasse em torno dele.', 'Pode ser crítica ou incentivo: "seja o main character da sua vida" é usado como conselho de autoestima.', 'protagonista'),
    ('pov', 'en', 'Vídeo feito como se a câmera fosse os olhos de quem assiste.', 'De "point of view", ponto de vista. Virou formato de vídeo curto, geralmente com uma legenda descrevendo a situação imaginada.', 'ponto de vista'),
    ('storytime', 'en', 'Vídeo em que a pessoa conta um caso que aconteceu com ela.', 'Formato muito comum em vídeos curtos, geralmente com algo acontecendo na tela enquanto a história é narrada.', 'relato'),
    ('grwm', 'en', 'Vídeo em que a pessoa se arruma enquanto conversa com a câmera.', 'De "get ready with me", se arrume comigo. O assunto costuma ser outro: arrumar-se é só o pano de fundo.', 'vídeo de rotina'),
    ('vlog', 'en', 'Vídeo em que a pessoa mostra o próprio dia.', 'Junção de "vídeo" com "blog". É um dos formatos mais antigos da internet em vídeo.', 'diário em vídeo'),
    ('tutorial', 'pt-BR', 'Vídeo ou texto que ensina passo a passo como fazer algo.', 'Buscar tutorial virou o primeiro reflexo diante de qualquer tarefa desconhecida.', 'guia'),
    ('tier list', 'en', 'Lista que classifica coisas em níveis, do melhor ao pior.', 'Os níveis costumam ir de S, o melhor, até F, o pior. Formato de vídeo popular por gerar discussão fácil.', 'classificação por níveis'),
    ('top tier', 'en', 'Do melhor nível possível.', 'De "tier", camada. Usado para qualquer coisa: "esse bolo é top tier".', 'excelente'),
    ('goat', 'en', 'O maior de todos os tempos numa área.', 'De "greatest of all time". Coincide com a palavra inglesa para cabra, o que rendeu a imagem de cabra como símbolo.', 'o maior de todos'),
    ('underrated', 'en', 'Algo bom que recebe menos atenção do que merece.', 'O oposto é "overrated", quando algo é elogiado além do que vale.', 'subestimado'),
    ('overrated', 'en', 'Algo elogiado muito além do que realmente merece.', 'Chamar algo popular de overrated é uma das discussões mais recorrentes da internet.', 'superestimado'),
    ('mid', 'en', 'Mediano, nada demais.', 'Do inglês "middle", meio. Usado para dizer que algo muito elogiado é, na verdade, comum.', 'mediano'),
    ('peak', 'en', 'O melhor momento de algo ou de alguém.', '"Ele tá no peak" quer dizer que a pessoa está no auge. Também usado com nostalgia: "aquele ano foi o peak da internet".', 'auge'),
    ('core', 'en', 'Sufixo que marca um estilo visual ou estético.', 'Aparece colado em outra palavra: "cottagecore", "weirdcore". Descreve um conjunto de imagens, cores e sensações, mais que um assunto.', 'estética'),
    ('aesthetic', 'en', 'O visual e o clima de algo, quando isso é o ponto principal.', '"Muito aesthetic" é elogio a algo bonito de um jeito específico e coerente, não apenas bonito.', 'visual'),
    ('vibe', 'en', 'O clima ou a sensação que algo ou alguém passa.', '"Boa vibe" e "má vibe" são sensações, não análises. "Vibe check" é uma checagem bem-humorada de como a pessoa está.', 'clima'),
    ('mood', 'en', 'Comentário dizendo que aquilo representa exatamente como a pessoa se sente.', 'Do inglês "mood", humor. Escrever só "mood" embaixo de uma imagem é dizer "sou eu".', 'é isso mesmo'),
    ('relatable', 'en', 'Algo com que a pessoa se identifica de imediato.', '"Muito relatable" quer dizer que a situação descrita acontece com quem está lendo também.', 'identificável'),
    ('red flag', 'en', 'Sinal de alerta sobre alguém, que indica problema à frente.', 'Vem das bandeiras vermelhas de aviso em praias e corridas. Muito usado para falar de relacionamentos.', 'sinal de alerta'),
    ('green flag', 'en', 'Sinal bom sobre alguém, que indica que a pessoa é de confiança.', 'Criado como oposto de "red flag", e bem mais recente que ele.', 'bom sinal'),
    ('beige flag', 'en', 'Mania estranha de alguém que não é boa nem ruim, só esquisita.', 'Bege por ser neutro, entre o vermelho e o verde. Termo recente, quase sempre usado com humor.', 'mania inofensiva'),
    ('iconico', 'pt-BR', 'Marcante a ponto de virar referência.', 'Usado com generosidade na internet: qualquer momento engraçado pode ser chamado de icônico.', 'memorável'),
    ('lenda', 'pt-BR', 'Elogio a alguém que fez algo admirável.', '"É uma lenda" quer dizer que a pessoa merece reconhecimento, mesmo por algo pequeno.', 'admirável'),
    ('chocante', 'pt-BR', 'Reação exagerada de surpresa, muitas vezes irônica.', 'Raramente indica choque de verdade. Costuma ser resposta bem-humorada a algo previsível.', 'surpreendente'),
    ('chorei', 'pt-BR', 'Jeito de dizer que algo foi muito engraçado, de tanto rir.', 'Fora do contexto de humor, mantém o sentido literal. O que separa os dois é o assunto da conversa.', 'ri muito'),
    ('passei mal', 'pt-BR', 'Reação a algo muito engraçado ou muito constrangedor.', 'Quase nunca é literal. "Passei mal de rir" é a forma completa, e o "de rir" costuma ser omitido.', 'reagi muito'),
    ('surtei', 'pt-BR', 'Reagi de forma muito intensa, de empolgação ou de nervoso.', 'O contexto separa os dois usos. Na internet costuma ser empolgação; fora dela pode indicar crise real, e vale prestar atenção.', 'reagi intensamente')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('live', 'en', 'lives', 'lives', 'lives'),
    ('live', 'en', 'tá em live', 'ta em live', 'ta em live'),
    ('stream', 'en', 'streamar', 'streamar', 'streamar'),
    ('stream', 'en', 'streaming', 'streaming', 'streaming'),
    ('emote', 'en', 'emotes', 'emotes', 'emotes'),
    ('sub', 'en', 'subscriber', 'subscriber', 'subscriber'),
    ('sub', 'en', 'subar', 'subar', 'subar'),
    ('host', 'en', 'hostear', 'hostear', 'hostear'),
    ('lurker', 'en', 'lurkando', 'lurkando', 'lurkando'),
    ('lurker', 'en', 'lurk', 'lurk', 'lurk'),
    ('mod', 'en', 'moderador', 'moderador', 'moderador'),
    ('mod', 'en', 'modar', 'modar', 'modar'),
    ('timeout', 'en', 'tomar timeout', 'tomar timeout', 'tomar timeout'),
    ('kekw', 'en', 'kek', 'kek', 'kek'),
    ('clip it', 'en', 'clipa isso', 'clipa isso', 'clipa isso'),
    ('donate', 'en', 'donate', 'donate', 'donate'),
    ('donate', 'en', 'doação', 'doacao', 'doacao'),
    ('donate', 'en', 'donation', 'donation', 'donation'),
    ('gorjeta', 'pt-BR', 'tip', 'tip', 'tip'),
    ('spam', 'en', 'spammar', 'spammar', 'spammar'),
    ('spam', 'en', 'spamando', 'spamando', 'spamando'),
    ('stream sniping', 'en', 'stream snipar', 'stream snipar', 'stream snipar'),
    ('cortes', 'pt-BR', 'canal de cortes', 'canal de cortes', 'canal de cortes'),
    ('react', 'en', 'reagir', 'reagir', 'reagir'),
    ('react', 'en', 'reação', 'reacao', 'reacao'),
    ('colab', 'pt-BR', 'collab', 'collab', 'collab'),
    ('colab', 'pt-BR', 'colaboração', 'colaboracao', 'colaboracao'),
    ('viralizar', 'pt-BR', 'viral', 'viral', 'viral'),
    ('viralizar', 'pt-BR', 'viralizou', 'viralizou', 'viralizou'),
    ('hype', 'en', 'hypado', 'hypado', 'hypado'),
    ('hype', 'en', 'hypar', 'hypar', 'hypar'),
    ('feat', 'en', 'featuring', 'featuring', 'featuring'),
    ('shorts', 'en', 'reels', 'reels', 'reels'),
    ('shorts', 'en', 'vídeo curto', 'video curto', 'video curto'),
    ('thumb', 'en', 'thumbnail', 'thumbnail', 'thumbnail'),
    ('thumb', 'en', 'capa', 'capa', 'capa'),
    ('publi', 'pt-BR', 'publipost', 'publipost', 'publipost'),
    ('publi', 'pt-BR', 'publieditorial', 'publieditorial', 'publieditorial'),
    ('cancelamento', 'pt-BR', 'cancelado', 'cancelado', 'cancelado'),
    ('cancelamento', 'pt-BR', 'cancelar', 'cancelar', 'cancelar'),
    ('polemica', 'pt-BR', 'treta', 'treta', 'treta'),
    ('polemica', 'pt-BR', 'climão', 'climao', 'climao'),
    ('print', 'en', 'printar', 'printar', 'printar'),
    ('print', 'en', 'printou', 'printou', 'printou'),
    ('expor', 'pt-BR', 'exposed', 'exposed', 'exposed'),
    ('expor', 'pt-BR', 'exposição', 'exposicao', 'exposicao'),
    ('indireta', 'pt-BR', 'indiretas', 'indiretas', 'indiretas'),
    ('vaza', 'pt-BR', 'vazou', 'vazou', 'vazou'),
    ('vaza', 'pt-BR', 'vazamento', 'vazamento', 'vazamento'),
    ('seguidor', 'pt-BR', 'follower', 'follower', 'follower'),
    ('seguidor', 'pt-BR', 'seguir', 'seguir', 'seguir'),
    ('unfollow', 'en', 'deixar de seguir', 'deixar de seguir', 'deixar de seguir'),
    ('mutar', 'pt-BR', 'mute', 'mute', 'mute'),
    ('mutar', 'pt-BR', 'silenciar', 'silenciar', 'silenciar'),
    ('bloquear', 'pt-BR', 'block', 'block', 'block'),
    ('bloquear', 'pt-BR', 'bloqueado', 'bloqueado', 'bloqueado'),
    ('close friends', 'en', 'melhores amigos', 'melhores amigos', 'melhores amigos'),
    ('fake', 'en', 'perfil fake', 'perfil fake', 'perfil fake'),
    ('trend', 'en', 'trending', 'trending', 'trending'),
    ('trend', 'en', 'tendência', 'tendencia', 'tendencia'),
    ('zoar', 'pt-BR', 'zoando', 'zoando', 'zoando'),
    ('zoar', 'pt-BR', 'zoação', 'zoacao', 'zoacao'),
    ('hate', 'en', 'hater', 'hater', 'hater'),
    ('stan', 'en', 'stanear', 'stanear', 'stanear'),
    ('shippar', 'pt-BR', 'ship', 'ship', 'ship'),
    ('shippar', 'pt-BR', 'shippo', 'shippo', 'shippo'),
    ('spoiler', 'en', 'spoilar', 'spoilar', 'spoilar'),
    ('spoiler', 'en', 'spoilou', 'spoilou', 'spoilou'),
    ('arco', 'pt-BR', 'arc', 'arc', 'arc'),
    ('main character', 'en', 'personagem principal', 'personagem principal', 'personagem principal'),
    ('grwm', 'en', 'get ready with me', 'get ready with me', 'get ready with me'),
    ('tutorial', 'pt-BR', 'tuto', 'tuto', 'tuto'),
    ('aesthetic', 'en', 'estética', 'estetica', 'estetica'),
    ('vibe', 'en', 'vibes', 'vibes', 'vibes'),
    ('vibe', 'en', 'vibe boa', 'vibe boa', 'vibe boa'),
    ('red flag', 'en', 'bandeira vermelha', 'bandeira vermelha', 'bandeira vermelha'),
    ('iconico', 'pt-BR', 'iconic', 'iconic', 'iconic')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('live', 'en', 'streaming'),
    ('stream', 'en', 'streaming'),
    ('streamer', 'en', 'streaming'),
    ('chat', 'en', 'streaming'),
    ('chat', 'en', 'redes'),
    ('emote', 'en', 'streaming'),
    ('sub', 'en', 'streaming'),
    ('raid', 'en', 'streaming'),
    ('host', 'en', 'streaming'),
    ('lurker', 'en', 'streaming'),
    ('mod', 'en', 'streaming'),
    ('mod', 'en', 'redes'),
    ('timeout', 'en', 'streaming'),
    ('copium', 'en', 'streaming'),
    ('copium', 'en', 'humor'),
    ('hopium', 'en', 'streaming'),
    ('hopium', 'en', 'humor'),
    ('malding', 'en', 'streaming'),
    ('malding', 'en', 'emocao'),
    ('kekw', 'en', 'streaming'),
    ('kekw', 'en', 'humor'),
    ('monkas', 'en', 'streaming'),
    ('monkas', 'en', 'emocao'),
    ('pepega', 'en', 'streaming'),
    ('pepega', 'en', 'humor'),
    ('sadge', 'en', 'streaming'),
    ('sadge', 'en', 'emocao'),
    ('based', 'en', 'streaming'),
    ('based', 'en', 'redes'),
    ('clip it', 'en', 'streaming'),
    ('donate', 'en', 'streaming'),
    ('bits', 'en', 'streaming'),
    ('gorjeta', 'pt-BR', 'streaming'),
    ('vod', 'en', 'streaming'),
    ('highlight reel', 'en', 'streaming'),
    ('sub only', 'en', 'streaming'),
    ('slow mode', 'en', 'streaming'),
    ('spam', 'en', 'streaming'),
    ('spam', 'en', 'redes'),
    ('stream sniping', 'en', 'streaming'),
    ('stream sniping', 'en', 'gaming'),
    ('stream sniping', 'en', 'critica'),
    ('cortes', 'pt-BR', 'streaming'),
    ('react', 'en', 'streaming'),
    ('colab', 'pt-BR', 'streaming'),
    ('colab', 'pt-BR', 'redes'),
    ('engajamento', 'pt-BR', 'streaming'),
    ('engajamento', 'pt-BR', 'redes'),
    ('algoritmo', 'pt-BR', 'redes'),
    ('algoritmo', 'pt-BR', 'streaming'),
    ('viralizar', 'pt-BR', 'redes'),
    ('viralizar', 'pt-BR', 'streaming'),
    ('hype', 'en', 'streaming'),
    ('hype', 'en', 'emocao'),
    ('overhype', 'en', 'streaming'),
    ('overhype', 'en', 'critica'),
    ('banger', 'en', 'streaming'),
    ('banger', 'en', 'musica'),
    ('banger', 'en', 'elogio'),
    ('cover', 'en', 'musica'),
    ('playlist', 'en', 'musica'),
    ('feat', 'en', 'musica'),
    ('flow', 'en', 'musica'),
    ('drop', 'en', 'musica'),
    ('remix', 'en', 'musica'),
    ('setlist', 'en', 'musica'),
    ('podcast', 'en', 'streaming'),
    ('shorts', 'en', 'redes'),
    ('thumb', 'en', 'streaming'),
    ('thumb', 'en', 'redes'),
    ('clickbait', 'en', 'redes'),
    ('clickbait', 'en', 'critica'),
    ('unboxing', 'en', 'redes'),
    ('publi', 'pt-BR', 'redes'),
    ('recebidos', 'pt-BR', 'redes'),
    ('nicho', 'pt-BR', 'redes'),
    ('cancelamento', 'pt-BR', 'redes'),
    ('cancelamento', 'pt-BR', 'critica'),
    ('polemica', 'pt-BR', 'redes'),
    ('print', 'en', 'redes'),
    ('expor', 'pt-BR', 'redes'),
    ('expor', 'pt-BR', 'critica'),
    ('indireta', 'pt-BR', 'redes'),
    ('vaza', 'pt-BR', 'redes'),
    ('seguidor', 'pt-BR', 'redes'),
    ('unfollow', 'en', 'redes'),
    ('mutar', 'pt-BR', 'redes'),
    ('bloquear', 'pt-BR', 'redes'),
    ('close friends', 'en', 'redes'),
    ('fake', 'en', 'redes'),
    ('bot', 'en', 'redes'),
    ('trend', 'en', 'redes'),
    ('meme', 'en', 'redes'),
    ('meme', 'en', 'humor'),
    ('zoar', 'pt-BR', 'humor'),
    ('hate', 'en', 'redes'),
    ('hate', 'en', 'critica'),
    ('fandom', 'en', 'redes'),
    ('stan', 'en', 'redes'),
    ('shippar', 'pt-BR', 'redes'),
    ('shippar', 'pt-BR', 'relacionamento'),
    ('canon', 'en', 'redes'),
    ('spoiler', 'en', 'redes'),
    ('teoria', 'pt-BR', 'redes'),
    ('easter egg', 'en', 'redes'),
    ('easter egg', 'en', 'gaming'),
    ('crossover', 'en', 'redes'),
    ('arco', 'pt-BR', 'redes'),
    ('plot twist', 'en', 'redes'),
    ('plot twist', 'en', 'humor'),
    ('npc', 'en', 'redes'),
    ('npc', 'en', 'critica'),
    ('main character', 'en', 'redes'),
    ('main character', 'en', 'critica'),
    ('pov', 'en', 'redes'),
    ('storytime', 'en', 'redes'),
    ('grwm', 'en', 'redes'),
    ('vlog', 'en', 'redes'),
    ('tutorial', 'pt-BR', 'redes'),
    ('tier list', 'en', 'redes'),
    ('tier list', 'en', 'gaming'),
    ('top tier', 'en', 'elogio'),
    ('goat', 'en', 'elogio'),
    ('goat', 'en', 'esporte'),
    ('underrated', 'en', 'elogio'),
    ('overrated', 'en', 'critica'),
    ('mid', 'en', 'critica'),
    ('peak', 'en', 'elogio'),
    ('core', 'en', 'redes'),
    ('aesthetic', 'en', 'redes'),
    ('vibe', 'en', 'emocao'),
    ('mood', 'en', 'emocao'),
    ('relatable', 'en', 'emocao'),
    ('red flag', 'en', 'relacionamento'),
    ('red flag', 'en', 'atencao'),
    ('green flag', 'en', 'relacionamento'),
    ('green flag', 'en', 'elogio'),
    ('beige flag', 'en', 'relacionamento'),
    ('beige flag', 'en', 'humor'),
    ('iconico', 'pt-BR', 'elogio'),
    ('lenda', 'pt-BR', 'elogio'),
    ('chocante', 'pt-BR', 'emocao'),
    ('chocante', 'pt-BR', 'humor'),
    ('chorei', 'pt-BR', 'humor'),
    ('chorei', 'pt-BR', 'emocao'),
    ('passei mal', 'pt-BR', 'humor'),
    ('passei mal', 'pt-BR', 'emocao'),
    ('surtei', 'pt-BR', 'emocao')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

