-- ---------------------------------------------------------------------------
-- girias de internet brasileira e abreviacoes
--
-- 103 verbetes, 105 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('vc', 'vc', 'vc', 'pt-BR', FALSE, FALSE),
    ('tb', 'tb', 'tb', 'pt-BR', FALSE, FALSE),
    ('pq', 'pq', 'pq', 'pt-BR', FALSE, FALSE),
    ('qnd', 'qnd', 'qnd', 'pt-BR', FALSE, FALSE),
    ('mt', 'mt', 'mt', 'pt-BR', FALSE, FALSE),
    ('blz', 'blz', 'blz', 'pt-BR', FALSE, FALSE),
    ('vlw', 'vlw', 'vlw', 'pt-BR', FALSE, FALSE),
    ('flw', 'flw', 'flw', 'pt-BR', FALSE, FALSE),
    ('add', 'add', 'add', 'pt-BR', FALSE, FALSE),
    ('obg', 'obg', 'obg', 'pt-BR', FALSE, FALSE),
    ('dnv', 'dnv', 'dnv', 'pt-BR', FALSE, FALSE),
    ('hj', 'hj', 'hj', 'pt-BR', FALSE, FALSE),
    ('ontem', 'ontem', 'ontem', 'pt-BR', FALSE, FALSE),
    ('amanha', 'amanha', 'amanha', 'pt-BR', FALSE, FALSE),
    ('n', 'n', 'n', 'pt-BR', FALSE, FALSE),
    ('s2', 's2', 's2', 'pt-BR', FALSE, FALSE),
    ('kkk', 'kkk', 'kk', 'pt-BR', FALSE, FALSE),
    ('mds', 'mds', 'mds', 'pt-BR', FALSE, FALSE),
    ('sqn', 'sqn', 'sqn', 'pt-BR', FALSE, FALSE),
    ('pdc', 'pdc', 'pdc', 'pt-BR', FALSE, FALSE),
    ('aff', 'aff', 'aff', 'pt-BR', FALSE, FALSE),
    ('eita', 'eita', 'eita', 'pt-BR', FALSE, FALSE),
    ('vish', 'vish', 'vish', 'pt-BR', FALSE, FALSE),
    ('nossa', 'nossa', 'nossa', 'pt-BR', FALSE, FALSE),
    ('caraca', 'caraca', 'caraca', 'pt-BR', FALSE, FALSE),
    ('putz', 'putz', 'putz', 'pt-BR', FALSE, FALSE),
    ('ué', 'ue', 'ue', 'pt-BR', FALSE, FALSE),
    ('sla', 'sla', 'sla', 'pt-BR', FALSE, FALSE),
    ('tlgd', 'tlgd', 'tlgd', 'pt-BR', FALSE, FALSE),
    ('tmj', 'tmj', 'tmj', 'pt-BR', FALSE, FALSE),
    ('flws', 'flws', 'flws', 'pt-BR', FALSE, FALSE),
    ('brincs', 'brincs', 'brincs', 'pt-BR', FALSE, FALSE),
    ('zap', 'zap', 'zap', 'pt-BR', FALSE, FALSE),
    ('insta', 'insta', 'insta', 'pt-BR', FALSE, FALSE),
    ('direct', 'direct', 'direct', 'en', FALSE, FALSE),
    ('status', 'status', 'status', 'pt-BR', FALSE, FALSE),
    ('stories', 'stories', 'stories', 'en', FALSE, FALSE),
    ('feed', 'feed', 'feed', 'pt-BR', FALSE, FALSE),
    ('arroba', 'arroba', 'arroba', 'pt-BR', FALSE, FALSE),
    ('marcar', 'marcar', 'marcar', 'pt-BR', FALSE, FALSE),
    ('salvar', 'salvar', 'salvar', 'pt-BR', FALSE, FALSE),
    ('compartilhar', 'compartilhar', 'compartilhar', 'pt-BR', FALSE, FALSE),
    ('printar', 'printar', 'printar', 'pt-BR', FALSE, FALSE),
    ('stalkear', 'stalkear', 'stalkear', 'pt-BR', FALSE, FALSE),
    ('crush', 'crush', 'crush', 'pt-BR', FALSE, FALSE),
    ('mozão', 'mozao', 'mozao', 'pt-BR', FALSE, FALSE),
    ('ficar', 'ficar', 'ficar', 'pt-BR', FALSE, FALSE),
    ('dar o perdido', 'dar o perdido', 'dar o perdido', 'pt-BR', FALSE, FALSE),
    ('ghosting', 'ghosting', 'ghosting', 'en', FALSE, FALSE),
    ('sextou', 'sextou', 'sextou', 'pt-BR', FALSE, FALSE),
    ('segundou', 'segundou', 'segundou', 'pt-BR', FALSE, FALSE),
    ('bora', 'bora', 'bora', 'pt-BR', FALSE, FALSE),
    ('partiu', 'partiu', 'partiu', 'pt-BR', FALSE, FALSE),
    ('colar', 'colar', 'colar', 'pt-BR', FALSE, FALSE),
    ('brotar', 'brotar', 'brotar', 'pt-BR', FALSE, FALSE),
    ('vazar', 'vazar', 'vazar', 'pt-BR', FALSE, FALSE),
    ('dar rolê', 'dar role', 'dar role', 'pt-BR', FALSE, FALSE),
    ('pagar mico', 'pagar mico', 'pagar mico', 'pt-BR', FALSE, FALSE),
    ('dar ruim', 'dar ruim', 'dar ruim', 'pt-BR', FALSE, FALSE),
    ('dar certo', 'dar certo', 'dar certo', 'pt-BR', FALSE, FALSE),
    ('de boa', 'de boa', 'de boa', 'pt-BR', FALSE, FALSE),
    ('suave', 'suave', 'suave', 'pt-BR', FALSE, FALSE),
    ('tranquilo', 'tranquilo', 'tranquilo', 'pt-BR', FALSE, FALSE),
    ('treta', 'treta', 'treta', 'pt-BR', FALSE, FALSE),
    ('climão', 'climao', 'climao', 'pt-BR', FALSE, FALSE),
    ('zoeira', 'zoeira', 'zoeira', 'pt-BR', FALSE, FALSE),
    ('ranço', 'ranco', 'ranco', 'pt-BR', FALSE, FALSE),
    ('recalque', 'recalque', 'recalque', 'pt-BR', FALSE, FALSE),
    ('mitou', 'mitou', 'mitou', 'pt-BR', FALSE, FALSE),
    ('arrasou', 'arrasou', 'arrasou', 'pt-BR', FALSE, FALSE),
    ('lacrar', 'lacrar', 'lacrar', 'pt-BR', FALSE, FALSE),
    ('sensacional', 'sensacional', 'sensacional', 'pt-BR', FALSE, FALSE),
    ('top', 'top', 'top', 'pt-BR', FALSE, FALSE),
    ('chave', 'chave', 'chave', 'pt-BR', FALSE, FALSE),
    ('brabo', 'brabo', 'brabo', 'pt-BR', FALSE, FALSE),
    ('monstro', 'monstro', 'monstro', 'pt-BR', FALSE, FALSE),
    ('fera', 'fera', 'fera', 'pt-BR', FALSE, FALSE),
    ('cria', 'cria', 'cria', 'pt-BR', FALSE, FALSE),
    ('parça', 'parca', 'parca', 'pt-BR', FALSE, FALSE),
    ('mano', 'mano', 'mano', 'pt-BR', FALSE, FALSE),
    ('véi', 'vei', 'vei', 'pt-BR', FALSE, FALSE),
    ('bróder', 'broder', 'broder', 'pt-BR', FALSE, FALSE),
    ('migos', 'migos', 'migos', 'pt-BR', FALSE, FALSE),
    ('bff', 'bff', 'bff', 'en', FALSE, FALSE),
    ('trairagem', 'trairagem', 'trairagem', 'pt-BR', FALSE, FALSE),
    ('migué', 'migue', 'migue', 'pt-BR', FALSE, FALSE),
    ('enrolar', 'enrolar', 'enrolar', 'pt-BR', FALSE, FALSE),
    ('furar', 'furar', 'furar', 'pt-BR', FALSE, FALSE),
    ('pistola', 'pistola', 'pistola', 'pt-BR', FALSE, FALSE),
    ('puto', 'puto', 'puto', 'pt-BR', FALSE, FALSE),
    ('surtar', 'surtar', 'surtar', 'pt-BR', FALSE, FALSE),
    ('chorar', 'chorar', 'chorar', 'pt-BR', FALSE, FALSE),
    ('bomba', 'bomba', 'bomba', 'pt-BR', FALSE, FALSE),
    ('cabuloso', 'cabuloso', 'cabuloso', 'pt-BR', FALSE, FALSE),
    ('sinistro', 'sinistro', 'sinistro', 'pt-BR', FALSE, FALSE),
    ('insano', 'insano', 'insano', 'pt-BR', FALSE, FALSE),
    ('absurdo', 'absurdo', 'absurdo', 'pt-BR', FALSE, FALSE),
    ('pesado', 'pesado', 'pesado', 'pt-BR', FALSE, FALSE),
    ('raso', 'raso', 'raso', 'pt-BR', FALSE, FALSE),
    ('forçado', 'forcado', 'forcado', 'pt-BR', FALSE, FALSE),
    ('mó', 'mo', 'mo', 'pt-BR', FALSE, FALSE),
    ('tipo assim', 'tipo assim', 'tipo assim', 'pt-BR', FALSE, FALSE),
    ('sabe', 'sabe', 'sabe', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('vc', 'pt-BR', 'Abreviação de "você".', 'Uma das abreviações mais antigas e mais usadas do português escrito na internet. "Vcs" é o plural.', 'você'),
    ('tb', 'pt-BR', 'Abreviação de "também".', 'Aparece como "tb", "tbm" e "tmb", todas com o mesmo sentido.', 'também'),
    ('pq', 'pt-BR', 'Abreviação de "porque" ou de "por quê".', 'Serve tanto para a pergunta quanto para a resposta. O contexto separa: "pq?" pergunta, "pq sim" responde.', 'porque'),
    ('qnd', 'pt-BR', 'Abreviação de "quando".', 'Segue o padrão de tirar as vogais, comum nas abreviações escritas no celular.', 'quando'),
    ('mt', 'pt-BR', 'Abreviação de "muito".', '"Mto" e "mta" marcam o gênero: muito e muita.', 'muito'),
    ('blz', 'pt-BR', 'Abreviação de "beleza", usada como "tudo bem" ou "combinado".', 'Serve de cumprimento e de confirmação. "Blz?" pergunta como a pessoa está; "blz" sozinho concorda.', 'tudo bem'),
    ('vlw', 'pt-BR', 'Abreviação de "valeu", ou seja, obrigado.', 'Costuma vir junto de "flw" no encerramento da conversa.', 'obrigado'),
    ('flw', 'pt-BR', 'Abreviação de "falou", usada como tchau.', '"Vlw, flw" quer dizer "obrigado, tchau", e é uma das despedidas mais comuns.', 'tchau'),
    ('add', 'pt-BR', 'Pedido ou aviso de que alguém foi adicionado como contato.', 'Do inglês "add", adicionar. "Me add" é um pedido para ser incluído numa lista ou num grupo.', 'adicionar'),
    ('obg', 'pt-BR', 'Abreviação de "obrigado" ou "obrigada".', 'Mais formal que "vlw", que soa mais próximo entre amigos.', 'obrigado'),
    ('dnv', 'pt-BR', 'Abreviação de "de novo".', 'Costuma vir com tom de cansaço: "dnv?" é um jeito de dizer "outra vez isso?".', 'de novo'),
    ('hj', 'pt-BR', 'Abreviação de "hoje".', 'Aparece muito em combinações: "hj n" quer dizer "hoje não".', 'hoje'),
    ('ontem', 'pt-BR', 'Escrito "ont", é a abreviação de ontem.', 'Segue o padrão de cortar o fim da palavra, comum na escrita rápida.', 'ontem'),
    ('amanha', 'pt-BR', 'Escrito "amnh", é a abreviação de amanhã.', 'A falta do til é característica da digitação rápida no celular, não erro de quem escreve.', 'amanhã'),
    ('n', 'pt-BR', 'Um "n" sozinho quer dizer "não".', 'Das abreviações mais curtas do português escrito. "N sei" quer dizer "não sei".', 'não'),
    ('s2', 'pt-BR', 'Representa um coração, feito com a letra S e o número 2.', 'Anterior aos emojis: nasceu quando os teclados não tinham figurinhas. Ainda é muito usado.', 'coração'),
    ('kkk', 'pt-BR', 'Representa risada, como "hahaha".', 'Quanto mais letras, maior a risada. É a forma mais comum de rir por escrito no Brasil, e chama atenção de estrangeiros.', 'risada'),
    ('mds', 'pt-BR', 'Abreviação de "meu Deus", usada em espanto.', 'Aparece com letras repetidas para reforçar o susto, como "mdsss".', 'meu Deus'),
    ('sqn', 'pt-BR', 'Marca de ironia: significa "só que não".', 'Escrito no fim da frase, avisa que o que veio antes era o contrário do que a pessoa pensa de verdade.', 'só que não'),
    ('pdc', 'pt-BR', 'Abreviação de "pode crer", que quer dizer "concordo".', 'Resposta curta de concordância, comum em conversas escritas.', 'pode crer'),
    ('aff', 'pt-BR', 'Som de impaciência ou desagrado, como um suspiro escrito.', 'Não tem tradução exata. Está entre o "que saco" e o "não acredito".', 'que saco'),
    ('eita', 'pt-BR', 'Interjeição de susto ou surpresa.', '"Eita nóis" é a versão comemorativa, usada quando algo dá certo.', 'nossa'),
    ('vish', 'pt-BR', 'Interjeição de espanto ou de "agora complicou".', 'Encurtamento de "vixe", que por sua vez vem de "virgem". Sinaliza que algo deu errado.', 'que problema'),
    ('nossa', 'pt-BR', 'Interjeição de surpresa, boa ou ruim.', 'Vem de "Nossa Senhora", mas hoje é usada sem qualquer sentido religioso.', 'puxa'),
    ('caraca', 'pt-BR', 'Interjeição de espanto forte.', 'Versão suavizada de um palavrão. Circula livremente, inclusive em ambientes formais.', 'caramba'),
    ('putz', 'pt-BR', 'Interjeição de contrariedade, quando algo dá errado.', 'Também versão suavizada de palavrão. Mais leve que "aff" e mais imediata.', 'poxa'),
    ('ue', 'pt-BR', 'Interjeição de estranhamento, quando algo não faz sentido.', '"Uai" é a variante mineira, e virou marca registrada de Minas Gerais.', 'como assim'),
    ('sla', 'pt-BR', 'Abreviação de "sei lá", usada quando a pessoa não sabe ou não quer opinar.', 'Muitas vezes indica desinteresse mais que ignorância: "sla" pode ser um jeito de encerrar o assunto.', 'não sei'),
    ('tlgd', 'pt-BR', 'Abreviação de "tá ligado", que quer dizer "entendeu?".', 'Funciona como marcador de conversa, parecido com o "sabe?" no fim da frase.', 'entendeu'),
    ('tmj', 'pt-BR', 'Abreviação de "tamo junto", jeito de dizer que está do lado da pessoa.', 'Serve como agradecimento e como demonstração de apoio, dependendo do momento.', 'estamos juntos'),
    ('flws', 'pt-BR', 'Variação de "flw", usada como tchau.', 'O "s" final não muda o sentido, só o tom, deixando a despedida mais leve.', 'tchau'),
    ('brincs', 'pt-BR', 'Abreviação de "brincadeira", usada para avisar que o que foi dito era piada.', 'Serve para desfazer mal-entendido em conversa escrita, onde não há tom de voz para indicar a brincadeira.', 'brincadeira'),
    ('zap', 'pt-BR', 'Apelido do aplicativo de mensagens WhatsApp.', '"Manda no zap" quer dizer "envie pelo WhatsApp". "Zap zap" é a versão mais brincalhona.', 'WhatsApp'),
    ('insta', 'pt-BR', 'Apelido do Instagram.', '"Me chama no insta" é um pedido para conversar por mensagem direta naquele aplicativo.', 'Instagram'),
    ('direct', 'en', 'A mensagem privada dentro de uma rede social.', 'De "direct message". "Chamar na direct" é levar a conversa do público para o privado.', 'mensagem privada'),
    ('status', 'pt-BR', 'Publicação que some depois de um dia, no WhatsApp.', 'Equivalente ao "stories" das outras redes. Muita conversa começa com alguém respondendo um status.', 'publicação temporária'),
    ('stories', 'en', 'Publicação de foto ou vídeo que desaparece depois de 24 horas.', 'Formato criado pelo Snapchat e copiado por todas as redes. O caráter temporário deixa as publicações mais soltas.', 'publicação de 24 horas'),
    ('feed', 'pt-BR', 'A sequência de publicações que aparece quando a pessoa abre a rede social.', '"Cuidar do feed" é escolher as fotos pensando em como o perfil fica no conjunto.', 'linha do tempo'),
    ('arroba', 'pt-BR', 'O nome de usuário de alguém numa rede social.', '"Qual seu arroba?" pergunta o nome de perfil, não o e-mail. Vem do símbolo que antecede o nome.', 'nome de usuário'),
    ('marcar', 'pt-BR', 'Citar alguém numa publicação para que a pessoa seja avisada.', '"Marca ela aí" é um pedido para chamar a atenção de alguém para aquele conteúdo.', 'mencionar'),
    ('salvar', 'pt-BR', 'Guardar uma publicação para ver depois.', 'Nas redes atuais, salvar conta mais que curtir para o sistema decidir mostrar aquilo a mais gente.', 'guardar'),
    ('compartilhar', 'pt-BR', 'Publicar de novo algo que outra pessoa fez.', '"Repost" costuma vir com o crédito ao autor original. Sem crédito, vira reclamação comum entre criadores.', 'republicar'),
    ('printar', 'pt-BR', 'Salvar uma imagem do que está na tela.', 'De "print screen". O resultado é o "print", usado como prova de uma conversa.', 'capturar a tela'),
    ('stalkear', 'pt-BR', 'Vasculhar o perfil de alguém nas redes sociais.', 'Do inglês "stalk", espreitar. No uso comum é apenas bisbilhotar publicações antigas, mas o termo original descreve perseguição, que é crime.', 'bisbilhotar'),
    ('crush', 'pt-BR', 'Pessoa por quem se está interessado romanticamente.', 'Palavra inglesa incorporada ao português. Costuma indicar interesse ainda não declarado.', 'paquera'),
    ('mozao', 'pt-BR', 'Apelido carinhoso para namorado ou namorada.', 'Aumentativo de "amor", com o "a" cortado. "Moza" é a forma feminina mais comum.', 'amor'),
    ('ficar', 'pt-BR', 'Ter um envolvimento sem compromisso de namoro.', '"Ficante" é a pessoa com quem se fica. É uma categoria própria no Brasil, entre a amizade e o namoro.', 'envolvimento casual'),
    ('dar o perdido', 'pt-BR', 'Sumir de alguém sem explicação, deixando a pessoa esperando.', 'Equivalente brasileiro de "ghosting", com a mesma carga de desaprovação.', 'sumir sem avisar'),
    ('ghosting', 'en', 'Sumir de alguém sem explicação, parando de responder.', 'De "ghost", fantasma. Descreve o fim de um contato sem qualquer aviso.', 'sumiço sem explicação'),
    ('sextou', 'pt-BR', 'Comemoração pela chegada da sexta-feira.', 'Verbo inventado a partir do dia da semana. Marca o início do fim de semana.', 'chegou a sexta-feira'),
    ('segundou', 'pt-BR', 'Reclamação bem-humorada pela chegada da segunda-feira.', 'Criado por oposição a "sextou", com sentido invertido: aqui o tom é de desânimo.', 'chegou a segunda-feira'),
    ('bora', 'pt-BR', 'Convite ou incentivo para fazer algo, vindo de "vamos embora".', 'Serve de convite ("bora sair?") e de estímulo ("bora, você consegue").', 'vamos'),
    ('partiu', 'pt-BR', 'Jeito de dizer "vamos nessa", com empolgação.', '"Partiu praia" quer dizer "vamos à praia". Marca decisão tomada, não convite.', 'vamos lá'),
    ('colar', 'pt-BR', 'Aparecer num lugar, geralmente a convite.', '"Cola aqui" é um convite informal. Nada a ver com o sentido de grudar.', 'aparecer'),
    ('brotar', 'pt-BR', 'Aparecer de repente num lugar, sem avisar.', '"Brota lá em casa" é convite. "Ele brotou do nada" descreve alguém que apareceu de surpresa.', 'aparecer de repente'),
    ('vazar', 'pt-BR', 'Ir embora de um lugar.', '"Vou vazar" é uma despedida informal. Diferente do outro sentido de vazar, que é informação escapar.', 'ir embora'),
    ('dar role', 'pt-BR', 'Sair para passear sem destino certo.', '"Rolê" também é o evento em si: "o rolê tava bom" quer dizer que o programa foi divertido.', 'passeio'),
    ('pagar mico', 'pt-BR', 'Passar vergonha em público.', '"Mico" sozinho é a situação vergonhosa. Expressão bem anterior à internet.', 'passar vergonha'),
    ('dar ruim', 'pt-BR', 'Algo dar errado, acabar mal.', 'Usado tanto para problemas pequenos quanto para consequências sérias. O tom da conversa indica a gravidade.', 'dar errado'),
    ('dar certo', 'pt-BR', '"Deu bom" é o oposto de "deu ruim": funcionou.', 'Criado por oposição, é mais recente que "deu ruim" e menos usado.', 'deu certo'),
    ('de boa', 'pt-BR', 'Tranquilo, sem problema.', 'Serve de resposta ("tá de boa") e de descrição de estado ("ele tá de boa").', 'tranquilo'),
    ('suave', 'pt-BR', 'Tranquilo, sem problema, parecido com "de boa".', 'Também usado como resposta a um pedido de desculpas: "suave" quer dizer "não tem problema".', 'tranquilo'),
    ('tranquilo', 'pt-BR', 'Sem problema, sem preocupação.', '"Tranks" é a forma abreviada. Como resposta, equivale a "não se preocupe".', 'tranquilo'),
    ('treta', 'pt-BR', 'Briga, confusão ou desentendimento.', 'Pode ser discussão na internet ou conflito real. "Dar treta" é virar briga.', 'confusão'),
    ('climao', 'pt-BR', 'Clima constrangedor depois de algo desagradável.', 'Aumentativo de "clima", sempre no sentido ruim. "Ficou um climão" descreve o silêncio incômodo que se instala.', 'constrangimento'),
    ('zoeira', 'pt-BR', 'Brincadeira, gozação.', 'Nem sempre é agressiva, mas o limite entre zoeira e ofensa é justamente o que costuma gerar treta.', 'brincadeira'),
    ('ranco', 'pt-BR', 'Antipatia persistente por alguém ou algo.', '"Ter ranço de alguém" é não suportar a pessoa, geralmente sem um motivo grave por trás.', 'antipatia'),
    ('recalque', 'pt-BR', 'Inveja disfarçada de crítica.', 'Acusar alguém de recalque é dizer que a crítica vem de inveja, e não de razão. Também é usado para se esquivar de crítica legítima.', 'inveja'),
    ('mitou', 'pt-BR', 'Fez algo excepcional, foi muito bem.', 'De "mito". Elogio forte e muito comum em comentários.', 'foi excelente'),
    ('arrasou', 'pt-BR', 'Foi muito bem, impressionou.', 'Usado principalmente para aparência e apresentações. Nada a ver com destruir.', 'foi muito bem'),
    ('lacrar', 'pt-BR', 'Dar uma resposta certeira que encerra a discussão.', 'Usado como elogio por uns e como crítica por outros, quando se entende que a pessoa fala só para impressionar.', 'arrasar'),
    ('sensacional', 'pt-BR', 'Muito bom, impressionante.', '"Sensa" é a abreviação usada em conversa escrita.', 'excelente'),
    ('top', 'pt-BR', 'Quer dizer que algo é muito bom.', 'Do inglês "top", topo. Uma das gírias de aprovação mais duradouras no Brasil, e das poucas que atravessam todas as idades.', 'ótimo'),
    ('chave', 'pt-BR', 'Muito bom, estiloso.', '"Chavoso" descreve quem se veste bem e chama atenção. Uso mais comum em São Paulo.', 'estiloso'),
    ('brabo', 'pt-BR', 'Muito bom naquilo que faz.', 'Variação de "bravo". Elogio de habilidade, não de humor: "ele é brabo no jogo".', 'muito bom'),
    ('monstro', 'pt-BR', 'Elogio a alguém muito habilidoso ou muito forte.', 'Sem carga negativa nesse uso. "Tá monstro" também é elogio a quem ficou em boa forma física.', 'excepcional'),
    ('fera', 'pt-BR', 'Pessoa muito boa em alguma coisa.', 'Também usado como forma de tratamento: "e aí, fera?" cumprimenta sem citar o nome.', 'especialista'),
    ('cria', 'pt-BR', 'Pessoa nascida e criada num lugar, que representa aquele lugar.', '"Cria da quebrada" é dito com orgulho de origem. Tem peso identitário forte.', 'nascido e criado'),
    ('parca', 'pt-BR', 'Amigo próximo, de confiança.', 'Encurtamento de "parceiro". Serve de tratamento direto: "fala, parça".', 'amigo'),
    ('mano', 'pt-BR', 'Forma informal de chamar alguém, como "cara" ou "amigo".', 'Serve também de interjeição no começo da frase, sem se dirigir a ninguém: "mano, que susto".', 'cara'),
    ('vei', 'pt-BR', 'Forma informal de chamar alguém, sem relação com idade.', 'Vem de "velho", mas não indica que a pessoa seja velha. É tratamento entre amigos.', 'cara'),
    ('broder', 'pt-BR', 'Forma de chamar um amigo ou colega.', 'Aportuguesamento de "brother", irmão. Tratamento usado principalmente entre homens.', 'amigo'),
    ('migos', 'pt-BR', 'Forma carinhosa de dizer amigo ou amiga.', 'Corte de "amiga". "Miga, sua louca" virou bordão de internet.', 'amigo'),
    ('bff', 'en', 'A melhor amiga ou o melhor amigo de alguém.', 'De "best friends forever", melhores amigos para sempre.', 'melhor amigo'),
    ('trairagem', 'pt-BR', 'Traição ou deslealdade com amigos.', 'Formado de "trair" com o sufixo "-agem". Vale para relacionamento e também para amizade.', 'deslealdade'),
    ('migue', 'pt-BR', 'Desculpa inventada para escapar de algo.', '"Dar um migué" é enrolar, apresentar uma justificativa que ninguém acredita.', 'desculpa esfarrapada'),
    ('enrolar', 'pt-BR', 'Adiar ou disfarçar para não fazer o que foi combinado.', '"Tá enrolando" acusa alguém de fugir do compromisso sem dizer que não vai cumprir.', 'protelar'),
    ('furar', 'pt-BR', 'Faltar a um compromisso combinado.', '"Furão" é quem faz isso sempre. Diferente de cancelar avisando: furar é sumir na hora.', 'faltar'),
    ('pistola', 'pt-BR', 'Muito irritado.', '"Ficar pistola" é ficar bravo. Não tem relação com arma no uso corrente.', 'irritado'),
    ('puto', 'pt-BR', 'Quer dizer que a pessoa está muito brava.', 'Nesse uso é apenas raiva, sem o outro sentido ofensivo que a palavra tem em outros contextos. "Puto da vida" reforça.', 'furioso'),
    ('surtar', 'pt-BR', 'Reagir de forma exagerada, perder o controle.', 'Usado com leveza para empolgação ("surtei com essa notícia") e também para crise emocional real. O contexto decide qual dos dois é.', 'perder o controle'),
    ('chorar', 'pt-BR', 'Reclamar de uma derrota em vez de aceitá-la.', 'No contexto de jogos, "para de chorar" quer dizer "aceite que perdeu". Fora dele, mantém o sentido comum.', 'reclamar'),
    ('bomba', 'pt-BR', 'Reprovação escolar.', '"Tomei bomba" é "fui reprovado". Uso escolar antigo, anterior à internet.', 'reprovação'),
    ('bomba', 'pt-BR', 'Também é um problema herdado de outra pessoa.', '"Me passaram a bomba" quer dizer que a pessoa ficou com um problema que não criou.', 'problema herdado'),
    ('cabuloso', 'pt-BR', 'Impressionante, para o bem ou para o mal.', 'Serve para elogiar ("que jogada cabulosa") e para assustar ("que história cabulosa"). O tom da voz decide.', 'impressionante'),
    ('sinistro', 'pt-BR', 'Impressionante ou assustador, dependendo do contexto.', 'Como "cabuloso", perdeu boa parte do sentido negativo original e virou intensificador.', 'impressionante'),
    ('insano', 'pt-BR', 'Impressionante, fora do normal.', 'Muito usado em comentários sobre jogadas e vídeos. Perdeu a conexão com o sentido clínico da palavra.', 'extraordinário'),
    ('absurdo', 'pt-BR', 'Muito bom ou muito ruim, dependendo do contexto.', '"Absurdo de bom" e "que absurdo" são opostos, e só o resto da frase separa os dois.', 'extremo'),
    ('pesado', 'pt-BR', 'Difícil de encarar emocionalmente.', '"Filme pesado" trata de assunto duro. Diferente do sentido físico da palavra.', 'difícil'),
    ('pesado', 'pt-BR', 'Também é elogio a algo muito bom e intenso.', '"Som pesado" é elogio em vários gêneros musicais.', 'intenso'),
    ('raso', 'pt-BR', 'Superficial, sem profundidade.', '"Argumento raso" é crítica comum em discussões na internet.', 'superficial'),
    ('forcado', 'pt-BR', 'Exagerado ou artificial, que não convence.', '"Humor forçado" é piada que não tem graça e se percebe o esforço.', 'artificial'),
    ('mo', 'pt-BR', 'Intensificador que quer dizer "muito" ou "grande".', 'Encurtamento de "maior". "Mó legal" é "muito legal"; "mó fila" é "fila enorme".', 'muito'),
    ('tipo assim', 'pt-BR', 'Expressão usada para introduzir um exemplo ou ganhar tempo na fala.', 'Funciona como marcador de conversa, sem significado próprio. Muito criticado, e muito usado por todas as idades.', 'por exemplo'),
    ('sabe', 'pt-BR', 'Pergunta no fim da frase que busca concordância de quem ouve.', 'Como "tlgd", é marcador de conversa. Não espera resposta de verdade.', 'entende')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('vc', 'pt-BR', 'vcs', 'vcs', 'vcs'),
    ('vc', 'pt-BR', 'voce', 'voce', 'voce'),
    ('tb', 'pt-BR', 'tbm', 'tbm', 'tbm'),
    ('tb', 'pt-BR', 'tmb', 'tmb', 'tmb'),
    ('qnd', 'pt-BR', 'qdo', 'qdo', 'qdo'),
    ('qnd', 'pt-BR', 'qd', 'qd', 'qd'),
    ('mt', 'pt-BR', 'mto', 'mto', 'mto'),
    ('mt', 'pt-BR', 'mta', 'mta', 'mta'),
    ('obg', 'pt-BR', 'obgd', 'obgd', 'obgd'),
    ('ontem', 'pt-BR', 'ont', 'ont', 'ont'),
    ('amanha', 'pt-BR', 'amnh', 'amnh', 'amnh'),
    ('amanha', 'pt-BR', 'amn', 'amn', 'amn'),
    ('kkk', 'pt-BR', 'kkkk', 'kkkk', 'kk'),
    ('kkk', 'pt-BR', 'rsrs', 'rsrs', 'rsrs'),
    ('kkk', 'pt-BR', 'haha', 'haha', 'haha'),
    ('mds', 'pt-BR', 'mdss', 'mdss', 'mdss'),
    ('mds', 'pt-BR', 'meu deus', 'meu deus', 'meu deus'),
    ('aff', 'pt-BR', 'affe', 'affe', 'affe'),
    ('aff', 'pt-BR', 'afff', 'afff', 'aff'),
    ('eita', 'pt-BR', 'eitcha', 'eitcha', 'eitcha'),
    ('eita', 'pt-BR', 'eita nois', 'eita nois', 'eita nois'),
    ('vish', 'pt-BR', 'vixe', 'vixe', 'vixe'),
    ('vish', 'pt-BR', 'vixi', 'vixi', 'vixi'),
    ('nossa', 'pt-BR', 'nossaaa', 'nossaaa', 'nossaa'),
    ('caraca', 'pt-BR', 'caramba', 'caramba', 'caramba'),
    ('caraca', 'pt-BR', 'caracas', 'caracas', 'caracas'),
    ('ue', 'pt-BR', 'uai', 'uai', 'uai'),
    ('sla', 'pt-BR', 'sei la', 'sei la', 'sei la'),
    ('tlgd', 'pt-BR', 'ta ligado', 'ta ligado', 'ta ligado'),
    ('tlgd', 'pt-BR', 'tá ligado', 'ta ligado', 'ta ligado'),
    ('brincs', 'pt-BR', 'brinc', 'brinc', 'brinc'),
    ('brincs', 'pt-BR', 'brincadeira', 'brincadeira', 'brincadeira'),
    ('zap', 'pt-BR', 'zap zap', 'zap zap', 'zap zap'),
    ('zap', 'pt-BR', 'zapzap', 'zapzap', 'zapzap'),
    ('zap', 'pt-BR', 'whats', 'whats', 'whats'),
    ('direct', 'en', 'dm', 'dm', 'dm'),
    ('direct', 'en', 'chamar na direct', 'chamar na direct', 'chamar na direct'),
    ('stories', 'en', 'story', 'story', 'story'),
    ('stories', 'en', 'storie', 'storie', 'storie'),
    ('marcar', 'pt-BR', 'taggear', 'taggear', 'taggear'),
    ('marcar', 'pt-BR', 'tag', 'tag', 'tag'),
    ('compartilhar', 'pt-BR', 'repostar', 'repostar', 'repostar'),
    ('compartilhar', 'pt-BR', 'repost', 'repost', 'repost'),
    ('printar', 'pt-BR', 'print', 'print', 'print'),
    ('printar', 'pt-BR', 'printou', 'printou', 'printou'),
    ('stalkear', 'pt-BR', 'stalk', 'stalk', 'stalk'),
    ('stalkear', 'pt-BR', 'stalker', 'stalker', 'stalker'),
    ('mozao', 'pt-BR', 'moza', 'moza', 'moza'),
    ('mozao', 'pt-BR', 'mozao', 'mozao', 'mozao'),
    ('mozao', 'pt-BR', 'mozi', 'mozi', 'mozi'),
    ('ficar', 'pt-BR', 'ficante', 'ficante', 'ficante'),
    ('ficar', 'pt-BR', 'rolo', 'rolo', 'rolo'),
    ('ghosting', 'en', 'ghostar', 'ghostar', 'ghostar'),
    ('bora', 'pt-BR', 'borá', 'bora', 'bora'),
    ('bora', 'pt-BR', 'vambora', 'vambora', 'vambora'),
    ('colar', 'pt-BR', 'cola aí', 'cola ai', 'cola ai'),
    ('colar', 'pt-BR', 'colar lá', 'colar la', 'colar la'),
    ('brotar', 'pt-BR', 'brotou', 'brotou', 'brotou'),
    ('vazar', 'pt-BR', 'vaza', 'vaza', 'vaza'),
    ('vazar', 'pt-BR', 'vazei', 'vazei', 'vazei'),
    ('dar role', 'pt-BR', 'rolê', 'role', 'role'),
    ('dar role', 'pt-BR', 'role', 'role', 'role'),
    ('dar role', 'pt-BR', 'rolezinho', 'rolezinho', 'rolezinho'),
    ('pagar mico', 'pt-BR', 'mico', 'mico', 'mico'),
    ('dar ruim', 'pt-BR', 'deu ruim', 'deu ruim', 'deu ruim'),
    ('dar certo', 'pt-BR', 'deu bom', 'deu bom', 'deu bom'),
    ('de boa', 'pt-BR', 'de boas', 'de boas', 'de boas'),
    ('de boa', 'pt-BR', 'numa boa', 'numa boa', 'numa boa'),
    ('suave', 'pt-BR', 'suavão', 'suavao', 'suavao'),
    ('tranquilo', 'pt-BR', 'tranks', 'tranks', 'tranks'),
    ('tranquilo', 'pt-BR', 'tranquilão', 'tranquilao', 'tranquilao'),
    ('treta', 'pt-BR', 'treta', 'treta', 'treta'),
    ('treta', 'pt-BR', 'tretar', 'tretar', 'tretar'),
    ('zoeira', 'pt-BR', 'zueira', 'zueira', 'zueira'),
    ('ranco', 'pt-BR', 'ranco', 'ranco', 'ranco'),
    ('recalque', 'pt-BR', 'recalcado', 'recalcado', 'recalcado'),
    ('recalque', 'pt-BR', 'recalcada', 'recalcada', 'recalcada'),
    ('mitou', 'pt-BR', 'mito', 'mito', 'mito'),
    ('mitou', 'pt-BR', 'mitar', 'mitar', 'mitar'),
    ('arrasou', 'pt-BR', 'arrasar', 'arrasar', 'arrasar'),
    ('lacrar', 'pt-BR', 'lacrou', 'lacrou', 'lacrou'),
    ('lacrar', 'pt-BR', 'lacração', 'lacracao', 'lacracao'),
    ('sensacional', 'pt-BR', 'sensa', 'sensa', 'sensa'),
    ('top', 'pt-BR', 'topzera', 'topzera', 'topzera'),
    ('top', 'pt-BR', 'top demais', 'top demais', 'top demais'),
    ('chave', 'pt-BR', 'chavoso', 'chavoso', 'chavoso'),
    ('brabo', 'pt-BR', 'braba', 'braba', 'braba'),
    ('brabo', 'pt-BR', 'brabex', 'brabex', 'brabex'),
    ('monstro', 'pt-BR', 'monstrão', 'monstrao', 'monstrao'),
    ('parca', 'pt-BR', 'parceiro', 'parceiro', 'parceiro'),
    ('parca', 'pt-BR', 'parcerinho', 'parcerinho', 'parcerinho'),
    ('mano', 'pt-BR', 'mana', 'mana', 'mana'),
    ('mano', 'pt-BR', 'manos', 'manos', 'manos'),
    ('vei', 'pt-BR', 'veio', 'veio', 'veio'),
    ('vei', 'pt-BR', 'vei', 'vei', 'vei'),
    ('broder', 'pt-BR', 'broder', 'broder', 'broder'),
    ('broder', 'pt-BR', 'brother', 'brother', 'brother'),
    ('migos', 'pt-BR', 'migo', 'migo', 'migo'),
    ('migos', 'pt-BR', 'miga', 'miga', 'miga'),
    ('migos', 'pt-BR', 'migas', 'migas', 'migas'),
    ('trairagem', 'pt-BR', 'traíra', 'traira', 'traira'),
    ('trairagem', 'pt-BR', 'traira', 'traira', 'traira'),
    ('migue', 'pt-BR', 'migue', 'migue', 'migue'),
    ('migue', 'pt-BR', 'dar um migué', 'dar um migue', 'dar um migue'),
    ('enrolar', 'pt-BR', 'enrolação', 'enrolacao', 'enrolacao'),
    ('furar', 'pt-BR', 'furou', 'furou', 'furou'),
    ('furar', 'pt-BR', 'furão', 'furao', 'furao'),
    ('pistola', 'pt-BR', 'pistolar', 'pistolar', 'pistolar'),
    ('pistola', 'pt-BR', 'ficar pistola', 'ficar pistola', 'ficar pistola'),
    ('puto', 'pt-BR', 'puta da vida', 'puta da vida', 'puta da vida'),
    ('surtar', 'pt-BR', 'surtei', 'surtei', 'surtei'),
    ('surtar', 'pt-BR', 'surtada', 'surtada', 'surtada'),
    ('chorar', 'pt-BR', 'chorão', 'chorao', 'chorao'),
    ('chorar', 'pt-BR', 'para de chorar', 'para de chorar', 'para de chorar'),
    ('bomba', 'pt-BR', 'tomar bomba', 'tomar bomba', 'tomar bomba'),
    ('bomba', 'pt-BR', 'bombou', 'bombou', 'bombou'),
    ('pesado', 'pt-BR', 'pesadão', 'pesadao', 'pesadao'),
    ('forcado', 'pt-BR', 'forçadão', 'forcadao', 'forcadao'),
    ('mo', 'pt-BR', 'mo', 'mo', 'mo'),
    ('tipo assim', 'pt-BR', 'tipo', 'tipo', 'tipo'),
    ('sabe', 'pt-BR', 'saca', 'saca', 'saca'),
    ('sabe', 'pt-BR', 'entende', 'entende', 'entende')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('vc', 'pt-BR', 'abreviacao'),
    ('tb', 'pt-BR', 'abreviacao'),
    ('pq', 'pt-BR', 'abreviacao'),
    ('qnd', 'pt-BR', 'abreviacao'),
    ('mt', 'pt-BR', 'abreviacao'),
    ('blz', 'pt-BR', 'abreviacao'),
    ('vlw', 'pt-BR', 'abreviacao'),
    ('flw', 'pt-BR', 'abreviacao'),
    ('add', 'pt-BR', 'abreviacao'),
    ('add', 'pt-BR', 'redes'),
    ('obg', 'pt-BR', 'abreviacao'),
    ('dnv', 'pt-BR', 'abreviacao'),
    ('hj', 'pt-BR', 'abreviacao'),
    ('hj', 'pt-BR', 'tempo'),
    ('ontem', 'pt-BR', 'tempo'),
    ('amanha', 'pt-BR', 'tempo'),
    ('n', 'pt-BR', 'abreviacao'),
    ('s2', 'pt-BR', 'abreviacao'),
    ('s2', 'pt-BR', 'emocao'),
    ('kkk', 'pt-BR', 'abreviacao'),
    ('kkk', 'pt-BR', 'humor'),
    ('mds', 'pt-BR', 'abreviacao'),
    ('mds', 'pt-BR', 'emocao'),
    ('sqn', 'pt-BR', 'abreviacao'),
    ('sqn', 'pt-BR', 'humor'),
    ('pdc', 'pt-BR', 'abreviacao'),
    ('aff', 'pt-BR', 'emocao'),
    ('eita', 'pt-BR', 'emocao'),
    ('vish', 'pt-BR', 'emocao'),
    ('nossa', 'pt-BR', 'emocao'),
    ('caraca', 'pt-BR', 'emocao'),
    ('putz', 'pt-BR', 'emocao'),
    ('ue', 'pt-BR', 'emocao'),
    ('sla', 'pt-BR', 'abreviacao'),
    ('tlgd', 'pt-BR', 'abreviacao'),
    ('tmj', 'pt-BR', 'abreviacao'),
    ('flws', 'pt-BR', 'abreviacao'),
    ('brincs', 'pt-BR', 'humor'),
    ('zap', 'pt-BR', 'redes'),
    ('insta', 'pt-BR', 'redes'),
    ('direct', 'en', 'redes'),
    ('status', 'pt-BR', 'redes'),
    ('stories', 'en', 'redes'),
    ('feed', 'pt-BR', 'redes'),
    ('arroba', 'pt-BR', 'redes'),
    ('marcar', 'pt-BR', 'redes'),
    ('salvar', 'pt-BR', 'redes'),
    ('compartilhar', 'pt-BR', 'redes'),
    ('printar', 'pt-BR', 'redes'),
    ('stalkear', 'pt-BR', 'redes'),
    ('crush', 'pt-BR', 'relacionamento'),
    ('mozao', 'pt-BR', 'relacionamento'),
    ('ficar', 'pt-BR', 'relacionamento'),
    ('dar o perdido', 'pt-BR', 'relacionamento'),
    ('ghosting', 'en', 'relacionamento'),
    ('sextou', 'pt-BR', 'tempo'),
    ('sextou', 'pt-BR', 'humor'),
    ('segundou', 'pt-BR', 'tempo'),
    ('segundou', 'pt-BR', 'humor'),
    ('bora', 'pt-BR', 'acao'),
    ('partiu', 'pt-BR', 'acao'),
    ('colar', 'pt-BR', 'acao'),
    ('brotar', 'pt-BR', 'acao'),
    ('vazar', 'pt-BR', 'acao'),
    ('dar role', 'pt-BR', 'acao'),
    ('pagar mico', 'pt-BR', 'emocao'),
    ('dar ruim', 'pt-BR', 'emocao'),
    ('dar certo', 'pt-BR', 'emocao'),
    ('de boa', 'pt-BR', 'emocao'),
    ('suave', 'pt-BR', 'emocao'),
    ('tranquilo', 'pt-BR', 'emocao'),
    ('treta', 'pt-BR', 'critica'),
    ('climao', 'pt-BR', 'emocao'),
    ('zoeira', 'pt-BR', 'humor'),
    ('ranco', 'pt-BR', 'critica'),
    ('ranco', 'pt-BR', 'emocao'),
    ('recalque', 'pt-BR', 'critica'),
    ('mitou', 'pt-BR', 'elogio'),
    ('arrasou', 'pt-BR', 'elogio'),
    ('lacrar', 'pt-BR', 'elogio'),
    ('lacrar', 'pt-BR', 'critica'),
    ('sensacional', 'pt-BR', 'elogio'),
    ('top', 'pt-BR', 'elogio'),
    ('chave', 'pt-BR', 'elogio'),
    ('brabo', 'pt-BR', 'elogio'),
    ('monstro', 'pt-BR', 'elogio'),
    ('fera', 'pt-BR', 'elogio'),
    ('cria', 'pt-BR', 'descricao'),
    ('parca', 'pt-BR', 'descricao'),
    ('mano', 'pt-BR', 'descricao'),
    ('vei', 'pt-BR', 'descricao'),
    ('broder', 'pt-BR', 'descricao'),
    ('migos', 'pt-BR', 'descricao'),
    ('bff', 'en', 'descricao'),
    ('bff', 'en', 'abreviacao'),
    ('trairagem', 'pt-BR', 'critica'),
    ('migue', 'pt-BR', 'critica'),
    ('enrolar', 'pt-BR', 'critica'),
    ('furar', 'pt-BR', 'critica'),
    ('pistola', 'pt-BR', 'emocao'),
    ('puto', 'pt-BR', 'emocao'),
    ('surtar', 'pt-BR', 'emocao'),
    ('chorar', 'pt-BR', 'critica'),
    ('bomba', 'pt-BR', 'escolar'),
    ('cabuloso', 'pt-BR', 'emocao'),
    ('sinistro', 'pt-BR', 'emocao'),
    ('insano', 'pt-BR', 'emocao'),
    ('absurdo', 'pt-BR', 'emocao'),
    ('pesado', 'pt-BR', 'emocao'),
    ('raso', 'pt-BR', 'critica'),
    ('forcado', 'pt-BR', 'critica'),
    ('mo', 'pt-BR', 'descricao'),
    ('tipo assim', 'pt-BR', 'descricao'),
    ('sabe', 'pt-BR', 'descricao')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

