-- ---------------------------------------------------------------------------
-- girias de rua e cotidiano brasileiro
--
-- 107 verbetes, 109 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('bagulho', 'bagulho', 'bagulho', 'pt-BR', FALSE, FALSE),
    ('treco', 'treco', 'treco', 'pt-BR', FALSE, FALSE),
    ('parada', 'parada', 'parada', 'pt-BR', FALSE, FALSE),
    ('quebrada', 'quebrada', 'quebrada', 'pt-BR', FALSE, FALSE),
    ('corre', 'corre', 'corre', 'pt-BR', FALSE, FALSE),
    ('trampo', 'trampo', 'trampo', 'pt-BR', FALSE, FALSE),
    ('bico', 'bico', 'bico', 'pt-BR', FALSE, FALSE),
    ('grana', 'grana', 'grana', 'pt-BR', FALSE, FALSE),
    ('din din', 'din din', 'din din', 'pt-BR', FALSE, FALSE),
    ('pila', 'pila', 'pila', 'pt-BR', FALSE, FALSE),
    ('conto', 'conto', 'conto', 'pt-BR', FALSE, FALSE),
    ('duro', 'duro', 'duro', 'pt-BR', FALSE, FALSE),
    ('quebrar o galho', 'quebrar o galho', 'quebrar o galho', 'pt-BR', FALSE, FALSE),
    ('dar um jeito', 'dar um jeito', 'dar um jeito', 'pt-BR', FALSE, FALSE),
    ('gambiarra', 'gambiarra', 'gambiarra', 'pt-BR', FALSE, FALSE),
    ('puxar o saco', 'puxar o saco', 'puxar o saco', 'pt-BR', FALSE, FALSE),
    ('dar mole', 'dar mole', 'dar mole', 'pt-BR', FALSE, FALSE),
    ('vacilar', 'vacilar', 'vacilar', 'pt-BR', FALSE, FALSE),
    ('pisar na bola', 'pisar na bola', 'pisar na bola', 'pt-BR', FALSE, FALSE),
    ('pagar de', 'pagar de', 'pagar de', 'pt-BR', FALSE, FALSE),
    ('se achar', 'se achar', 'se achar', 'pt-BR', FALSE, FALSE),
    ('metido', 'metido', 'metido', 'pt-BR', FALSE, FALSE),
    ('folgado', 'folgado', 'folgado', 'pt-BR', FALSE, FALSE),
    ('cara de pau', 'cara de pau', 'cara de pau', 'pt-BR', FALSE, FALSE),
    ('sem noção', 'sem nocao', 'sem nocao', 'pt-BR', FALSE, FALSE),
    ('mala', 'mala', 'mala', 'pt-BR', FALSE, FALSE),
    ('chato', 'chato', 'chato', 'pt-BR', FALSE, FALSE),
    ('esquentar a cabeça', 'esquentar a cabeca', 'esquentar a cabeca', 'pt-BR', FALSE, FALSE),
    ('encanar', 'encanar', 'encanar', 'pt-BR', FALSE, FALSE),
    ('viajar', 'viajar', 'viajar', 'pt-BR', FALSE, FALSE),
    ('brisar', 'brisar', 'brisar', 'pt-BR', FALSE, FALSE),
    ('zoar a cabeça', 'zoar a cabeca', 'zoar a cabeca', 'pt-BR', FALSE, FALSE),
    ('dar um tempo', 'dar um tempo', 'dar um tempo', 'pt-BR', FALSE, FALSE),
    ('dar um perdido', 'dar um perdido', 'dar um perdido', 'pt-BR', FALSE, FALSE),
    ('chutar o balde', 'chutar o balde', 'chutar o balde', 'pt-BR', FALSE, FALSE),
    ('pisar no freio', 'pisar no freio', 'pisar no freio', 'pt-BR', FALSE, FALSE),
    ('botar pra quebrar', 'botar pra quebrar', 'botar pra quebrar', 'pt-BR', FALSE, FALSE),
    ('meter o pé', 'meter o pe', 'meter o pe', 'pt-BR', FALSE, FALSE),
    ('dar o fora', 'dar o fora', 'dar o fora', 'pt-BR', FALSE, FALSE),
    ('ficar na seca', 'ficar na seca', 'ficar na seca', 'pt-BR', FALSE, FALSE),
    ('dar bola', 'dar bola', 'dar bola', 'pt-BR', FALSE, FALSE),
    ('azarar', 'azarar', 'azarar', 'pt-BR', FALSE, FALSE),
    ('cantada', 'cantada', 'cantada', 'pt-BR', FALSE, FALSE),
    ('papo reto', 'papo reto', 'papo reto', 'pt-BR', FALSE, FALSE),
    ('papo furado', 'papo furado', 'papo furado', 'pt-BR', FALSE, FALSE),
    ('encher linguiça', 'encher linguica', 'encher linguica', 'pt-BR', FALSE, FALSE),
    ('viajar na maionese', 'viajar na maionese', 'viajar na maionese', 'pt-BR', FALSE, FALSE),
    ('pagar o pato', 'pagar o pato', 'pagar o pato', 'pt-BR', FALSE, FALSE),
    ('abacaxi', 'abacaxi', 'abacaxi', 'pt-BR', FALSE, FALSE),
    ('pepino', 'pepino', 'pepino', 'pt-BR', FALSE, FALSE),
    ('saia justa', 'saia justa', 'saia justa', 'pt-BR', FALSE, FALSE),
    ('mão na roda', 'mao na roda', 'mao na roda', 'pt-BR', FALSE, FALSE),
    ('pé no chão', 'pe no chao', 'pe no chao', 'pt-BR', FALSE, FALSE),
    ('gente boa', 'gente boa', 'gente boa', 'pt-BR', FALSE, FALSE),
    ('bacana', 'bacana', 'bacana', 'pt-BR', FALSE, FALSE),
    ('massa', 'massa', 'massa', 'pt-BR', FALSE, FALSE),
    ('irado', 'irado', 'irado', 'pt-BR', FALSE, FALSE),
    ('da hora', 'da hora', 'da hora', 'pt-BR', FALSE, FALSE),
    ('show de bola', 'show de bola', 'show de bola', 'pt-BR', FALSE, FALSE),
    ('joia', 'joia', 'joia', 'pt-BR', FALSE, FALSE),
    ('beleza', 'beleza', 'beleza', 'pt-BR', FALSE, FALSE),
    ('firmeza', 'firmeza', 'firmeza', 'pt-BR', FALSE, FALSE),
    ('sussa', 'sussa', 'sussa', 'pt-BR', FALSE, FALSE),
    ('tá tranquilo', 'ta tranquilo', 'ta tranquilo', 'pt-BR', FALSE, FALSE),
    ('na moral', 'na moral', 'na moral', 'pt-BR', FALSE, FALSE),
    ('pela moral', 'pela moral', 'pela moral', 'pt-BR', FALSE, FALSE),
    ('de rolê', 'de role', 'de role', 'pt-BR', FALSE, FALSE),
    ('role', 'role', 'role', 'pt-BR', FALSE, FALSE),
    ('resenha', 'resenha', 'resenha', 'pt-BR', FALSE, FALSE),
    ('treta boa', 'treta boa', 'treta boa', 'pt-BR', FALSE, FALSE),
    ('esquema', 'esquema', 'esquema', 'pt-BR', FALSE, FALSE),
    ('fechou', 'fechou', 'fechou', 'pt-BR', FALSE, FALSE),
    ('colar na fita', 'colar na fita', 'colar na fita', 'pt-BR', FALSE, FALSE),
    ('dar linha', 'dar linha', 'dar linha', 'pt-BR', FALSE, FALSE),
    ('pagar de gato', 'pagar de gato', 'pagar de gato', 'pt-BR', FALSE, FALSE),
    ('gato', 'gato', 'gato', 'pt-BR', FALSE, FALSE),
    ('coroa', 'coroa', 'coroa', 'pt-BR', FALSE, FALSE),
    ('moleque', 'moleque', 'moleque', 'pt-BR', FALSE, FALSE),
    ('guri', 'guri', 'guri', 'pt-BR', FALSE, FALSE),
    ('piá', 'pia', 'pia', 'pt-BR', FALSE, FALSE),
    ('cabra', 'cabra', 'cabra', 'pt-BR', FALSE, FALSE),
    ('véia', 'veia', 'veia', 'pt-BR', FALSE, FALSE),
    ('chapa', 'chapa', 'chapa', 'pt-BR', FALSE, FALSE),
    ('xará', 'xara', 'xara', 'pt-BR', FALSE, FALSE),
    ('mermão', 'mermao', 'mermao', 'pt-BR', FALSE, FALSE),
    ('maluco', 'maluco', 'maluco', 'pt-BR', FALSE, FALSE),
    ('tiozão', 'tiozao', 'tiozao', 'pt-BR', FALSE, FALSE),
    ('boomer', 'boomer', 'boomer', 'en', FALSE, FALSE),
    ('millennial', 'millennial', 'millennial', 'en', FALSE, FALSE),
    ('geração z', 'geracao z', 'geracao z', 'pt-BR', FALSE, FALSE),
    ('alpha', 'alpha', 'alpha', 'en', FALSE, FALSE),
    ('mó paia', 'mo paia', 'mo paia', 'pt-BR', FALSE, FALSE),
    ('zica', 'zica', 'zica', 'pt-BR', FALSE, FALSE),
    ('pé frio', 'pe frio', 'pe frio', 'pt-BR', FALSE, FALSE),
    ('encosto', 'encosto', 'encosto', 'pt-BR', FALSE, FALSE),
    ('sangue no olho', 'sangue no olho', 'sangue no olho', 'pt-BR', FALSE, FALSE),
    ('raça', 'raca', 'raca', 'pt-BR', FALSE, FALSE),
    ('garra', 'garra', 'garra', 'pt-BR', FALSE, FALSE),
    ('cara de tacho', 'cara de tacho', 'cara de tacho', 'pt-BR', FALSE, FALSE),
    ('boiar', 'boiar', 'boiar', 'pt-BR', FALSE, FALSE),
    ('cair a ficha', 'cair a ficha', 'cair a ficha', 'pt-BR', FALSE, FALSE),
    ('sacar', 'sacar', 'sacar', 'pt-BR', FALSE, FALSE),
    ('manjar', 'manjar', 'manjar', 'pt-BR', FALSE, FALSE),
    ('caô', 'cao', 'cao', 'pt-BR', FALSE, FALSE),
    ('lorota', 'lorota', 'lorota', 'pt-BR', FALSE, FALSE),
    ('papo de doido', 'papo de doido', 'papo de doido', 'pt-BR', FALSE, FALSE),
    ('sinal amarelo', 'sinal amarelo', 'sinal amarelo', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('bagulho', 'pt-BR', 'Coisa, objeto qualquer, quando a pessoa não lembra ou não quer dizer o nome.', 'Palavra genérica, como "treco" e "negócio". "Passa aquele bagulho ali" pode se referir a qualquer coisa.', 'coisa'),
    ('bagulho', 'pt-BR', 'Também descreve uma situação inteira.', '"O bagulho ficou doido" quer dizer que a situação ficou complicada ou fora de controle.', 'situação'),
    ('treco', 'pt-BR', 'Coisa, objeto sem nome definido.', '"Trem" é a versão mineira e não tem relação com o transporte: em Minas, "trem" é qualquer coisa.', 'objeto'),
    ('parada', 'pt-BR', 'Assunto, situação ou coisa, de forma genérica.', '"Que parada é essa?" pergunta o que está acontecendo. Muito usado no Rio de Janeiro.', 'assunto'),
    ('quebrada', 'pt-BR', 'O bairro de periferia onde a pessoa mora.', 'Dito com orgulho de origem por quem é de lá. "Cria da quebrada" reforça esse pertencimento.', 'bairro'),
    ('corre', 'pt-BR', 'O trabalho ou a atividade que a pessoa faz para ganhar dinheiro.', '"Tô no corre" quer dizer que a pessoa está trabalhando ou resolvendo coisas. Costuma indicar trabalho informal ou por conta própria.', 'trabalho'),
    ('trampo', 'pt-BR', 'Trabalho, emprego.', '"Trampar" é o verbo. Termo antigo, ainda muito comum em todo o Brasil.', 'trabalho'),
    ('bico', 'pt-BR', 'Trabalho extra, feito de vez em quando para complementar a renda.', '"Fazer um bico" é pegar um serviço avulso, fora do emprego principal.', 'trabalho avulso'),
    ('grana', 'pt-BR', 'Quer dizer dinheiro.', 'Das gírias mais duradouras do português brasileiro, viva desde os anos 70. "Sem grana" é sem dinheiro.', 'dinheiro'),
    ('din din', 'pt-BR', 'Jeito brincalhão de dizer dinheiro.', 'Costuma aparecer em tom leve, quando o assunto é receber ou gastar pouco.', 'dinheiro'),
    ('pila', 'pt-BR', 'Dinheiro, no sul do Brasil.', 'Muito usado no Rio Grande do Sul. "Vinte pila" quer dizer vinte reais.', 'dinheiro'),
    ('conto', 'pt-BR', 'Unidade informal de dinheiro, geralmente reais.', '"Cinquenta conto" é cinquenta reais. Herança do tempo em que a moeda era o cruzeiro.', 'reais'),
    ('duro', 'pt-BR', 'Sem dinheiro nenhum.', '"Tô duro" e "tô liso" querem dizer a mesma coisa. Nada a ver com dureza física.', 'sem dinheiro'),
    ('quebrar o galho', 'pt-BR', 'Resolver um problema de forma improvisada, ajudando alguém.', '"Quebra-galho" também é a solução temporária em si, que resolve mas não é a ideal.', 'improvisar uma solução'),
    ('dar um jeito', 'pt-BR', 'Resolver algo por caminhos que não são os oficiais.', 'O "jeitinho brasileiro" é discutido como característica cultural, elogiado como criatividade e criticado como desrespeito a regras.', 'improvisar'),
    ('gambiarra', 'pt-BR', 'Solução improvisada, feita com o que tinha à mão.', 'Funciona, mas não é a forma certa. Na área técnica virou termo comum para código ou conserto malfeito que resolve por enquanto.', 'improviso'),
    ('puxar o saco', 'pt-BR', 'Bajular alguém para conseguir vantagem.', '"Puxa-saco" é a pessoa que faz isso. Crítica comum em ambiente de trabalho e escola.', 'bajular'),
    ('dar mole', 'pt-BR', 'Descuidar e deixar que algo dê errado.', '"Deu mole" é o mesmo que "vacilou". Também pode significar demonstrar interesse por alguém.', 'descuidar'),
    ('vacilar', 'pt-BR', 'Errar de um jeito que decepciona os outros.', '"Vacilão" é quem faz isso com frequência, e é ofensa forte. "Vacilo" é o erro em si.', 'falhar'),
    ('pisar na bola', 'pt-BR', 'Decepcionar alguém deixando de cumprir o combinado.', 'Metáfora do futebol. Mais leve que "vacilar": indica falha, não caráter.', 'decepcionar'),
    ('pagar de', 'pt-BR', 'Fingir ser algo que não é.', '"Pagando de rico" é aparentar riqueza que não tem. Sempre com carga de crítica.', 'aparentar'),
    ('se achar', 'pt-BR', 'Ter opinião exagerada sobre si mesmo.', '"Ele se acha" quer dizer que a pessoa se considera melhor do que é. Crítica comum a quem parece arrogante.', 'ser arrogante'),
    ('metido', 'pt-BR', 'Quem se comporta como superior aos outros.', 'Parecido com "se achar", mas descreve o comportamento, não a opinião interna.', 'presunçoso'),
    ('folgado', 'pt-BR', 'Quem abusa da boa vontade dos outros.', 'Diferente de preguiçoso: o folgado se aproveita de quem está por perto.', 'abusado'),
    ('cara de pau', 'pt-BR', 'Pessoa sem vergonha, que faz coisas descaradas sem se constranger.', 'Imagem de um rosto que não muda de expressão, sem revelar constrangimento.', 'descarado'),
    ('sem nocao', 'pt-BR', 'Quem não percebe o quanto está passando dos limites.', 'Diferente de mal-intencionado: o "sem noção" costuma não perceber o efeito do que faz.', 'inconveniente'),
    ('mala', 'pt-BR', 'Pessoa chata, difícil de aguentar.', '"Mala sem alça" reforça: é um peso que ninguém consegue carregar com jeito.', 'inconveniente'),
    ('chato', 'pt-BR', 'Pessoa ou situação desagradável e cansativa.', 'Palavra de uso amplíssimo no Brasil, aplicada a pessoas, tarefas e assuntos.', 'desagradável'),
    ('esquentar a cabeca', 'pt-BR', 'Preocupar-se demais com algo.', '"Não esquenta" é um pedido para a pessoa relaxar e não se preocupar.', 'preocupar-se'),
    ('encanar', 'pt-BR', 'Ficar preso a uma preocupação, remoendo o assunto.', '"Encanei com aquilo" descreve pensamento que não sai da cabeça. Diferente de se preocupar de passagem.', 'obcecar-se'),
    ('viajar', 'pt-BR', 'Perder o fio da conversa ou pensar em coisas sem sentido.', '"Viajei" quer dizer que a pessoa se distraiu. "Que viagem" comenta uma ideia estranha.', 'distrair-se'),
    ('brisar', 'pt-BR', 'Ficar pensativo ou distraído, num estado meio solto.', '"Que brisa" comenta um pensamento curioso. "Brisado" é quem está distraído.', 'distraído'),
    ('zoar a cabeca', 'pt-BR', 'Deixar alguém confuso ou abalado emocionalmente.', '"Isso zoou minha cabeça" descreve algo que afetou a pessoa mais do que ela esperava.', 'abalar'),
    ('dar um tempo', 'pt-BR', 'Interromper um relacionamento por um período, sem terminar de vez.', 'Situação de definição vaga, o que costuma gerar mal-entendido sobre o que vale ou não durante esse tempo.', 'pausa no relacionamento'),
    ('dar um perdido', 'pt-BR', 'Sumir de alguém sem explicação.', 'Versão brasileira do que em inglês se chama "ghosting".', 'sumir'),
    ('chutar o balde', 'pt-BR', 'Desistir de vez e parar de tentar controlar a situação.', 'Costuma vir depois de muita paciência acumulada. Não é decisão calma, é rompimento.', 'desistir'),
    ('pisar no freio', 'pt-BR', 'Diminuir o ritmo ou recuar de uma decisão.', 'Metáfora de direção. Usado para conselho: "pisa no freio" pede cautela.', 'desacelerar'),
    ('botar pra quebrar', 'pt-BR', 'Fazer algo com toda a força, dando o melhor.', 'Sem sentido destrutivo: é elogio ao empenho.', 'empenhar-se ao máximo'),
    ('meter o pe', 'pt-BR', 'Ir embora, geralmente rápido.', 'Pode indicar fuga de uma situação chata ou simplesmente partida apressada.', 'ir embora'),
    ('dar o fora', 'pt-BR', 'Terminar um relacionamento.', '"Levou um fora" é quem foi rejeitado, seja num término ou numa investida que não deu certo.', 'terminar'),
    ('ficar na seca', 'pt-BR', 'Estar há muito tempo sem envolvimento amoroso.', 'Sempre com tom de brincadeira, geralmente sobre si mesmo.', 'sem relacionamentos'),
    ('dar bola', 'pt-BR', 'Demonstrar interesse por alguém.', '"Não deu bola" também significa ignorar, não necessariamente em contexto amoroso.', 'demonstrar interesse'),
    ('azarar', 'pt-BR', 'Tentar conquistar alguém.', 'Termo mais antigo, hoje usado com ar nostálgico ou por gerações mais velhas.', 'cortejar'),
    ('cantada', 'pt-BR', 'Frase dita para conquistar alguém.', 'Quando não é bem recebida, deixa de ser cantada e passa a ser importunação, que no Brasil é crime desde 2018.', 'investida'),
    ('papo reto', 'pt-BR', 'Conversa franca, direta, sem rodeios.', '"Papo reto" também serve como afirmação de sinceridade: "papo reto, não foi isso que aconteceu".', 'conversa franca'),
    ('papo furado', 'pt-BR', 'Conversa sem conteúdo, ou promessa que não vai se cumprir.', '"Conversa fiada" é o sinônimo mais antigo, com o mesmo sentido.', 'conversa vazia'),
    ('encher linguica', 'pt-BR', 'Falar ou escrever muito sem dizer nada de útil.', 'Muito usado em contexto escolar, sobre redações que ocupam espaço sem conteúdo.', 'prolongar sem conteúdo'),
    ('viajar na maionese', 'pt-BR', 'Falar coisas sem sentido ou entender tudo errado.', 'Expressão sem origem clara, mas de uso consolidado. Sempre com tom de brincadeira.', 'falar sem sentido'),
    ('pagar o pato', 'pt-BR', 'Ser responsabilizado por algo que outra pessoa fez.', 'Expressão antiga, vinda de uma brincadeira popular portuguesa. Nada a ver com a ave.', 'levar a culpa'),
    ('abacaxi', 'pt-BR', 'Problema difícil que sobrou para alguém resolver.', '"Descascar o abacaxi" é resolver o problema complicado, geralmente criado por outro.', 'problema difícil'),
    ('pepino', 'pt-BR', 'Problema chato de resolver.', 'Muito usado em ambiente de trabalho, quase sempre para problema herdado.', 'problema'),
    ('saia justa', 'pt-BR', 'Situação constrangedora da qual é difícil escapar.', 'A imagem é de uma roupa apertada que limita os movimentos.', 'situação constrangedora'),
    ('mao na roda', 'pt-BR', 'Algo que ajuda muito e facilita a vida.', '"Esse aplicativo é uma mão na roda" é elogio à utilidade, não à beleza.', 'muito útil'),
    ('pe no chao', 'pt-BR', 'Pessoa realista, que não se ilude.', 'Elogio ao equilíbrio, em oposição a quem "viaja" ou promete demais.', 'realista'),
    ('gente boa', 'pt-BR', 'Pessoa agradável e de boa índole.', '"Gente fina" é sinônimo. Elogio simples, sobre convivência, não sobre competência.', 'pessoa agradável'),
    ('bacana', 'pt-BR', 'Legal, agradável.', 'Termo mais antigo, usado por várias gerações. Serve para pessoas e coisas.', 'agradável'),
    ('massa', 'pt-BR', 'Muito bom, legal.', 'Muito usado no Nordeste, principalmente em Pernambuco, e hoje espalhado pelo país.', 'ótimo'),
    ('irado', 'pt-BR', 'Muito bom, impressionante.', 'Apesar de vir de "ira", não indica raiva nenhuma nesse uso.', 'excelente'),
    ('da hora', 'pt-BR', 'Quer dizer que algo é muito legal.', 'Muito associado a São Paulo. Termo dos anos 90 que continua em uso, hoje com ar levemente nostálgico.', 'legal'),
    ('show de bola', 'pt-BR', 'Excelente, muito bem feito.', 'Vem do futebol. "Show" sozinho já serve como aprovação.', 'excelente'),
    ('joia', 'pt-BR', 'Ótimo, tudo bem.', 'Serve como resposta a "como vai?". Termo antigo, ainda comum entre pessoas mais velhas.', 'muito bem'),
    ('beleza', 'pt-BR', 'Tudo bem, combinado.', 'Serve de cumprimento ("beleza?") e de confirmação ("beleza, então").', 'tudo bem'),
    ('firmeza', 'pt-BR', 'Confirmação de que está tudo certo.', 'Também serve de cumprimento, como "beleza". Comum no Rio de Janeiro.', 'tudo certo'),
    ('sussa', 'pt-BR', 'Tranquilo, sem problema.', 'Encurtamento de "sussurro" ou de "suave", conforme a região. Uso jovem.', 'tranquilo'),
    ('ta tranquilo', 'pt-BR', 'Está tudo bem, sem preocupação.', '"Tá tranquilo, tá favorável" virou bordão nacional a partir de um vídeo de 2017.', 'está tudo bem'),
    ('na moral', 'pt-BR', 'Falando sério, sem brincadeira.', 'Também usado como pedido: "na moral, para com isso".', 'falando sério'),
    ('pela moral', 'pt-BR', 'Fazer algo de graça, por consideração à pessoa.', '"Faz pela moral" pede um favor sem cobrança, apelando à relação.', 'por consideração'),
    ('de role', 'pt-BR', 'Passeando, sem compromisso.', '"Tô de rolê" quer dizer que a pessoa está na rua, sem destino fixo.', 'passeando'),
    ('role', 'pt-BR', 'Passeio ou programa com amigos.', '"O rolê tava bom" avalia o programa. "Rolezinho" ganhou sentido político em 2013, quando grupos de jovens de periferia começaram a se encontrar em shoppings.', 'passeio'),
    ('resenha', 'pt-BR', 'Conversa animada e descontraída entre amigos.', 'Diferente do sentido de crítica literária. "Fazer uma resenha" é passar o tempo conversando e rindo.', 'conversa descontraída'),
    ('treta boa', 'pt-BR', 'Confusão divertida, sem consequência séria.', 'Uso irônico de "treta", que normalmente é briga. Aqui indica agito bem-humorado.', 'agito'),
    ('esquema', 'pt-BR', 'Arranjo ou plano combinado para resolver algo.', '"Fechou o esquema" quer dizer que ficou combinado. Nem sempre indica coisa ilícita.', 'arranjo'),
    ('fechou', 'pt-BR', 'Combinado, está acertado.', 'Resposta de confirmação, equivalente a "beleza". "Fechou" encerra a negociação.', 'combinado'),
    ('colar na fita', 'pt-BR', 'Entrar num assunto ou numa situação.', '"Fita" sozinho é o assunto ou a situação: "que fita é essa?".', 'entrar no assunto'),
    ('dar linha', 'pt-BR', 'Dar atenção ou dar corda a alguém.', '"Não dá linha pra ele" é um conselho para ignorar a pessoa.', 'dar atenção'),
    ('pagar de gato', 'pt-BR', 'Achar-se bonito e demonstrar isso.', '"Gato" e "gata" são elogios à aparência; "pagar de gato" é a crítica a quem se acha demais.', 'achar-se bonito'),
    ('gato', 'pt-BR', 'Jeito de dizer que a pessoa é bonita.', 'Elogio comum e antigo, sem carga ofensiva. "Gata" é a forma feminina, igualmente usada.', 'pessoa bonita'),
    ('gato', 'pt-BR', 'Também é uma ligação irregular de luz ou de TV.', '"Fazer um gato" nesse sentido é puxar ligação clandestina, o que é crime.', 'ligação clandestina'),
    ('coroa', 'pt-BR', 'Pessoa mais velha.', 'Não é ofensivo por si só, mas depende muito do tom. Também usado com carinho para os pais.', 'pessoa mais velha'),
    ('moleque', 'pt-BR', 'Menino ou rapaz jovem.', 'Pode ser afetuoso ("meu moleque") ou crítico ("que moleque"). O contexto decide.', 'garoto'),
    ('guri', 'pt-BR', 'Menino ou menina, no sul do Brasil.', 'Muito usado no Rio Grande do Sul. "Guria" é a forma feminina.', 'criança'),
    ('pia', 'pt-BR', 'Menino, no Paraná e em Santa Catarina.', 'Palavra de origem indígena, do tupi. Muito característica da região sul.', 'menino'),
    ('cabra', 'pt-BR', 'Homem, sujeito, no Nordeste.', '"Cabra bom" é elogio; "cabra da peste" descreve alguém corajoso e resistente.', 'sujeito'),
    ('veia', 'pt-BR', 'Forma carinhosa de se referir à mãe ou a uma amiga.', 'Apesar de vir de "velha", não indica idade nesse uso, e sim proximidade.', 'querida'),
    ('chapa', 'pt-BR', 'Amigo, companheiro.', 'Tratamento informal entre homens, mais comum em Minas Gerais e no interior.', 'amigo'),
    ('xara', 'pt-BR', 'Pessoa que tem o mesmo nome que você.', 'Palavra de origem tupi. Serve de tratamento carinhoso entre quem compartilha o nome.', 'homônimo'),
    ('mermao', 'pt-BR', 'Forma de chamar alguém, vinda de "meu irmão".', 'Muito característica do Rio de Janeiro, ao lado de "maluco" e "caraca".', 'amigo'),
    ('maluco', 'pt-BR', 'Forma de chamar alguém, sem indicar loucura.', 'Muito usada no Rio de Janeiro como tratamento neutro: "e aí, maluco".', 'cara'),
    ('tiozao', 'pt-BR', 'Pessoa mais velha que age de um jeito considerado ultrapassado.', '"Piada de tiozão" é humor datado. "Tia do zap" descreve quem repassa correntes sem verificar.', 'pessoa fora de época'),
    ('boomer', 'en', 'Pessoa de geração mais velha, usado como crítica a ideias antiquadas.', 'De "baby boomer", geração nascida após a Segunda Guerra. "Ok boomer" virou resposta irônica em 2019.', 'pessoa de geração antiga'),
    ('millennial', 'en', 'Pessoa nascida entre o início dos anos 80 e meados dos 90.', 'Também virou alvo de piada na internet, principalmente por gerações mais novas.', 'geração Y'),
    ('geracao z', 'pt-BR', 'Pessoas nascidas aproximadamente entre 1997 e 2010.', 'É a geração que cresceu com celular e redes sociais desde a infância, e de onde vem boa parte das gírias atuais.', 'geração Z'),
    ('alpha', 'en', 'As crianças nascidas a partir de 2010.', 'É a geração associada a termos como "skibidi" e "gyat", que confundem até quem é jovem.', 'geração Alpha'),
    ('mo paia', 'pt-BR', 'Ruim, decepcionante.', '"Paia" vem de "palha", algo sem valor. "Que paia" comenta uma situação chata.', 'ruim'),
    ('zica', 'pt-BR', 'Azar, má sorte.', '"Tá zicado" é estar com azar persistente. Palavra bem anterior ao vírus de mesmo nome.', 'azar'),
    ('pe frio', 'pt-BR', 'Pessoa que parece atrair azar para o time ou para o grupo.', 'Muito usado em futebol, sempre com tom de brincadeira.', 'azarado'),
    ('encosto', 'pt-BR', 'Pessoa que vive às custas dos outros.', 'Também usado em sentido espiritual em contextos religiosos, mas no uso comum é apenas crítica.', 'parasita'),
    ('sangue no olho', 'pt-BR', 'Determinação forte para conseguir algo.', 'Elogio à garra. Muito usado em esporte e em contexto de trabalho.', 'determinação'),
    ('raca', 'pt-BR', 'Esforço e garra ao fazer algo.', '"Jogou com raça" elogia o empenho, mesmo quando o resultado não veio.', 'garra'),
    ('garra', 'pt-BR', 'Vontade forte de não desistir.', 'Sinônimo de "raça" nesse uso, e igualmente comum em esporte.', 'determinação'),
    ('cara de tacho', 'pt-BR', 'Ficar sem graça depois de um constrangimento.', 'A imagem é do fundo de uma panela: rosto vazio, sem saber o que dizer.', 'ficar sem graça'),
    ('boiar', 'pt-BR', 'Não entender nada do que está acontecendo.', '"Boiei" é a forma mais comum, dita logo depois de uma explicação confusa.', 'não entender'),
    ('cair a ficha', 'pt-BR', 'Entender algo de repente, depois de um tempo sem perceber.', 'A imagem vem do telefone público antigo, em que a ficha caía quando a ligação era completada.', 'compreender de repente'),
    ('sacar', 'pt-BR', 'Quer dizer entender alguma coisa.', '"Saquei" é "entendi". "Saca?" no fim da frase pede confirmação de que a pessoa acompanhou o raciocínio.', 'entender'),
    ('manjar', 'pt-BR', 'Entender bem de um assunto.', '"Ele manja de carro" quer dizer que é entendido no assunto. "Manjado" é algo já muito conhecido, sem novidade.', 'entender do assunto'),
    ('cao', 'pt-BR', 'Mentira ou enrolação.', '"Contar caô" é inventar história. Termo de origem iorubá, muito usado na Bahia e em São Paulo.', 'mentira'),
    ('lorota', 'pt-BR', 'Mentira, história inventada.', 'Termo mais antigo, hoje mais comum entre gerações mais velhas.', 'mentira'),
    ('papo de doido', 'pt-BR', 'Conversa sem sentido ou pouco confiável.', 'Também usado para descrever algo tão surpreendente que parece inventado.', 'conversa duvidosa'),
    ('sinal amarelo', 'pt-BR', 'Aviso de que algo merece atenção antes de continuar.', 'Metáfora do semáforo. Menos grave que "red flag", que já indica problema.', 'sinal de cautela')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('bagulho', 'pt-BR', 'bagulhinho', 'bagulhinho', 'bagulhinho'),
    ('treco', 'pt-BR', 'trem', 'trem', 'trem'),
    ('treco', 'pt-BR', 'troço', 'troco', 'troco'),
    ('quebrada', 'pt-BR', 'quebrado', 'quebrado', 'quebrado'),
    ('corre', 'pt-BR', 'corridinha', 'corridinha', 'corridinha'),
    ('trampo', 'pt-BR', 'trampar', 'trampar', 'trampar'),
    ('grana', 'pt-BR', 'granas', 'granas', 'granas'),
    ('din din', 'pt-BR', 'dindin', 'dindin', 'dindin'),
    ('din din', 'pt-BR', 'dinheirinho', 'dinheirinho', 'dinheirinho'),
    ('duro', 'pt-BR', 'duro de grana', 'duro de grana', 'duro de grana'),
    ('duro', 'pt-BR', 'liso', 'liso', 'liso'),
    ('quebrar o galho', 'pt-BR', 'quebra galho', 'quebra galho', 'quebra galho'),
    ('dar um jeito', 'pt-BR', 'jeitinho', 'jeitinho', 'jeitinho'),
    ('puxar o saco', 'pt-BR', 'puxa-saco', 'puxa saco', 'puxa saco'),
    ('puxar o saco', 'pt-BR', 'puxa saco', 'puxa saco', 'puxa saco'),
    ('vacilar', 'pt-BR', 'vacilão', 'vacilao', 'vacilao'),
    ('vacilar', 'pt-BR', 'vacilo', 'vacilo', 'vacilo'),
    ('pagar de', 'pt-BR', 'pagando de', 'pagando de', 'pagando de'),
    ('se achar', 'pt-BR', 'achado', 'achado', 'achado'),
    ('se achar', 'pt-BR', 'achada', 'achada', 'achada'),
    ('metido', 'pt-BR', 'metida', 'metida', 'metida'),
    ('metido', 'pt-BR', 'metidinho', 'metidinho', 'metidinho'),
    ('folgado', 'pt-BR', 'folgada', 'folgada', 'folgada'),
    ('cara de pau', 'pt-BR', 'cara-de-pau', 'cara de pau', 'cara de pau'),
    ('sem nocao', 'pt-BR', 'sem nocao', 'sem nocao', 'sem nocao'),
    ('mala', 'pt-BR', 'malão', 'malao', 'malao'),
    ('mala', 'pt-BR', 'mala sem alça', 'mala sem alca', 'mala sem alca'),
    ('chato', 'pt-BR', 'chatão', 'chatao', 'chatao'),
    ('chato', 'pt-BR', 'chatice', 'chatice', 'chatice'),
    ('esquentar a cabeca', 'pt-BR', 'esquenta não', 'esquenta nao', 'esquenta nao'),
    ('encanar', 'pt-BR', 'encanado', 'encanado', 'encanado'),
    ('viajar', 'pt-BR', 'viajando', 'viajando', 'viajando'),
    ('viajar', 'pt-BR', 'viajou', 'viajou', 'viajou'),
    ('brisar', 'pt-BR', 'brisa', 'brisa', 'brisa'),
    ('brisar', 'pt-BR', 'brisado', 'brisado', 'brisado'),
    ('zoar a cabeca', 'pt-BR', 'mexer com a cabeça', 'mexer com a cabeca', 'mexer com a cabeca'),
    ('botar pra quebrar', 'pt-BR', 'botar pra jogo', 'botar pra jogo', 'botar pra jogo'),
    ('meter o pe', 'pt-BR', 'meteu o pé', 'meteu o pe', 'meteu o pe'),
    ('ficar na seca', 'pt-BR', 'na seca', 'na seca', 'na seca'),
    ('azarar', 'pt-BR', 'azaração', 'azaracao', 'azaracao'),
    ('cantada', 'pt-BR', 'cantar', 'cantar', 'cantar'),
    ('papo reto', 'pt-BR', 'papo reto', 'papo reto', 'papo reto'),
    ('papo furado', 'pt-BR', 'conversa fiada', 'conversa fiada', 'conversa fiada'),
    ('pe no chao', 'pt-BR', 'pé no chão', 'pe no chao', 'pe no chao'),
    ('gente boa', 'pt-BR', 'gente fina', 'gente fina', 'gente fina'),
    ('massa', 'pt-BR', 'massa demais', 'massa demais', 'massa demais'),
    ('da hora', 'pt-BR', 'dahora', 'dahora', 'dahora'),
    ('show de bola', 'pt-BR', 'show', 'show', 'show'),
    ('joia', 'pt-BR', 'jóia', 'joia', 'joia'),
    ('beleza', 'pt-BR', 'belezinha', 'belezinha', 'belezinha'),
    ('firmeza', 'pt-BR', 'firmeza total', 'firmeza total', 'firmeza total'),
    ('ta tranquilo', 'pt-BR', 'ta tranquilo ta favoravel', 'ta tranquilo ta favoravel', 'ta tranquilo ta favoravel'),
    ('role', 'pt-BR', 'rolê', 'role', 'role'),
    ('role', 'pt-BR', 'rolezinho', 'rolezinho', 'rolezinho'),
    ('resenha', 'pt-BR', 'resenhar', 'resenhar', 'resenhar'),
    ('esquema', 'pt-BR', 'esquematizar', 'esquematizar', 'esquematizar'),
    ('fechou', 'pt-BR', 'fechô', 'fecho', 'fecho'),
    ('fechou', 'pt-BR', 'fechado', 'fechado', 'fechado'),
    ('colar na fita', 'pt-BR', 'fita', 'fita', 'fita'),
    ('gato', 'pt-BR', 'gata', 'gata', 'gata'),
    ('gato', 'pt-BR', 'gatinho', 'gatinho', 'gatinho'),
    ('coroa', 'pt-BR', 'coroinha', 'coroinha', 'coroinha'),
    ('moleque', 'pt-BR', 'moleque', 'moleque', 'moleque'),
    ('moleque', 'pt-BR', 'molecada', 'molecada', 'molecada'),
    ('guri', 'pt-BR', 'guria', 'guria', 'guria'),
    ('pia', 'pt-BR', 'pia', 'pia', 'pia'),
    ('veia', 'pt-BR', 'veia', 'veia', 'veia'),
    ('veia', 'pt-BR', 'minha véia', 'minha veia', 'minha veia'),
    ('xara', 'pt-BR', 'xara', 'xara', 'xara'),
    ('mermao', 'pt-BR', 'mermao', 'mermao', 'mermao'),
    ('mermao', 'pt-BR', 'meu irmão', 'meu irmao', 'meu irmao'),
    ('tiozao', 'pt-BR', 'tiozao', 'tiozao', 'tiozao'),
    ('tiozao', 'pt-BR', 'tia do zap', 'tia do zap', 'tia do zap'),
    ('boomer', 'en', 'ok boomer', 'ok boomer', 'ok boomer'),
    ('geracao z', 'pt-BR', 'gen z', 'gen z', 'gen z'),
    ('geracao z', 'pt-BR', 'genz', 'genz', 'genz'),
    ('alpha', 'en', 'geração alpha', 'geracao alpha', 'geracao alpha'),
    ('mo paia', 'pt-BR', 'paia', 'paia', 'paia'),
    ('mo paia', 'pt-BR', 'que paia', 'que paia', 'que paia'),
    ('zica', 'pt-BR', 'zicado', 'zicado', 'zicado'),
    ('raca', 'pt-BR', 'com raça', 'com raca', 'com raca'),
    ('cara de tacho', 'pt-BR', 'ficar com cara de tacho', 'ficar com cara de tacho', 'ficar com cara de tacho'),
    ('boiar', 'pt-BR', 'boiei', 'boiei', 'boiei'),
    ('cair a ficha', 'pt-BR', 'caiu a ficha', 'caiu a ficha', 'caiu a ficha'),
    ('sacar', 'pt-BR', 'saquei', 'saquei', 'saquei'),
    ('sacar', 'pt-BR', 'saca', 'saca', 'saca'),
    ('manjar', 'pt-BR', 'manja', 'manja', 'manja'),
    ('manjar', 'pt-BR', 'manjado', 'manjado', 'manjado'),
    ('cao', 'pt-BR', 'cao', 'cao', 'cao'),
    ('cao', 'pt-BR', 'caozada', 'caozada', 'caozada')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('bagulho', 'pt-BR', 'rua'),
    ('treco', 'pt-BR', 'rua'),
    ('parada', 'pt-BR', 'rua'),
    ('quebrada', 'pt-BR', 'rua'),
    ('corre', 'pt-BR', 'rua'),
    ('corre', 'pt-BR', 'trabalho'),
    ('trampo', 'pt-BR', 'trabalho'),
    ('bico', 'pt-BR', 'trabalho'),
    ('grana', 'pt-BR', 'trabalho'),
    ('din din', 'pt-BR', 'trabalho'),
    ('din din', 'pt-BR', 'humor'),
    ('pila', 'pt-BR', 'trabalho'),
    ('pila', 'pt-BR', 'regional'),
    ('conto', 'pt-BR', 'trabalho'),
    ('duro', 'pt-BR', 'trabalho'),
    ('quebrar o galho', 'pt-BR', 'acao'),
    ('dar um jeito', 'pt-BR', 'acao'),
    ('gambiarra', 'pt-BR', 'acao'),
    ('puxar o saco', 'pt-BR', 'critica'),
    ('dar mole', 'pt-BR', 'critica'),
    ('vacilar', 'pt-BR', 'critica'),
    ('pisar na bola', 'pt-BR', 'critica'),
    ('pagar de', 'pt-BR', 'critica'),
    ('se achar', 'pt-BR', 'critica'),
    ('metido', 'pt-BR', 'critica'),
    ('folgado', 'pt-BR', 'critica'),
    ('cara de pau', 'pt-BR', 'critica'),
    ('sem nocao', 'pt-BR', 'critica'),
    ('mala', 'pt-BR', 'critica'),
    ('chato', 'pt-BR', 'critica'),
    ('esquentar a cabeca', 'pt-BR', 'emocao'),
    ('encanar', 'pt-BR', 'emocao'),
    ('viajar', 'pt-BR', 'emocao'),
    ('brisar', 'pt-BR', 'emocao'),
    ('zoar a cabeca', 'pt-BR', 'emocao'),
    ('dar um tempo', 'pt-BR', 'relacionamento'),
    ('dar um perdido', 'pt-BR', 'relacionamento'),
    ('chutar o balde', 'pt-BR', 'acao'),
    ('pisar no freio', 'pt-BR', 'acao'),
    ('botar pra quebrar', 'pt-BR', 'acao'),
    ('botar pra quebrar', 'pt-BR', 'elogio'),
    ('meter o pe', 'pt-BR', 'acao'),
    ('dar o fora', 'pt-BR', 'relacionamento'),
    ('ficar na seca', 'pt-BR', 'relacionamento'),
    ('ficar na seca', 'pt-BR', 'humor'),
    ('dar bola', 'pt-BR', 'relacionamento'),
    ('azarar', 'pt-BR', 'relacionamento'),
    ('cantada', 'pt-BR', 'relacionamento'),
    ('papo reto', 'pt-BR', 'descricao'),
    ('papo furado', 'pt-BR', 'critica'),
    ('encher linguica', 'pt-BR', 'critica'),
    ('viajar na maionese', 'pt-BR', 'critica'),
    ('viajar na maionese', 'pt-BR', 'humor'),
    ('pagar o pato', 'pt-BR', 'critica'),
    ('abacaxi', 'pt-BR', 'critica'),
    ('pepino', 'pt-BR', 'critica'),
    ('saia justa', 'pt-BR', 'emocao'),
    ('mao na roda', 'pt-BR', 'elogio'),
    ('pe no chao', 'pt-BR', 'elogio'),
    ('gente boa', 'pt-BR', 'elogio'),
    ('bacana', 'pt-BR', 'elogio'),
    ('massa', 'pt-BR', 'elogio'),
    ('massa', 'pt-BR', 'regional'),
    ('irado', 'pt-BR', 'elogio'),
    ('da hora', 'pt-BR', 'elogio'),
    ('show de bola', 'pt-BR', 'elogio'),
    ('joia', 'pt-BR', 'elogio'),
    ('beleza', 'pt-BR', 'elogio'),
    ('firmeza', 'pt-BR', 'elogio'),
    ('sussa', 'pt-BR', 'emocao'),
    ('ta tranquilo', 'pt-BR', 'emocao'),
    ('ta tranquilo', 'pt-BR', 'humor'),
    ('na moral', 'pt-BR', 'descricao'),
    ('pela moral', 'pt-BR', 'descricao'),
    ('de role', 'pt-BR', 'acao'),
    ('role', 'pt-BR', 'acao'),
    ('resenha', 'pt-BR', 'acao'),
    ('treta boa', 'pt-BR', 'humor'),
    ('esquema', 'pt-BR', 'acao'),
    ('fechou', 'pt-BR', 'acao'),
    ('colar na fita', 'pt-BR', 'acao'),
    ('dar linha', 'pt-BR', 'acao'),
    ('pagar de gato', 'pt-BR', 'critica'),
    ('pagar de gato', 'pt-BR', 'humor'),
    ('gato', 'pt-BR', 'descricao'),
    ('gato', 'pt-BR', 'relacionamento'),
    ('coroa', 'pt-BR', 'descricao'),
    ('moleque', 'pt-BR', 'descricao'),
    ('guri', 'pt-BR', 'descricao'),
    ('guri', 'pt-BR', 'regional'),
    ('pia', 'pt-BR', 'descricao'),
    ('pia', 'pt-BR', 'regional'),
    ('cabra', 'pt-BR', 'descricao'),
    ('cabra', 'pt-BR', 'regional'),
    ('veia', 'pt-BR', 'descricao'),
    ('chapa', 'pt-BR', 'descricao'),
    ('xara', 'pt-BR', 'descricao'),
    ('mermao', 'pt-BR', 'descricao'),
    ('mermao', 'pt-BR', 'regional'),
    ('maluco', 'pt-BR', 'descricao'),
    ('maluco', 'pt-BR', 'regional'),
    ('tiozao', 'pt-BR', 'descricao'),
    ('tiozao', 'pt-BR', 'humor'),
    ('boomer', 'en', 'descricao'),
    ('boomer', 'en', 'critica'),
    ('millennial', 'en', 'descricao'),
    ('geracao z', 'pt-BR', 'descricao'),
    ('alpha', 'en', 'descricao'),
    ('mo paia', 'pt-BR', 'critica'),
    ('zica', 'pt-BR', 'critica'),
    ('pe frio', 'pt-BR', 'critica'),
    ('pe frio', 'pt-BR', 'humor'),
    ('encosto', 'pt-BR', 'critica'),
    ('sangue no olho', 'pt-BR', 'elogio'),
    ('raca', 'pt-BR', 'elogio'),
    ('raca', 'pt-BR', 'esporte'),
    ('garra', 'pt-BR', 'elogio'),
    ('cara de tacho', 'pt-BR', 'emocao'),
    ('cara de tacho', 'pt-BR', 'humor'),
    ('boiar', 'pt-BR', 'emocao'),
    ('cair a ficha', 'pt-BR', 'emocao'),
    ('sacar', 'pt-BR', 'emocao'),
    ('manjar', 'pt-BR', 'descricao'),
    ('cao', 'pt-BR', 'critica'),
    ('lorota', 'pt-BR', 'critica'),
    ('papo de doido', 'pt-BR', 'critica'),
    ('sinal amarelo', 'pt-BR', 'atencao')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

