-- ---------------------------------------------------------------------------
-- regionalismos escola e trabalho
--
-- 91 verbetes, 91 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('uai', 'uai', 'uai', 'pt-BR', FALSE, FALSE),
    ('trem', 'trem', 'trem', 'pt-BR', FALSE, FALSE),
    ('bão', 'bao', 'bao', 'pt-BR', FALSE, FALSE),
    ('sô', 'so', 'so', 'pt-BR', FALSE, FALSE),
    ('cê', 'ce', 'ce', 'pt-BR', FALSE, FALSE),
    ('arretado', 'arretado', 'arretado', 'pt-BR', FALSE, FALSE),
    ('oxente', 'oxente', 'oxente', 'pt-BR', FALSE, FALSE),
    ('visse', 'visse', 'visse', 'pt-BR', FALSE, FALSE),
    ('mainha', 'mainha', 'mainha', 'pt-BR', FALSE, FALSE),
    ('danado', 'danado', 'danado', 'pt-BR', FALSE, FALSE),
    ('avexado', 'avexado', 'avexado', 'pt-BR', FALSE, FALSE),
    ('égua', 'egua', 'egua', 'pt-BR', FALSE, FALSE),
    ('tchê', 'tche', 'tche', 'pt-BR', FALSE, FALSE),
    ('bah', 'bah', 'bah', 'pt-BR', FALSE, FALSE),
    ('capaz', 'capaz', 'capaz', 'pt-BR', FALSE, FALSE),
    ('guria', 'guria', 'guria', 'pt-BR', FALSE, FALSE),
    ('prenda', 'prenda', 'prenda', 'pt-BR', FALSE, FALSE),
    ('bergamota', 'bergamota', 'bergamota', 'pt-BR', FALSE, FALSE),
    ('biscoito', 'biscoito', 'biscoito', 'pt-BR', FALSE, FALSE),
    ('pão francês', 'pao frances', 'pao frances', 'pt-BR', FALSE, FALSE),
    ('sinaleira', 'sinaleira', 'sinaleira', 'pt-BR', FALSE, FALSE),
    ('cadê', 'cade', 'cade', 'pt-BR', FALSE, FALSE),
    ('vixe', 'vixe', 'vixe', 'pt-BR', FALSE, FALSE),
    ('arrudiar', 'arrudiar', 'arrudiar', 'pt-BR', FALSE, FALSE),
    ('peleia', 'peleia', 'peleia', 'pt-BR', FALSE, FALSE),
    ('guaraná', 'guarana', 'guarana', 'pt-BR', FALSE, FALSE),
    ('cuscuz', 'cuscuz', 'cuscuz', 'pt-BR', FALSE, FALSE),
    ('açaí', 'acai', 'acai', 'pt-BR', FALSE, FALSE),
    ('quentinha', 'quentinha', 'quentinha', 'pt-BR', FALSE, FALSE),
    ('bicho', 'bicho', 'bicho', 'pt-BR', FALSE, FALSE),
    ('rapadura', 'rapadura', 'rapadura', 'pt-BR', FALSE, FALSE),
    ('peixe', 'peixe', 'peixe', 'pt-BR', FALSE, FALSE),
    ('abrir o olho', 'abrir o olho', 'abrir o olho', 'pt-BR', FALSE, FALSE),
    ('de olho', 'de olho', 'de olho', 'pt-BR', FALSE, FALSE),
    ('malandro', 'malandro', 'malandro', 'pt-BR', FALSE, FALSE),
    ('sabido', 'sabido', 'sabido', 'pt-BR', FALSE, FALSE),
    ('besta', 'besta', 'besta', 'pt-BR', FALSE, FALSE),
    ('abestado', 'abestado', 'abestado', 'pt-BR', FALSE, FALSE),
    ('azaração', 'azaracao', 'azaracao', 'pt-BR', FALSE, FALSE),
    ('xepa', 'xepa', 'xepa', 'pt-BR', FALSE, FALSE),
    ('boteco', 'boteco', 'boteco', 'pt-BR', FALSE, FALSE),
    ('gelada', 'gelada', 'gelada', 'pt-BR', FALSE, FALSE),
    ('rango', 'rango', 'rango', 'pt-BR', FALSE, FALSE),
    ('larica', 'larica', 'larica', 'pt-BR', FALSE, FALSE),
    ('beliscar', 'beliscar', 'beliscar', 'pt-BR', FALSE, FALSE),
    ('matar a fome', 'matar a fome', 'matar a fome', 'pt-BR', FALSE, FALSE),
    ('dar uma canja', 'dar uma canja', 'dar uma canja', 'pt-BR', FALSE, FALSE),
    ('gato pingado', 'gato pingado', 'gato pingado', 'pt-BR', FALSE, FALSE),
    ('encher o saco', 'encher o saco', 'encher o saco', 'pt-BR', FALSE, FALSE),
    ('pé na jaca', 'pe na jaca', 'pe na jaca', 'pt-BR', FALSE, FALSE),
    ('ressaca', 'ressaca', 'ressaca', 'pt-BR', FALSE, FALSE),
    ('virar a noite', 'virar a noite', 'virar a noite', 'pt-BR', FALSE, FALSE),
    ('dar um perdido no sono', 'dar um perdido no sono', 'dar um perdido no sono', 'pt-BR', FALSE, FALSE),
    ('cochilar', 'cochilar', 'cochilar', 'pt-BR', FALSE, FALSE),
    ('encarar', 'encarar', 'encarar', 'pt-BR', FALSE, FALSE),
    ('topar', 'topar', 'topar', 'pt-BR', FALSE, FALSE),
    ('cair fora', 'cair fora', 'cair fora', 'pt-BR', FALSE, FALSE),
    ('se virar', 'se virar', 'se virar', 'pt-BR', FALSE, FALSE),
    ('correr atrás', 'correr atras', 'correr atras', 'pt-BR', FALSE, FALSE),
    ('meter a cara', 'meter a cara', 'meter a cara', 'pt-BR', FALSE, FALSE),
    ('dar conta', 'dar conta', 'dar conta', 'pt-BR', FALSE, FALSE),
    ('tocar o barco', 'tocar o barco', 'tocar o barco', 'pt-BR', FALSE, FALSE),
    ('segurar as pontas', 'segurar as pontas', 'segurar as pontas', 'pt-BR', FALSE, FALSE),
    ('quebrar a cabeça', 'quebrar a cabeca', 'quebrar a cabeca', 'pt-BR', FALSE, FALSE),
    ('dar um perdido na conta', 'dar um perdido na conta', 'dar um perdido na conta', 'pt-BR', FALSE, FALSE),
    ('rachar a conta', 'rachar a conta', 'rachar a conta', 'pt-BR', FALSE, FALSE),
    ('fiado', 'fiado', 'fiado', 'pt-BR', FALSE, FALSE),
    ('pindaíba', 'pindaiba', 'pindaiba', 'pt-BR', FALSE, FALSE),
    ('no vermelho', 'no vermelho', 'no vermelho', 'pt-BR', FALSE, FALSE),
    ('pé de meia', 'pe de meia', 'pe de meia', 'pt-BR', FALSE, FALSE),
    ('salário mínimo', 'salario minimo', 'salario minimo', 'pt-BR', FALSE, FALSE),
    ('carteira assinada', 'carteira assinada', 'carteira assinada', 'pt-BR', FALSE, FALSE),
    ('pejotizado', 'pejotizado', 'pejotizado', 'pt-BR', FALSE, FALSE),
    ('freela', 'freela', 'freela', 'pt-BR', FALSE, FALSE),
    ('home office', 'home office', 'home office', 'en', FALSE, FALSE),
    ('reunião', 'reuniao', 'reuniao', 'pt-BR', FALSE, FALSE),
    ('burnout', 'burnout', 'burnout', 'en', FALSE, FALSE),
    ('prazo', 'prazo', 'prazo', 'pt-BR', FALSE, FALSE),
    ('cobrar', 'cobrar', 'cobrar', 'pt-BR', FALSE, FALSE),
    ('alinhar', 'alinhar', 'alinhar', 'pt-BR', FALSE, FALSE),
    ('prova', 'prova', 'prova', 'pt-BR', FALSE, FALSE),
    ('cola', 'cola', 'cola', 'pt-BR', FALSE, FALSE),
    ('matar aula', 'matar aula', 'matar aula', 'pt-BR', FALSE, FALSE),
    ('dependência', 'dependencia', 'dependencia', 'pt-BR', FALSE, FALSE),
    ('enem', 'enem', 'enem', 'pt-BR', FALSE, FALSE),
    ('cursinho', 'cursinho', 'cursinho', 'pt-BR', FALSE, FALSE),
    ('calouro', 'calouro', 'calouro', 'pt-BR', FALSE, FALSE),
    ('tcc', 'tcc', 'tcc', 'pt-BR', FALSE, FALSE),
    ('estágio', 'estagio', 'estagio', 'pt-BR', FALSE, FALSE),
    ('monitoria', 'monitoria', 'monitoria', 'pt-BR', FALSE, FALSE),
    ('grupo do trabalho', 'grupo do trabalho', 'grupo do trabalho', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('uai', 'pt-BR', 'Interjeição de espanto ou estranhamento, típica de Minas Gerais.', 'Não tem tradução exata. Serve para surpresa, dúvida e até para começar frase sem sentido específico.', 'ora'),
    ('trem', 'pt-BR', 'Em Minas Gerais, quer dizer coisa, qualquer coisa.', 'Nada a ver com o transporte. "Que trem é esse?" pergunta o que é aquilo. "Trem bão" é elogio.', 'coisa'),
    ('bao', 'pt-BR', 'Forma mineira de dizer "bom".', 'Faz parte de um jeito de falar que corta e junta sílabas, como em "cadê" virando "cadê ocê".', 'bom'),
    ('so', 'pt-BR', 'Palavra que os mineiros põem no fim da frase, sem significado próprio.', 'Vem de "senhor", mas hoje é só marcador de fala, como o "né" do resto do país.', 'cara'),
    ('ce', 'pt-BR', 'Forma falada de "você", comum em Minas e no interior.', '"Ocê" é a variante mais marcada. Na escrita da internet virou "cê" mesmo.', 'você'),
    ('arretado', 'pt-BR', 'Muito bom, impressionante, no Nordeste.', 'Também pode significar bravo, dependendo do tom e do estado. Em Pernambuco costuma ser elogio.', 'excelente'),
    ('oxente', 'pt-BR', 'Interjeição de espanto típica do Nordeste.', 'Contração de "ó gente". "Oxe" é a forma curta, mais usada na Bahia.', 'nossa'),
    ('visse', 'pt-BR', 'Palavra posta no fim da frase em Pernambuco, pedindo concordância.', 'Vem de "viste". Funciona como o "né" ou o "tá ligado" de outras regiões.', 'entendeu'),
    ('mainha', 'pt-BR', 'Forma carinhosa de dizer mãe, no Nordeste.', '"Painho" é o equivalente para pai. Muito usado na Bahia e em Pernambuco.', 'mãe'),
    ('danado', 'pt-BR', 'Pessoa esperta ou levada, geralmente dito com carinho.', 'No Nordeste, "danado de bom" é elogio forte. Também descreve criança travessa.', 'esperto'),
    ('avexado', 'pt-BR', 'Apressado, com pressa demais, no Nordeste.', '"Não se avexe não" é um pedido para a pessoa ter calma. Termo antigo, ainda vivo no interior.', 'apressado'),
    ('egua', 'pt-BR', 'Interjeição de espanto típica do Pará.', '"Égua!" sozinho expressa surpresa. Um dos marcadores mais fortes do jeito paraense de falar.', 'nossa'),
    ('tche', 'pt-BR', 'Palavra usada no fim da frase no Rio Grande do Sul.', 'Funciona como tratamento e como marcador de fala. Origem discutida, possivelmente indígena ou espanhola.', 'cara'),
    ('bah', 'pt-BR', 'Interjeição gaúcha, que serve para quase toda emoção.', 'Pode expressar surpresa, decepção, empolgação ou desânimo. O tom de voz decide qual.', 'nossa'),
    ('capaz', 'pt-BR', 'No Rio Grande do Sul, quer dizer "de jeito nenhum".', 'Sentido invertido em relação ao resto do país, onde "capaz" indica possibilidade. Confunde muito quem é de fora.', 'de jeito nenhum'),
    ('guria', 'pt-BR', 'Menina ou moça, no sul do Brasil.', '"Gurizada" é o grupo de crianças ou jovens. "Guri" é o masculino.', 'menina'),
    ('prenda', 'pt-BR', 'Moça, no vocabulário tradicional gaúcho.', 'Usado principalmente em contexto de tradição, como nos Centros de Tradições Gaúchas.', 'moça'),
    ('bergamota', 'pt-BR', 'A fruta que em outros estados se chama mexerica ou tangerina.', 'É o exemplo clássico de regionalismo brasileiro: a mesma fruta tem mais de dez nomes pelo país.', 'tangerina'),
    ('biscoito', 'pt-BR', 'O que em São Paulo se chama bolacha.', 'A discussão entre "biscoito" e "bolacha" é uma das brigas regionais mais antigas e mais brincalhonas do Brasil.', 'biscoito'),
    ('pao frances', 'pt-BR', 'O pãozinho comum de padaria, que muda de nome conforme o estado.', 'É "cacetinho" no Rio Grande do Sul, "pão careca" em partes do Nordeste, "pão d''água" no Rio de Janeiro.', 'pão francês'),
    ('sinaleira', 'pt-BR', 'O semáforo, no sul do Brasil.', 'É "farol" em partes do Nordeste, "sinal" em São Paulo e "sinaleiro" em Minas.', 'semáforo'),
    ('cade', 'pt-BR', 'Pergunta "onde está?".', 'Contração de "que é feito de". "Quedê" é a variante nordestina.', 'onde está'),
    ('vixe', 'pt-BR', 'Interjeição de espanto, comum no Nordeste e em Minas.', 'Vem de "virgem Maria", mas hoje é usada sem sentido religioso.', 'nossa'),
    ('arrudiar', 'pt-BR', 'Dar a volta, contornar, no interior e no Nordeste.', 'Variação regional de "rodear". Também usado no sentido de enrolar para não responder.', 'contornar'),
    ('peleia', 'pt-BR', 'Briga ou esforço grande, no Rio Grande do Sul.', 'Do espanhol "pelea". Reflete a proximidade cultural do sul com Argentina e Uruguai.', 'luta'),
    ('guarana', 'pt-BR', 'Em várias regiões, qualquer refrigerante é chamado assim.', 'No interior de São Paulo, "tubaína" tem uso parecido: o nome de uma marca virou nome da categoria.', 'refrigerante'),
    ('cuscuz', 'pt-BR', 'Prato de milho cozido no vapor, típico do café da manhã nordestino.', 'Não é o mesmo cuscuz marroquino, feito de trigo. O brasileiro é de flocos de milho.', 'cuscuz de milho'),
    ('acai', 'pt-BR', 'Fruta amazônica, servida no Norte com peixe e farinha, e no resto do país como sobremesa doce.', 'A diferença surpreende quem viaja: no Pará, açaí com açúcar é considerado quase uma ofensa.', 'açaí'),
    ('quentinha', 'pt-BR', 'Refeição pronta servida em embalagem de alumínio, vendida para viagem.', 'É "quentinha" no Rio, "marmitex" em São Paulo. Comum no almoço de quem trabalha fora.', 'marmita'),
    ('bicho', 'pt-BR', 'Forma de chamar alguém, comum no Nordeste e no Norte.', '"E aí, bicho" é cumprimento neutro, sem relação com animal.', 'cara'),
    ('rapadura', 'pt-BR', 'Doce duro feito de caldo de cana, típico do Nordeste.', '"Rapadura é doce mas não é mole não" é ditado sobre pessoa firme, e virou frase de orgulho nordestino.', 'rapadura'),
    ('peixe', 'pt-BR', 'Ser protegido ou favorecido por alguém importante.', '"É peixe do chefe" quer dizer que a pessoa tem tratamento privilegiado.', 'protegido'),
    ('abrir o olho', 'pt-BR', 'Prestar atenção para não ser enganado.', '"Olho vivo" é o estado de atenção. Comum como conselho entre familiares.', 'prestar atenção'),
    ('de olho', 'pt-BR', 'Observando com atenção.', '"Fica de olho" pede vigilância. Também usado para interesse: "tô de olho nesse celular".', 'atento'),
    ('malandro', 'pt-BR', 'Pessoa esperta, que sabe se virar.', 'Pode ser elogio, no sentido de esperteza, ou crítica, no sentido de quem leva vantagem. O contexto separa.', 'esperto'),
    ('sabido', 'pt-BR', 'Pessoa esperta, que percebe as coisas rápido.', 'Muito usado com crianças, quase sempre como elogio afetuoso.', 'esperto'),
    ('besta', 'pt-BR', 'Bobo, ou pessoa que se acha demais.', 'No Nordeste, "besta" costuma indicar quem se acha; em outras regiões, quem é bobo. Os dois sentidos convivem.', 'bobo'),
    ('abestado', 'pt-BR', 'Bobo ou distraído, no Nordeste.', 'Costuma ser dito com humor entre pessoas próximas, não como ofensa séria.', 'bobo'),
    ('azaracao', 'pt-BR', 'A prática de tentar conquistar alguém.', 'Palavra de gerações anteriores, hoje usada com ar nostálgico.', 'cortejo'),
    ('xepa', 'pt-BR', 'O que sobra na feira no fim do dia, vendido barato ou dado.', '"Pegar a xepa" é aproveitar o que sobrou. Termo com carga social forte.', 'sobras da feira'),
    ('boteco', 'pt-BR', 'Bar simples de esquina, onde as pessoas se encontram para conversar.', 'Instituição cultural brasileira. "Papo de boteco" é conversa informal, sem compromisso com precisão.', 'bar'),
    ('gelada', 'pt-BR', 'Cerveja gelada.', '"Breja" e "cerva" são outros apelidos. "Tomar uma gelada" é convite comum de fim de tarde.', 'cerveja'),
    ('rango', 'pt-BR', 'Comida, refeição.', '"Bora rangar" é um convite para comer. Termo antigo e ainda muito usado.', 'comida'),
    ('larica', 'pt-BR', 'Fome repentina, geralmente de comida específica.', 'Costuma aparecer em contexto noturno. "Bateu a larica" descreve a vontade que surge de repente.', 'fome'),
    ('beliscar', 'pt-BR', 'Comer pequenas quantidades ao longo do tempo.', '"Só beliscar" é comer pouco, sem fazer refeição completa.', 'petiscar'),
    ('matar a fome', 'pt-BR', 'Comer o suficiente para não sentir mais fome.', 'Diferente de fazer uma refeição completa: indica resolver a necessidade imediata.', 'saciar-se'),
    ('dar uma canja', 'pt-BR', 'Participar de um show de outro artista por pouco tempo.', 'Também usado fora da música, para quem colabora rapidamente em algo alheio.', 'participação rápida'),
    ('gato pingado', 'pt-BR', 'Público muito pequeno num evento.', '"Só tinha quatro gatos pingados" descreve lugar quase vazio.', 'poucas pessoas'),
    ('encher o saco', 'pt-BR', 'Incomodar alguém insistentemente.', '"Que saco" é a reação a isso. Expressão informal, mas usada com muita naturalidade.', 'importunar'),
    ('pe na jaca', 'pt-BR', 'Exagerar, geralmente em bebida ou comida.', '"Enfiei o pé na jaca" costuma vir no dia seguinte, com tom de arrependimento bem-humorado.', 'exagerar'),
    ('ressaca', 'pt-BR', 'O mal-estar do dia seguinte a uma noite de bebida.', '"Ressaca moral" é o arrependimento pelo que se fez, e não pelo que se bebeu.', 'mal-estar'),
    ('virar a noite', 'pt-BR', 'Passar a noite inteira acordado.', 'Pode ser por diversão, trabalho ou estudo. Muito usado em época de prova.', 'não dormir'),
    ('dar um perdido no sono', 'pt-BR', 'Deixar de dormir quando deveria.', '"Furou o sono" descreve quem passou da hora e agora não consegue dormir.', 'perder o sono'),
    ('cochilar', 'pt-BR', 'Dormir pouco tempo, geralmente sem intenção.', '"Cochilou" também significa distrair-se e perder uma oportunidade: "cochilou, o cachimbo cai".', 'dormir brevemente'),
    ('encarar', 'pt-BR', 'Enfrentar algo difícil.', '"Encara?" é um desafio; "vou encarar" é aceitação. Também significa olhar fixamente para alguém.', 'enfrentar'),
    ('topar', 'pt-BR', 'Aceitar uma proposta ou convite.', '"Topa?" é convite direto. Nada a ver com esbarrar em algo, que é o outro sentido do verbo.', 'aceitar'),
    ('cair fora', 'pt-BR', 'Sair de uma situação ou de um lugar.', 'Pode ser retirada estratégica ou desistência. "Cai fora" também é expulsão rude.', 'retirar-se'),
    ('se virar', 'pt-BR', 'Resolver sozinho, sem ajuda.', '"Me viro" indica autonomia. "Se vira" pode soar como abandono, dependendo do tom.', 'resolver sozinho'),
    ('correr atras', 'pt-BR', 'Esforçar-se para conseguir algo.', '"Correr atrás do prejuízo" é tentar recuperar o que se perdeu.', 'esforçar-se'),
    ('meter a cara', 'pt-BR', 'Dedicar-se a algo com tudo, sem hesitar.', '"Meti a cara nos estudos" descreve dedicação intensa, geralmente por um período curto.', 'dedicar-se'),
    ('dar conta', 'pt-BR', 'Conseguir realizar algo.', '"Não dou conta" admite limite. Em Minas, "dar conta" também aparece no sentido de perceber.', 'conseguir'),
    ('tocar o barco', 'pt-BR', 'Seguir em frente, mesmo sem condições ideais.', 'Descreve persistência em situação difícil, sem heroísmo: é apenas continuar.', 'prosseguir'),
    ('segurar as pontas', 'pt-BR', 'Aguentar uma situação difícil por um tempo.', '"Segura as pontas" é um pedido de paciência até que algo se resolva.', 'aguentar'),
    ('quebrar a cabeca', 'pt-BR', 'Pensar muito para resolver algo difícil.', 'Diferente de "esquentar a cabeça", que é preocupar-se: aqui o foco é o esforço mental.', 'esforçar-se mentalmente'),
    ('dar um perdido na conta', 'pt-BR', 'Sair sem pagar ou não cumprir o combinado.', '"Dar o cano" é o termo mais usado, e vale tanto para dinheiro quanto para compromisso.', 'não cumprir'),
    ('rachar a conta', 'pt-BR', 'Dividir o valor entre as pessoas.', 'Costume comum em restaurantes no Brasil, às vezes com discussão sobre quem consumiu mais.', 'dividir'),
    ('fiado', 'pt-BR', 'Comprar agora e pagar depois, com base na confiança.', 'Prática antiga de comércio de bairro, anotada em caderneta. Ainda existe em cidades pequenas.', 'a crédito'),
    ('pindaiba', 'pt-BR', 'Situação de falta de dinheiro.', '"Tô na pindaíba" é dito com humor. Palavra de origem tupi.', 'sem dinheiro'),
    ('no vermelho', 'pt-BR', 'Com a conta bancária negativa.', 'Vem da cor usada nos extratos para indicar saldo negativo. O oposto é "no azul".', 'com saldo negativo'),
    ('pe de meia', 'pt-BR', 'Dinheiro guardado aos poucos, como reserva.', 'Vem do costume antigo de guardar dinheiro dentro da meia, antes dos bancos populares.', 'poupança'),
    ('salario minimo', 'pt-BR', 'O menor salário que a lei permite pagar por mês de trabalho.', 'Muito usado como unidade de medida informal: "ganha dois mínimos" descreve a faixa de renda.', 'salário mínimo'),
    ('carteira assinada', 'pt-BR', 'Emprego formal, com direitos garantidos por lei.', 'Vem do registro na Carteira de Trabalho. "CLT" é a sigla da lei trabalhista e virou sinônimo do tipo de contrato.', 'emprego formal'),
    ('pejotizado', 'pt-BR', 'Trabalhar como empresa em vez de empregado, sem os direitos de carteira assinada.', 'De "pessoa jurídica". Comum em tecnologia e comunicação, e alvo de discussão trabalhista.', 'contratado como empresa'),
    ('freela', 'pt-BR', 'Trabalho avulso, feito por conta própria para vários clientes.', 'Do inglês "freelance". Diferente de "bico" pelo tipo de trabalho: freela costuma ser especializado.', 'trabalho autônomo'),
    ('home office', 'en', 'Trabalhar de casa em vez de ir ao escritório.', 'Termo que se popularizou no Brasil durante a pandemia de 2020. "Híbrido" é o modelo que mistura os dois.', 'trabalho remoto'),
    ('reuniao', 'pt-BR', 'Conversa de trabalho marcada, hoje quase sempre por vídeo.', '"Call" virou o termo mais usado. "Essa reunião podia ser um e-mail" é reclamação comum.', 'reunião'),
    ('burnout', 'en', 'Esgotamento profundo causado por excesso de trabalho.', 'Reconhecido pela Organização Mundial da Saúde como fenômeno ocupacional desde 2019. Não é apenas cansaço: envolve exaustão, distanciamento do trabalho e queda de desempenho.', 'esgotamento profissional'),
    ('prazo', 'pt-BR', 'A data limite para entregar algo.', '"Deadline" é o termo em inglês, muito usado em escritório. "Estourar o prazo" é passar da data.', 'prazo final'),
    ('cobrar', 'pt-BR', 'Pedir que alguém cumpra o que ficou combinado.', '"Me cobra" é um pedido para ser lembrado. Diferente de cobrar dinheiro, que é o sentido literal.', 'exigir'),
    ('alinhar', 'pt-BR', 'Combinar detalhes com as outras pessoas antes de seguir.', 'Jargão de escritório muito criticado por ser vago. Na prática, quer dizer conversar para todos concordarem.', 'combinar'),
    ('prova', 'pt-BR', 'Avaliação escolar que vale nota.', '"Prova surpresa" é a aplicada sem aviso. "Cair na prova" é o assunto aparecer na avaliação.', 'avaliação'),
    ('cola', 'pt-BR', 'Trapaça na prova, copiando de alguém ou de um papel escondido.', '"Colar" é o verbo. Prática antiga, hoje também feita por celular.', 'trapaça'),
    ('matar aula', 'pt-BR', 'Faltar à aula sem justificativa, escondido dos pais.', '"Cabular" é o termo usado no Nordeste; "gazear" aparece no sul e em Portugal.', 'faltar à aula'),
    ('dependencia', 'pt-BR', 'Ter que refazer uma matéria em que foi reprovado, enquanto avança nas outras.', '"Pegar dp" é ficar nessa situação. Comum no ensino médio e na faculdade.', 'dependência escolar'),
    ('enem', 'pt-BR', 'A prova nacional que serve para entrar em universidades no Brasil.', 'Exame Nacional do Ensino Médio. Milhões de pessoas fazem por ano, e é o principal caminho para o ensino superior público.', 'Exame Nacional do Ensino Médio'),
    ('cursinho', 'pt-BR', 'Curso preparatório para o vestibular ou para o Enem.', '"Cursinho popular" é a versão gratuita ou de baixo custo, mantida por voluntários ou universidades.', 'curso preparatório'),
    ('calouro', 'pt-BR', 'Estudante no primeiro ano da faculdade.', '"Bixo" é a variante usada em algumas universidades. "Veterano" é quem já está há mais tempo.', 'estudante iniciante'),
    ('tcc', 'pt-BR', 'O trabalho final que o estudante entrega para se formar.', 'Trabalho de Conclusão de Curso. Virou assunto de piada pelo estresse que gera nos últimos meses da faculdade.', 'trabalho de conclusão'),
    ('estagio', 'pt-BR', 'Trabalho de aprendizado feito por estudante, com carga e pagamento reduzidos.', 'Regulado por lei própria no Brasil. "Culpa do estagiário" virou piada para explicar qualquer erro público.', 'estágio'),
    ('monitoria', 'pt-BR', 'Quando um aluno mais adiantado ajuda a ensinar os colegas.', 'Costuma valer bolsa ou crédito na faculdade. É a primeira experiência de ensino de muita gente.', 'monitoria'),
    ('grupo do trabalho', 'pt-BR', 'Tarefa escolar feita em equipe.', 'Assunto recorrente de piada, pela desigualdade de esforço entre os integrantes.', 'trabalho em equipe')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('trem', 'pt-BR', 'trem bão', 'trem bao', 'trem bao'),
    ('bao', 'pt-BR', 'bao', 'bao', 'bao'),
    ('bao', 'pt-BR', 'bão demais', 'bao demais', 'bao demais'),
    ('so', 'pt-BR', 'so', 'so', 'so'),
    ('so', 'pt-BR', 'uai sô', 'uai so', 'uai so'),
    ('ce', 'pt-BR', 'ce', 'ce', 'ce'),
    ('ce', 'pt-BR', 'ocê', 'oce', 'oce'),
    ('arretado', 'pt-BR', 'arretada', 'arretada', 'arretada'),
    ('oxente', 'pt-BR', 'oxe', 'oxe', 'oxe'),
    ('mainha', 'pt-BR', 'painho', 'painho', 'painho'),
    ('danado', 'pt-BR', 'danadinho', 'danadinho', 'danadinho'),
    ('avexado', 'pt-BR', 'avexar', 'avexar', 'avexar'),
    ('egua', 'pt-BR', 'egua', 'egua', 'egua'),
    ('egua', 'pt-BR', 'arre égua', 'arre egua', 'arre egua'),
    ('tche', 'pt-BR', 'tche', 'tche', 'tche'),
    ('bah', 'pt-BR', 'ba', 'ba', 'ba'),
    ('guria', 'pt-BR', 'gurizada', 'gurizada', 'gurizada'),
    ('bergamota', 'pt-BR', 'mexerica', 'mexerica', 'mexerica'),
    ('bergamota', 'pt-BR', 'tangerina', 'tangerina', 'tangerina'),
    ('bergamota', 'pt-BR', 'poncã', 'ponca', 'ponca'),
    ('biscoito', 'pt-BR', 'bolacha', 'bolacha', 'bolacha'),
    ('pao frances', 'pt-BR', 'pão careca', 'pao careca', 'pao careca'),
    ('pao frances', 'pt-BR', 'cacetinho', 'cacetinho', 'cacetinho'),
    ('pao frances', 'pt-BR', 'pão d''água', 'pao d agua', 'pao d agua'),
    ('sinaleira', 'pt-BR', 'semáforo', 'semaforo', 'semaforo'),
    ('sinaleira', 'pt-BR', 'farol', 'farol', 'farol'),
    ('sinaleira', 'pt-BR', 'sinal', 'sinal', 'sinal'),
    ('cade', 'pt-BR', 'cade', 'cade', 'cade'),
    ('cade', 'pt-BR', 'quede', 'quede', 'quede'),
    ('vixe', 'pt-BR', 'vixi', 'vixi', 'vixi'),
    ('vixe', 'pt-BR', 'vixe maria', 'vixe maria', 'vixe maria'),
    ('arrudiar', 'pt-BR', 'arrodear', 'arrodear', 'arrodear'),
    ('peleia', 'pt-BR', 'pelear', 'pelear', 'pelear'),
    ('guarana', 'pt-BR', 'tubaína', 'tubaina', 'tubaina'),
    ('acai', 'pt-BR', 'acai', 'acai', 'acai'),
    ('quentinha', 'pt-BR', 'marmitex', 'marmitex', 'marmitex'),
    ('quentinha', 'pt-BR', 'marmita', 'marmita', 'marmita'),
    ('peixe', 'pt-BR', 'ser peixe', 'ser peixe', 'ser peixe'),
    ('abrir o olho', 'pt-BR', 'olho vivo', 'olho vivo', 'olho vivo'),
    ('malandro', 'pt-BR', 'malandragem', 'malandragem', 'malandragem'),
    ('sabido', 'pt-BR', 'sabida', 'sabida', 'sabida'),
    ('sabido', 'pt-BR', 'sabidinho', 'sabidinho', 'sabidinho'),
    ('besta', 'pt-BR', 'bestinha', 'bestinha', 'bestinha'),
    ('besta', 'pt-BR', 'besteira', 'besteira', 'besteira'),
    ('abestado', 'pt-BR', 'abestalhado', 'abestalhado', 'abestalhado'),
    ('boteco', 'pt-BR', 'botequim', 'botequim', 'botequim'),
    ('boteco', 'pt-BR', 'bar', 'bar', 'bar'),
    ('gelada', 'pt-BR', 'breja', 'breja', 'breja'),
    ('gelada', 'pt-BR', 'cerva', 'cerva', 'cerva'),
    ('rango', 'pt-BR', 'rangar', 'rangar', 'rangar'),
    ('encher o saco', 'pt-BR', 'enche o saco', 'enche o saco', 'enche o saco'),
    ('pe na jaca', 'pt-BR', 'enfiar o pé na jaca', 'enfiar o pe na jaca', 'enfiar o pe na jaca'),
    ('ressaca', 'pt-BR', 'ressacado', 'ressacado', 'ressacado'),
    ('virar a noite', 'pt-BR', 'virou a noite', 'virou a noite', 'virou a noite'),
    ('dar um perdido no sono', 'pt-BR', 'furar o sono', 'furar o sono', 'furar o sono'),
    ('cochilar', 'pt-BR', 'cochilo', 'cochilo', 'cochilo'),
    ('cochilar', 'pt-BR', 'tirar um cochilo', 'tirar um cochilo', 'tirar um cochilo'),
    ('topar', 'pt-BR', 'topo', 'topo', 'topo'),
    ('topar', 'pt-BR', 'topa', 'topa', 'topa'),
    ('se virar', 'pt-BR', 'me viro', 'me viro', 'me viro'),
    ('dar conta', 'pt-BR', 'dou conta', 'dou conta', 'dou conta'),
    ('dar conta', 'pt-BR', 'não dou conta', 'nao dou conta', 'nao dou conta'),
    ('dar um perdido na conta', 'pt-BR', 'dar o cano', 'dar o cano', 'dar o cano'),
    ('rachar a conta', 'pt-BR', 'rachar', 'rachar', 'rachar'),
    ('fiado', 'pt-BR', 'na caderneta', 'na caderneta', 'na caderneta'),
    ('pindaiba', 'pt-BR', 'na pindaíba', 'na pindaiba', 'na pindaiba'),
    ('salario minimo', 'pt-BR', 'mínimo', 'minimo', 'minimo'),
    ('carteira assinada', 'pt-BR', 'clt', 'clt', 'clt'),
    ('pejotizado', 'pt-BR', 'pj', 'pj', 'pj'),
    ('pejotizado', 'pt-BR', 'pejotização', 'pejotizacao', 'pejotizacao'),
    ('freela', 'pt-BR', 'freelance', 'freelance', 'freelance'),
    ('freela', 'pt-BR', 'freelancer', 'freelancer', 'freelancer'),
    ('home office', 'en', 'trabalho remoto', 'trabalho remoto', 'trabalho remoto'),
    ('reuniao', 'pt-BR', 'call', 'call', 'call'),
    ('reuniao', 'pt-BR', 'meeting', 'meeting', 'meeting'),
    ('burnout', 'en', 'esgotamento', 'esgotamento', 'esgotamento'),
    ('prazo', 'pt-BR', 'deadline', 'deadline', 'deadline'),
    ('alinhar', 'pt-BR', 'alinhamento', 'alinhamento', 'alinhamento'),
    ('prova', 'pt-BR', 'avaliação', 'avaliacao', 'avaliacao'),
    ('prova', 'pt-BR', 'prova surpresa', 'prova surpresa', 'prova surpresa'),
    ('cola', 'pt-BR', 'colar', 'colar', 'colar'),
    ('cola', 'pt-BR', 'cabulei', 'cabulei', 'cabulei'),
    ('matar aula', 'pt-BR', 'cabular', 'cabular', 'cabular'),
    ('matar aula', 'pt-BR', 'gazear', 'gazear', 'gazear'),
    ('dependencia', 'pt-BR', 'dp', 'dp', 'dp'),
    ('dependencia', 'pt-BR', 'pegar dp', 'pegar dp', 'pegar dp'),
    ('cursinho', 'pt-BR', 'pré-vestibular', 'pre vestibular', 'pre vestibular'),
    ('calouro', 'pt-BR', 'bixo', 'bixo', 'bixo'),
    ('calouro', 'pt-BR', 'veterano', 'veterano', 'veterano'),
    ('tcc', 'pt-BR', 'monografia', 'monografia', 'monografia'),
    ('estagio', 'pt-BR', 'estagiário', 'estagiario', 'estagiario'),
    ('monitoria', 'pt-BR', 'monitor', 'monitor', 'monitor'),
    ('grupo do trabalho', 'pt-BR', 'trabalho em grupo', 'trabalho em grupo', 'trabalho em grupo')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('uai', 'pt-BR', 'regional'),
    ('uai', 'pt-BR', 'emocao'),
    ('trem', 'pt-BR', 'regional'),
    ('bao', 'pt-BR', 'regional'),
    ('bao', 'pt-BR', 'elogio'),
    ('so', 'pt-BR', 'regional'),
    ('ce', 'pt-BR', 'regional'),
    ('ce', 'pt-BR', 'abreviacao'),
    ('arretado', 'pt-BR', 'regional'),
    ('arretado', 'pt-BR', 'elogio'),
    ('oxente', 'pt-BR', 'regional'),
    ('oxente', 'pt-BR', 'emocao'),
    ('visse', 'pt-BR', 'regional'),
    ('mainha', 'pt-BR', 'regional'),
    ('mainha', 'pt-BR', 'familia'),
    ('danado', 'pt-BR', 'regional'),
    ('danado', 'pt-BR', 'descricao'),
    ('avexado', 'pt-BR', 'regional'),
    ('avexado', 'pt-BR', 'emocao'),
    ('egua', 'pt-BR', 'regional'),
    ('egua', 'pt-BR', 'emocao'),
    ('tche', 'pt-BR', 'regional'),
    ('bah', 'pt-BR', 'regional'),
    ('bah', 'pt-BR', 'emocao'),
    ('capaz', 'pt-BR', 'regional'),
    ('capaz', 'pt-BR', 'emocao'),
    ('guria', 'pt-BR', 'regional'),
    ('guria', 'pt-BR', 'descricao'),
    ('prenda', 'pt-BR', 'regional'),
    ('prenda', 'pt-BR', 'descricao'),
    ('bergamota', 'pt-BR', 'regional'),
    ('bergamota', 'pt-BR', 'comida'),
    ('biscoito', 'pt-BR', 'regional'),
    ('biscoito', 'pt-BR', 'comida'),
    ('pao frances', 'pt-BR', 'regional'),
    ('pao frances', 'pt-BR', 'comida'),
    ('sinaleira', 'pt-BR', 'regional'),
    ('cade', 'pt-BR', 'descricao'),
    ('vixe', 'pt-BR', 'regional'),
    ('vixe', 'pt-BR', 'emocao'),
    ('arrudiar', 'pt-BR', 'regional'),
    ('arrudiar', 'pt-BR', 'acao'),
    ('peleia', 'pt-BR', 'regional'),
    ('guarana', 'pt-BR', 'regional'),
    ('guarana', 'pt-BR', 'comida'),
    ('cuscuz', 'pt-BR', 'regional'),
    ('cuscuz', 'pt-BR', 'comida'),
    ('acai', 'pt-BR', 'regional'),
    ('acai', 'pt-BR', 'comida'),
    ('quentinha', 'pt-BR', 'regional'),
    ('quentinha', 'pt-BR', 'comida'),
    ('bicho', 'pt-BR', 'regional'),
    ('bicho', 'pt-BR', 'descricao'),
    ('rapadura', 'pt-BR', 'regional'),
    ('rapadura', 'pt-BR', 'comida'),
    ('peixe', 'pt-BR', 'descricao'),
    ('abrir o olho', 'pt-BR', 'atencao'),
    ('de olho', 'pt-BR', 'atencao'),
    ('malandro', 'pt-BR', 'descricao'),
    ('sabido', 'pt-BR', 'descricao'),
    ('besta', 'pt-BR', 'critica'),
    ('abestado', 'pt-BR', 'regional'),
    ('abestado', 'pt-BR', 'critica'),
    ('azaracao', 'pt-BR', 'relacionamento'),
    ('xepa', 'pt-BR', 'comida'),
    ('boteco', 'pt-BR', 'comida'),
    ('gelada', 'pt-BR', 'comida'),
    ('rango', 'pt-BR', 'comida'),
    ('larica', 'pt-BR', 'comida'),
    ('beliscar', 'pt-BR', 'comida'),
    ('matar a fome', 'pt-BR', 'comida'),
    ('dar uma canja', 'pt-BR', 'musica'),
    ('gato pingado', 'pt-BR', 'descricao'),
    ('gato pingado', 'pt-BR', 'humor'),
    ('encher o saco', 'pt-BR', 'critica'),
    ('pe na jaca', 'pt-BR', 'humor'),
    ('ressaca', 'pt-BR', 'emocao'),
    ('virar a noite', 'pt-BR', 'tempo'),
    ('dar um perdido no sono', 'pt-BR', 'tempo'),
    ('dar um perdido no sono', 'pt-BR', 'humor'),
    ('cochilar', 'pt-BR', 'tempo'),
    ('encarar', 'pt-BR', 'acao'),
    ('topar', 'pt-BR', 'acao'),
    ('cair fora', 'pt-BR', 'acao'),
    ('se virar', 'pt-BR', 'acao'),
    ('correr atras', 'pt-BR', 'acao'),
    ('correr atras', 'pt-BR', 'trabalho'),
    ('meter a cara', 'pt-BR', 'acao'),
    ('dar conta', 'pt-BR', 'acao'),
    ('tocar o barco', 'pt-BR', 'acao'),
    ('segurar as pontas', 'pt-BR', 'acao'),
    ('quebrar a cabeca', 'pt-BR', 'acao'),
    ('dar um perdido na conta', 'pt-BR', 'critica'),
    ('rachar a conta', 'pt-BR', 'trabalho'),
    ('fiado', 'pt-BR', 'trabalho'),
    ('pindaiba', 'pt-BR', 'trabalho'),
    ('no vermelho', 'pt-BR', 'trabalho'),
    ('pe de meia', 'pt-BR', 'trabalho'),
    ('salario minimo', 'pt-BR', 'trabalho'),
    ('carteira assinada', 'pt-BR', 'trabalho'),
    ('pejotizado', 'pt-BR', 'trabalho'),
    ('freela', 'pt-BR', 'trabalho'),
    ('home office', 'en', 'trabalho'),
    ('reuniao', 'pt-BR', 'trabalho'),
    ('reuniao', 'pt-BR', 'humor'),
    ('burnout', 'en', 'trabalho'),
    ('burnout', 'en', 'emocao'),
    ('burnout', 'en', 'atencao'),
    ('prazo', 'pt-BR', 'trabalho'),
    ('cobrar', 'pt-BR', 'trabalho'),
    ('alinhar', 'pt-BR', 'trabalho'),
    ('prova', 'pt-BR', 'escolar'),
    ('cola', 'pt-BR', 'escolar'),
    ('matar aula', 'pt-BR', 'escolar'),
    ('dependencia', 'pt-BR', 'escolar'),
    ('enem', 'pt-BR', 'escolar'),
    ('cursinho', 'pt-BR', 'escolar'),
    ('calouro', 'pt-BR', 'escolar'),
    ('tcc', 'pt-BR', 'escolar'),
    ('estagio', 'pt-BR', 'escolar'),
    ('estagio', 'pt-BR', 'trabalho'),
    ('monitoria', 'pt-BR', 'escolar'),
    ('grupo do trabalho', 'pt-BR', 'escolar'),
    ('grupo do trabalho', 'pt-BR', 'humor')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

