-- ---------------------------------------------------------------------------
-- ingles de redes sociais e memes
--
-- 97 verbetes, 97 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('rizz', 'rizz', 'rizz', 'en', FALSE, FALSE),
    ('gyat', 'gyat', 'gyat', 'en', FALSE, FALSE),
    ('sigma', 'sigma', 'sigma', 'en', FALSE, FALSE),
    ('skibidi', 'skibidi', 'skibidi', 'en', FALSE, FALSE),
    ('ohio', 'ohio', 'ohio', 'en', FALSE, FALSE),
    ('fanum tax', 'fanum tax', 'fanum tax', 'en', FALSE, FALSE),
    ('no cap', 'no cap', 'no cap', 'en', FALSE, FALSE),
    ('bet', 'bet', 'bet', 'en', FALSE, FALSE),
    ('fr', 'fr', 'fr', 'en', FALSE, FALSE),
    ('ngl', 'ngl', 'ngl', 'en', FALSE, FALSE),
    ('tbh', 'tbh', 'tbh', 'en', FALSE, FALSE),
    ('imo', 'imo', 'imo', 'en', FALSE, FALSE),
    ('idk', 'idk', 'idk', 'en', FALSE, FALSE),
    ('iykyk', 'iykyk', 'iykyk', 'en', FALSE, FALSE),
    ('lmao', 'lmao', 'lmao', 'en', FALSE, FALSE),
    ('smh', 'smh', 'smh', 'en', FALSE, FALSE),
    ('istg', 'istg', 'istg', 'en', FALSE, FALSE),
    ('ffs', 'ffs', 'ffs', 'en', FALSE, FALSE),
    ('wdym', 'wdym', 'wdym', 'en', FALSE, FALSE),
    ('hbu', 'hbu', 'hbu', 'en', FALSE, FALSE),
    ('nvm', 'nvm', 'nvm', 'en', FALSE, FALSE),
    ('asap', 'asap', 'asap', 'en', FALSE, FALSE),
    ('eta', 'eta', 'eta', 'en', FALSE, FALSE),
    ('afaik', 'afaik', 'afaik', 'en', FALSE, FALSE),
    ('slay', 'slay', 'slay', 'en', FALSE, FALSE),
    ('ate', 'ate', 'ate', 'en', FALSE, FALSE),
    ('tea', 'tea', 'tea', 'en', FALSE, FALSE),
    ('shade', 'shade', 'shade', 'en', FALSE, FALSE),
    ('receipts', 'receipts', 'receipts', 'en', FALSE, FALSE),
    ('flop', 'flop', 'flop', 'en', FALSE, FALSE),
    ('cringe', 'cringe', 'cringe', 'en', FALSE, FALSE),
    ('yikes', 'yikes', 'yikes', 'en', FALSE, FALSE),
    ('oof', 'oof', 'oof', 'en', FALSE, FALSE),
    ('sus', 'sus', 'sus', 'en', FALSE, FALSE),
    ('simp', 'simp', 'simp', 'en', FALSE, FALSE),
    ('ick', 'ick', 'ick', 'en', FALSE, FALSE),
    ('situationship', 'situationship', 'situationship', 'en', FALSE, FALSE),
    ('breadcrumbing', 'breadcrumbing', 'breadcrumbing', 'en', FALSE, FALSE),
    ('love bombing', 'love bombing', 'love bombing', 'en', FALSE, FALSE),
    ('gaslighting', 'gaslighting', 'gaslighting', 'en', FALSE, FALSE),
    ('boundaries', 'boundaries', 'boundaries', 'en', FALSE, FALSE),
    ('closure', 'closure', 'closure', 'en', FALSE, FALSE),
    ('healing', 'healing', 'healing', 'en', FALSE, FALSE),
    ('era', 'era', 'era', 'en', FALSE, FALSE),
    ('romanticize', 'romanticize', 'romanticize', 'en', FALSE, FALSE),
    ('delulu', 'delulu', 'delulu', 'en', FALSE, FALSE),
    ('glow up', 'glow up', 'glow up', 'en', FALSE, FALSE),
    ('flex', 'flex', 'flex', 'en', FALSE, FALSE),
    ('drip', 'drip', 'drip', 'en', FALSE, FALSE),
    ('fit', 'fit', 'fit', 'en', FALSE, FALSE),
    ('clean', 'clean', 'clean', 'en', FALSE, FALSE),
    ('lowkey', 'lowkey', 'lowkey', 'en', FALSE, FALSE),
    ('highkey', 'highkey', 'highkey', 'en', FALSE, FALSE),
    ('deadass', 'deadass', 'deadass', 'en', FALSE, FALSE),
    ('bussin', 'bussin', 'bussin', 'en', FALSE, FALSE),
    ('mid', 'mid', 'mid', 'en', FALSE, FALSE),
    ('ratio', 'ratio', 'ratio', 'en', FALSE, FALSE),
    ('based', 'based', 'based', 'en', FALSE, FALSE),
    ('touch grass', 'touch grass', 'touch grass', 'en', FALSE, FALSE),
    ('chronically online', 'chronically online', 'chronically online', 'en', FALSE, FALSE),
    ('doomscrolling', 'doomscrolling', 'doomscrolling', 'en', FALSE, FALSE),
    ('brain rot', 'brain rot', 'brain rot', 'en', FALSE, FALSE),
    ('goblin mode', 'goblin mode', 'goblin mode', 'en', FALSE, FALSE),
    ('parasocial', 'parasocial', 'parasocial', 'en', FALSE, FALSE),
    ('npc behavior', 'npc behavior', 'npc behavior', 'en', FALSE, FALSE),
    ('core memory', 'core memory', 'core memory', 'en', FALSE, FALSE),
    ('unhinged', 'unhinged', 'unhinged', 'en', FALSE, FALSE),
    ('feral', 'feral', 'feral', 'en', FALSE, FALSE),
    ('obsessed', 'obsessed', 'obsessed', 'en', FALSE, FALSE),
    ('living for', 'living for', 'living for', 'en', FALSE, FALSE),
    ('not me', 'not me', 'not me', 'en', FALSE, FALSE),
    ('the way', 'the way', 'the way', 'en', FALSE, FALSE),
    ('caught in 4k', 'caught in 4k', 'caught in 4k', 'en', FALSE, FALSE),
    ('understood the assignment', 'understood the assignment', 'understood the assignment', 'en', FALSE, FALSE),
    ('rent free', 'rent free', 'rent free', 'en', FALSE, FALSE),
    ('it''s giving', 'it s giving', 'it s giving', 'en', FALSE, FALSE),
    ('material girl', 'material girl', 'material girl', 'en', FALSE, FALSE),
    ('girl dinner', 'girl dinner', 'girl dinner', 'en', FALSE, FALSE),
    ('hot girl walk', 'hot girl walk', 'hot girl walk', 'en', FALSE, FALSE),
    ('self care', 'self care', 'self care', 'en', FALSE, FALSE),
    ('touch base', 'touch base', 'touch base', 'en', FALSE, FALSE),
    ('quiet quitting', 'quiet quitting', 'quiet quitting', 'en', FALSE, FALSE),
    ('side hustle', 'side hustle', 'side hustle', 'en', FALSE, FALSE),
    ('ceo of', 'ceo of', 'ceo of', 'en', FALSE, FALSE),
    ('villain era', 'villain era', 'villain era', 'en', FALSE, FALSE),
    ('green screen', 'green screen', 'green screen', 'en', FALSE, FALSE),
    ('duet', 'duet', 'duet', 'en', FALSE, FALSE),
    ('fyp', 'fyp', 'fyp', 'en', FALSE, FALSE),
    ('algospeak', 'algospeak', 'algospeak', 'en', FALSE, FALSE),
    ('unalive', 'unalive', 'unalive', 'en', FALSE, FALSE),
    ('seggs', 'seggs', 'seggs', 'en', FALSE, FALSE),
    ('corecore', 'corecore', 'corecore', 'en', FALSE, FALSE),
    ('ragebait', 'ragebait', 'ragebait', 'en', FALSE, FALSE),
    ('engagement farming', 'engagement farming', 'engagement farming', 'en', FALSE, FALSE),
    ('ai slop', 'ai slop', 'ai slop', 'en', FALSE, FALSE),
    ('deepfake', 'deepfake', 'deepfake', 'en', FALSE, FALSE),
    ('prompt', 'prompt', 'prompt', 'en', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('rizz', 'en', 'Facilidade para conquistar alguém, ter charme na conversa.', 'Encurtamento de "charisma", carisma. "Ter rizz" é saber puxar conversa e agradar; "no rizz" é o contrário.', 'charme'),
    ('gyat', 'en', 'Exclamação de espanto diante do corpo de alguém.', 'Deformação de "goddamn". Muito usada por adolescentes, frequentemente como piada exagerada, sem intenção real.', 'exclamação de espanto'),
    ('sigma', 'en', 'Rótulo para o homem que se apresenta como independente e solitário.', 'Vem de uma classificação social sem base científica, popularizada na internet. Hoje é usado quase sempre como piada, inclusive por quem não leva a sério.', 'solitário independente'),
    ('skibidi', 'en', 'Palavra sem significado fixo, usada por humor entre adolescentes.', 'Vem de uma série de vídeos curtos de humor absurdo. O sentido muda conforme a frase e, muitas vezes, é apenas piada sem conteúdo algum.', 'sem sentido definido'),
    ('ohio', 'en', 'Usado para descrever algo estranho ou sem sentido.', 'Vem de uma piada da internet sobre o estado americano de Ohio ser um lugar onde coisas absurdas acontecem. Nada a ver com o estado real.', 'estranho'),
    ('fanum tax', 'en', 'Roubar um pedaço da comida de um amigo, de brincadeira.', 'Nome vindo de um criador de conteúdo que fazia isso nas transmissões. Virou termo geral entre adolescentes.', 'pegar comida alheia'),
    ('no cap', 'en', 'Quer dizer "sem mentira", "é sério mesmo".', 'Vem da gíria norte-americana em que "capping" é exagerar ou mentir. "Cap" sozinho acusa alguém de estar mentindo.', 'sem mentira'),
    ('bet', 'en', 'Quer dizer "combinado" ou "pode deixar".', 'Literalmente "aposta", mas o uso é de confirmação, como o "fechou" brasileiro.', 'combinado'),
    ('fr', 'en', 'Abreviação de "for real", que quer dizer "sério mesmo".', 'Serve para confirmar o que a outra pessoa disse ou para reforçar o próprio ponto. "Frfr" é a versão enfática.', 'sério mesmo'),
    ('ngl', 'en', 'Abreviação de "not gonna lie": "não vou mentir".', 'Usado antes de uma opinião sincera, geralmente uma que a pessoa acha que pode desagradar.', 'sinceramente'),
    ('tbh', 'en', 'Abreviação de "to be honest": "para ser sincero".', 'Muito parecido com "ngl". Também virou brincadeira de rede social, em que a pessoa pede que digam algo sincero sobre ela.', 'para ser sincero'),
    ('imo', 'en', 'Abreviação de "in my opinion": "na minha opinião".', '"Imho" acrescenta "humble", humilde, e costuma ser usado com ironia.', 'na minha opinião'),
    ('idk', 'en', 'Abreviação de "I don''t know": "não sei".', 'Equivalente ao "sla" brasileiro, com o mesmo tom de quem não quer se comprometer.', 'não sei'),
    ('iykyk', 'en', 'Abreviação de "if you know, you know": quem entendeu, entendeu.', 'Marca uma referência que só faz sentido para um grupo. Serve para criar cumplicidade e, ao mesmo tempo, excluir quem está de fora.', 'quem entende, entende'),
    ('lmao', 'en', 'Sigla que representa risada, como o "kkk" brasileiro.', '"Lol" é a mais antiga e mais leve; "lmao" indica risada mais forte. São as equivalentes em inglês do nosso "kkk".', 'risada'),
    ('smh', 'en', 'Abreviação de "shaking my head": balançando a cabeça em desaprovação.', 'Expressa decepção ou incredulidade diante de algo bobo.', 'que decepção'),
    ('istg', 'en', 'Abreviação de "I swear to God": "eu juro".', 'Usado para reforçar uma afirmação ou expressar irritação contida.', 'eu juro'),
    ('ffs', 'en', 'Sigla de irritação, equivalente a um "aff" mais forte.', 'De "for f''s sake". É palavrão abreviado, então o tom é mais pesado que o "aff" brasileiro.', 'que saco'),
    ('wdym', 'en', 'Abreviação de "what do you mean": "como assim?".', 'Pergunta de estranhamento, geralmente quando a pessoa discorda ou não entendeu.', 'como assim'),
    ('hbu', 'en', 'Abreviação de "how about you": "e você?".', 'Devolve a pergunta que acabou de ser feita, mantendo a conversa.', 'e você'),
    ('nvm', 'en', 'Abreviação de "never mind": "deixa pra lá".', 'Usado para desistir de uma pergunta ou de um assunto que já não importa.', 'deixa pra lá'),
    ('asap', 'en', 'Abreviação de "as soon as possible": "o mais rápido possível".', 'Muito usado em ambiente de trabalho, e frequentemente criticado por criar urgência artificial.', 'o quanto antes'),
    ('eta', 'en', 'Abreviação de "estimated time of arrival": previsão de chegada.', 'Vem da aviação. Hoje usado para qualquer coisa: "eta do pedido" é quando a entrega chega.', 'previsão de chegada'),
    ('afaik', 'en', 'Abreviação de "as far as I know": "até onde eu sei".', 'Marca que a informação pode estar incompleta. Comum em fóruns técnicos.', 'até onde sei'),
    ('slay', 'en', 'Elogio forte: mandou muito bem, arrasou.', 'Popularizado em comunidades de moda e música. Não tem relação com o sentido literal do verbo em inglês, que é matar.', 'arrasou'),
    ('ate', 'en', 'Elogio dizendo que a pessoa fez algo muito bem.', 'Literalmente "comeu", no sentido de ter dominado a situação. Vem da cultura ballroom e das comunidades negras dos Estados Unidos.', 'arrasou'),
    ('tea', 'en', 'Fofoca ou informação quente sobre alguém.', '"Spill the tea" é contar a fofoca. Também vem da cultura ballroom, onde "T" significava "truth", verdade.', 'fofoca'),
    ('shade', 'en', 'Crítica indireta e elegante, feita sem dizer o nome.', '"Throw shade" é o equivalente à "indireta" brasileira, com um traço a mais de estilo.', 'crítica velada'),
    ('receipts', 'en', 'Provas de que algo aconteceu, geralmente capturas de tela.', 'Literalmente "recibos". Equivalente ao "tem print" brasileiro.', 'provas'),
    ('flop', 'en', 'Fracasso, algo que não deu certo.', 'Usado para lançamentos, publicações que não engajaram e planos que não funcionaram. Virou verbo em português: "flopou".', 'fracasso'),
    ('cringe', 'en', 'Vergonha alheia; algo tão constrangedor que dá desconforto.', 'Em inglês, "cringe" é o gesto de encolher-se. Virou substantivo e adjetivo também em português: "que cringe", "isso é muito cringe".', 'vergonha alheia'),
    ('yikes', 'en', 'Reação de desconforto diante de algo constrangedor ou ruim.', 'Interjeição antiga do inglês que ganhou vida nova na internet. Próxima do "eita" brasileiro, mas com mais desaprovação.', 'que desconforto'),
    ('oof', 'en', 'Reação a algo doloroso ou constrangedor, como um "ai".', 'Ficou famosa por ser o som de morte de um jogo infantil muito popular. Usada com humor.', 'que dor'),
    ('sus', 'en', 'Suspeito, algo que parece estranho.', 'Encurtamento de "suspicious". Espalhou-se por um jogo em que os participantes acusam uns aos outros de traição.', 'suspeito'),
    ('simp', 'en', 'Alguém que se rebaixa demais tentando agradar uma pessoa.', 'É usado quase sempre de forma pejorativa, e já foi criticado justamente por ridicularizar demonstrações de afeto.', 'bajulador'),
    ('ick', 'en', 'Aversão repentina por alguém, causada por um detalhe pequeno.', '"Deu ick" descreve o momento em que o interesse some por causa de algo bobo. Termo recente, muito usado em vídeos sobre relacionamento.', 'aversão repentina'),
    ('situationship', 'en', 'Relação indefinida, que não é namoro nem só amizade.', 'Junção de "situation" com "relationship". Descreve exatamente a falta de definição, que costuma ser a fonte do problema.', 'relação indefinida'),
    ('breadcrumbing', 'en', 'Dar atenção suficiente para manter alguém interessado, sem intenção de compromisso.', 'De "breadcrumb", migalha. Descreve um padrão de comportamento, não um episódio isolado.', 'manter interesse sem compromisso'),
    ('love bombing', 'en', 'Excesso de carinho e presentes no começo de uma relação, para criar dependência.', 'Reconhecido como padrão de relacionamento abusivo. O excesso costuma vir seguido de afastamento e controle.', 'excesso calculado de afeto'),
    ('gaslighting', 'en', 'Fazer alguém duvidar da própria memória e percepção.', 'Nome vindo de uma peça de 1938 em que o marido manipula a esposa. É forma reconhecida de abuso psicológico, não apenas desacordo.', 'manipulação psicológica'),
    ('boundaries', 'en', 'Os limites que a pessoa estabelece sobre como quer ser tratada.', '"Impor boundaries" virou tema comum em conteúdo sobre saúde mental. Em português se diz simplesmente "limites".', 'limites pessoais'),
    ('closure', 'en', 'A sensação de ter encerrado bem um assunto ou uma relação.', '"Ficar sem closure" descreve o incômodo de um término sem explicação.', 'encerramento'),
    ('healing', 'en', 'Período em que a pessoa está se recuperando emocionalmente.', '"Tô na minha healing era" descreve uma fase de cuidado consigo mesma, geralmente depois de algo difícil.', 'recuperação'),
    ('era', 'en', 'Uma fase da vida da pessoa, tratada como um capítulo com nome.', 'Vem da forma como artistas dividem a carreira em eras. "Tô na minha era de estudar" é jeito bem-humorado de anunciar uma fase.', 'fase'),
    ('romanticize', 'en', 'Enxergar beleza em coisas comuns do dia a dia.', '"Romanticize your life" é conselho comum em vídeos curtos. Também tem sentido crítico: romantizar sofrimento é tratá-lo como bonito.', 'idealizar'),
    ('delulu', 'en', 'Estar iludido, acreditando em algo improvável, geralmente de brincadeira.', 'Deformação de "delusional". "Delulu is the solulu" virou bordão sobre manter esperança sem base.', 'iludido'),
    ('glow up', 'en', 'Transformação para melhor na aparência ou na vida da pessoa.', 'O oposto é "glow down". Vídeos de antes e depois são um formato próprio nas redes.', 'transformação'),
    ('flex', 'en', 'Exibir algo para impressionar os outros.', 'De "flex", flexionar o músculo. "Weird flex but ok" é resposta irônica a quem se gaba de algo estranho.', 'ostentar'),
    ('drip', 'en', 'Roupa de bom gosto, visual bem montado.', 'Elogio à maneira de se vestir. "Ter drip" é ter estilo.', 'estilo'),
    ('fit', 'en', 'A roupa que a pessoa está usando, como conjunto.', 'Encurtamento de "outfit". "Fit check" é mostrar a roupa do dia para quem está assistindo.', 'conjunto de roupa'),
    ('clean', 'en', 'Elogio a algo bem feito, sem excessos.', 'Aplica-se a visual, jogada e design. Vem do sentido de limpo, sem sujeira nem exagero.', 'impecável'),
    ('lowkey', 'en', 'Um pouco, discretamente, sem alarde.', '"Lowkey gostei" quer dizer que a pessoa gostou mas não quer admitir muito. O oposto é "highkey", abertamente.', 'discretamente'),
    ('highkey', 'en', 'Abertamente, sem esconder.', 'Criado por oposição a "lowkey", e bem menos usado que ele.', 'abertamente'),
    ('deadass', 'en', 'Falando sério mesmo, sem brincadeira.', 'Gíria originalmente de Nova York. Equivalente ao "na moral" brasileiro.', 'falando sério'),
    ('bussin', 'en', 'Muito bom, principalmente falando de comida.', 'Vem da gíria afro-americana. "This is bussin" é elogio forte a um prato.', 'delicioso'),
    ('mid', 'en', 'Mediano, nada demais.', 'Do inglês "middle", meio. Usado para dizer que algo muito elogiado é, na verdade, comum.', 'mediano'),
    ('ratio', 'en', 'Aviso de que uma publicação recebeu mais críticas do que apoio.', 'Refere-se à proporção entre respostas e curtidas: quando as respostas superam muito as curtidas, entende-se que a opinião foi mal recebida.', 'rejeição pública'),
    ('based', 'en', 'Elogio a quem fala o que pensa sem se importar com a opinião alheia.', 'Começou como gíria de rua nos Estados Unidos e foi ressignificado na internet. O oposto costuma ser "cringe".', 'autêntico'),
    ('touch grass', 'en', 'Conselho irônico para alguém sair da internet e voltar à vida real.', 'Literalmente "toque na grama". Dito a quem está levando uma discussão online a sério demais.', 'saia da internet'),
    ('chronically online', 'en', 'Pessoa tão imersa na internet que perdeu a noção do mundo fora dela.', 'Crítica a quem aplica regras de discussão online a situações comuns da vida real.', 'excessivamente conectado'),
    ('doomscrolling', 'en', 'Passar horas rolando notícias ruins sem conseguir parar.', 'Junção de "doom", desgraça, com "scroll", rolar. Reconhecido como hábito que piora ansiedade, e comum antes de dormir.', 'consumo compulsivo de más notícias'),
    ('brain rot', 'en', 'Conteúdo tão bobo e repetitivo que parece apodrecer o cérebro.', 'Usado com humor e autocrítica por quem consome esse conteúdo. Palavra do ano de 2024 pelo dicionário Oxford.', 'conteúdo vazio'),
    ('goblin mode', 'en', 'Estado de largar tudo e ficar desleixado sem culpa.', 'Palavra do ano de 2022 pelo dicionário Oxford. Descreve, com humor, o oposto da vida perfeita mostrada nas redes.', 'desleixo assumido'),
    ('parasocial', 'en', 'Sensação de conhecer de verdade alguém famoso que não sabe da sua existência.', 'Termo de psicologia dos anos 50, muito atual com transmissões ao vivo. Não é doença, mas em excesso pode virar dependência emocional.', 'relação unilateral'),
    ('npc behavior', 'en', 'Agir de forma automática e previsível, como um personagem de jogo.', 'Ampliação do uso de "npc". Costuma ser dito com humor, sobre a própria rotina.', 'comportamento automático'),
    ('core memory', 'en', 'Lembrança marcante que fica para sempre.', 'Vem do filme "Divertida Mente", de 2015. Usado com exagero e humor para momentos pequenos.', 'lembrança marcante'),
    ('unhinged', 'en', 'Descontrolado de um jeito engraçado.', 'Literalmente "sem dobradiça". Costuma ser elogio a conteúdo criativo e imprevisível.', 'descontrolado'),
    ('feral', 'en', 'Estado de empolgação descontrolada.', 'Literalmente "selvagem". "Going feral" descreve reagir de forma exagerada a algo que a pessoa ama.', 'eufórico'),
    ('obsessed', 'en', 'Jeito de dizer que gostou muitíssimo de algo.', '"I''m obsessed" quase nunca indica obsessão de verdade: é elogio exagerado, no mesmo tom do "surtei" brasileiro.', 'adorei'),
    ('living for', 'en', 'Expressão de aprovação forte a algo.', '"I''m living for this" quer dizer que a pessoa está adorando. Nada a ver com sobrevivência.', 'estou adorando'),
    ('not me', 'en', 'Forma bem-humorada de admitir algo constrangedor sobre si.', '"Not me crying at 3am" é admitir exatamente aquilo, fingindo negar. Estrutura vinda do TikTok.', 'confesso que'),
    ('the way', 'en', 'Começo de frase que chama atenção para algo engraçado ou absurdo.', '"The way he just left" equivale ao "o jeito que ele simplesmente saiu". Estrutura importada direto do inglês.', 'o jeito que'),
    ('caught in 4k', 'en', 'Ser flagrado com prova clara do que fez.', '"4K" é a resolução de vídeo de alta definição: a piada é que a prova está nítida demais para negar.', 'flagrado com provas'),
    ('understood the assignment', 'en', 'Elogio a quem entendeu exatamente o que precisava fazer e mandou bem.', 'Literalmente "entendeu a tarefa". Usado sobre roupa, apresentação e trabalho.', 'acertou em cheio'),
    ('rent free', 'en', 'Algo que não sai da cabeça da pessoa.', '"Living rent free in my head" quer dizer que aquilo ocupa espaço mental sem pagar aluguel. Metáfora bem-humorada.', 'não sai da cabeça'),
    ('it s giving', 'en', 'Forma de dizer que algo lembra ou passa a impressão de outra coisa.', '"It''s giving férias" quer dizer que aquilo tem cara de férias. Vem da cultura ballroom.', 'parece'),
    ('material girl', 'en', 'Rótulo bem-humorado para quem valoriza bens materiais.', 'Referência à música de Madonna de 1984, que voltou a circular por causa de vídeos curtos.', 'materialista'),
    ('girl dinner', 'en', 'Jantar improvisado feito só do que tinha na geladeira.', 'Virou termo de humor sobre não cozinhar. Também gerou discussão sobre normalizar refeições insuficientes.', 'jantar improvisado'),
    ('hot girl walk', 'en', 'Caminhada feita para melhorar o humor e clarear a cabeça.', 'O nome é brincalhão, mas a prática é levada a sério como cuidado com a saúde mental.', 'caminhada'),
    ('self care', 'en', 'Cuidar de si mesmo, do corpo e da cabeça.', 'Virou também argumento de venda, o que gerou crítica: nem todo autocuidado precisa ser comprado.', 'autocuidado'),
    ('touch base', 'en', 'Conversar rapidamente para alinhar algo no trabalho.', 'Vem do beisebol. É jargão de escritório muito criticado por não dizer nada de concreto.', 'conversar rapidamente'),
    ('quiet quitting', 'en', 'Fazer exatamente o combinado no trabalho, sem se dedicar além disso.', 'Apesar do nome, não é demitir-se: é parar de fazer hora extra não remunerada e de assumir tarefas fora do combinado.', 'cumprir apenas o combinado'),
    ('side hustle', 'en', 'Trabalho paralelo feito além do emprego principal.', 'Equivalente ao "bico" brasileiro, mas com carga cultural diferente: costuma vir com discurso de empreendedorismo.', 'trabalho paralelo'),
    ('ceo of', 'en', 'Brincadeira que declara alguém o maior representante de alguma coisa.', '"Ceo of chegar atrasado" é um jeito bem-humorado de dizer que a pessoa sempre se atrasa.', 'o maior representante de'),
    ('villain era', 'en', 'Fase em que a pessoa decide priorizar a si mesma e dizer não.', 'O nome é dramático de propósito. Na prática descreve parar de agradar todo mundo, não fazer maldade.', 'fase de impor limites'),
    ('green screen', 'en', 'Recurso que coloca uma imagem de fundo atrás da pessoa no vídeo.', 'Muito usado para comentar prints e notícias, com a pessoa aparecendo na frente da imagem.', 'fundo virtual'),
    ('duet', 'en', 'Recurso que permite gravar um vídeo ao lado do vídeo de outra pessoa.', 'Formato do TikTok. Usado para responder, complementar ou zoar o vídeo original.', 'vídeo lado a lado'),
    ('fyp', 'en', 'A tela principal do TikTok, que mostra vídeos escolhidos pelo aplicativo.', 'De "for you page". "Caiu na fyp" quer dizer que o vídeo foi mostrado para muita gente.', 'página principal'),
    ('algospeak', 'en', 'Escrever palavras de forma alterada para não serem bloqueadas pelo aplicativo.', 'Junção de "algoritmo" com "speak". Explica por que aparecem grafias estranhas em vídeos sobre assuntos sensíveis.', 'linguagem de contorno'),
    ('unalive', 'en', 'Palavra inventada para falar de morte sem que o aplicativo bloqueie o conteúdo.', 'Exemplo mais conhecido de "algospeak". Encontrar essa palavra em conversa de adolescente merece atenção, porque o assunto costuma ser sério.', 'morte'),
    ('seggs', 'en', 'Escrita alterada de "sex", para escapar dos filtros dos aplicativos.', 'Outro caso de "algospeak". Aparece principalmente em vídeos e legendas.', 'sexo'),
    ('corecore', 'en', 'Formato de vídeo que junta trechos aleatórios para provocar uma emoção.', 'Costuma tratar de solidão e cansaço da vida moderna, sem falar diretamente sobre isso.', 'montagem emocional'),
    ('ragebait', 'en', 'Conteúdo feito de propósito para irritar e gerar comentários.', 'Junção de "rage", raiva, com "bait", isca. Funciona porque comentário irritado também conta como engajamento.', 'isca de raiva'),
    ('engagement farming', 'en', 'Publicar coisas só para gerar comentários e curtidas, sem conteúdo real.', 'Inclui perguntas bobas, erros propositais e polêmicas fabricadas.', 'busca artificial por interação'),
    ('ai slop', 'en', 'Conteúdo gerado por inteligência artificial em massa, de baixa qualidade.', 'Literalmente "lavagem", a comida dada a porcos. Termo recente, usado para criticar a enxurrada de textos e imagens automáticos.', 'conteúdo automático de baixa qualidade'),
    ('deepfake', 'en', 'Vídeo ou áudio falso que imita o rosto e a voz de uma pessoa real.', 'Usado em golpes e em criação de imagens íntimas falsas, o que é crime no Brasil desde 2024. A qualidade cresceu ao ponto de enganar familiares por telefone.', 'falsificação por inteligência artificial'),
    ('prompt', 'en', 'O texto que a pessoa escreve para pedir algo a uma inteligência artificial.', 'Do inglês "prompt", instrução. "Bom prompt" virou habilidade valorizada.', 'instrução')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('rizz', 'en', 'rizzar', 'rizzar', 'rizzar'),
    ('rizz', 'en', 'unspoken rizz', 'unspoken rizz', 'unspoken rizz'),
    ('gyat', 'en', 'gyatt', 'gyatt', 'gyatt'),
    ('sigma', 'en', 'sigma male', 'sigma male', 'sigma male'),
    ('no cap', 'en', 'cap', 'cap', 'cap'),
    ('no cap', 'en', 'capping', 'capping', 'capping'),
    ('fr', 'en', 'for real', 'for real', 'for real'),
    ('fr', 'en', 'frfr', 'frfr', 'frfr'),
    ('imo', 'en', 'imho', 'imho', 'imho'),
    ('lmao', 'en', 'lol', 'lol', 'lol'),
    ('lmao', 'en', 'lmfao', 'lmfao', 'lmfao'),
    ('lmao', 'en', 'rofl', 'rofl', 'rofl'),
    ('hbu', 'en', 'wbu', 'wbu', 'wbu'),
    ('slay', 'en', 'slayed', 'slayed', 'slayed'),
    ('slay', 'en', 'slaying', 'slaying', 'slaying'),
    ('ate', 'en', 'ate that', 'ate that', 'ate that'),
    ('ate', 'en', 'she ate', 'she ate', 'she ate'),
    ('tea', 'en', 'spill the tea', 'spill the tea', 'spill the tea'),
    ('shade', 'en', 'throw shade', 'throw shade', 'throw shade'),
    ('flop', 'en', 'flopar', 'flopar', 'flopar'),
    ('flop', 'en', 'flopou', 'flopou', 'flopou'),
    ('cringe', 'en', 'cringy', 'cringy', 'cringy'),
    ('cringe', 'en', 'cringar', 'cringar', 'cringar'),
    ('sus', 'en', 'sussy', 'sussy', 'sussy'),
    ('simp', 'en', 'simpar', 'simpar', 'simpar'),
    ('gaslighting', 'en', 'gaslight', 'gaslight', 'gaslight'),
    ('boundaries', 'en', 'limites', 'limites', 'limites'),
    ('healing', 'en', 'healing era', 'healing era', 'healing era'),
    ('era', 'en', 'minha era', 'minha era', 'minha era'),
    ('romanticize', 'en', 'romantizar', 'romantizar', 'romantizar'),
    ('glow up', 'en', 'glowup', 'glowup', 'glowup'),
    ('flex', 'en', 'flexar', 'flexar', 'flexar'),
    ('flex', 'en', 'flexing', 'flexing', 'flexing'),
    ('fit', 'en', 'outfit', 'outfit', 'outfit'),
    ('fit', 'en', 'fit check', 'fit check', 'fit check'),
    ('lowkey', 'en', 'low key', 'low key', 'low key'),
    ('ratio', 'en', 'ratioed', 'ratioed', 'ratioed'),
    ('doomscrolling', 'en', 'doomscroll', 'doomscroll', 'doomscroll'),
    ('brain rot', 'en', 'brainrot', 'brainrot', 'brainrot'),
    ('not me', 'en', 'not me doing', 'not me doing', 'not me doing'),
    ('rent free', 'en', 'living rent free', 'living rent free', 'living rent free'),
    ('it s giving', 'en', 'its giving', 'its giving', 'its giving'),
    ('self care', 'en', 'autocuidado', 'autocuidado', 'autocuidado'),
    ('duet', 'en', 'dueto', 'dueto', 'dueto'),
    ('fyp', 'en', 'for you page', 'for you page', 'for you page'),
    ('ai slop', 'en', 'slop', 'slop', 'slop')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('rizz', 'en', 'relacionamento'),
    ('rizz', 'en', 'redes'),
    ('gyat', 'en', 'redes'),
    ('sigma', 'en', 'descricao'),
    ('sigma', 'en', 'redes'),
    ('skibidi', 'en', 'redes'),
    ('skibidi', 'en', 'humor'),
    ('ohio', 'en', 'redes'),
    ('ohio', 'en', 'humor'),
    ('fanum tax', 'en', 'redes'),
    ('fanum tax', 'en', 'humor'),
    ('no cap', 'en', 'descricao'),
    ('bet', 'en', 'descricao'),
    ('fr', 'en', 'abreviacao'),
    ('ngl', 'en', 'abreviacao'),
    ('tbh', 'en', 'abreviacao'),
    ('imo', 'en', 'abreviacao'),
    ('idk', 'en', 'abreviacao'),
    ('iykyk', 'en', 'abreviacao'),
    ('lmao', 'en', 'abreviacao'),
    ('lmao', 'en', 'humor'),
    ('smh', 'en', 'abreviacao'),
    ('smh', 'en', 'emocao'),
    ('istg', 'en', 'abreviacao'),
    ('istg', 'en', 'emocao'),
    ('ffs', 'en', 'abreviacao'),
    ('ffs', 'en', 'emocao'),
    ('wdym', 'en', 'abreviacao'),
    ('hbu', 'en', 'abreviacao'),
    ('nvm', 'en', 'abreviacao'),
    ('asap', 'en', 'abreviacao'),
    ('asap', 'en', 'trabalho'),
    ('eta', 'en', 'abreviacao'),
    ('afaik', 'en', 'abreviacao'),
    ('slay', 'en', 'elogio'),
    ('ate', 'en', 'elogio'),
    ('tea', 'en', 'redes'),
    ('shade', 'en', 'critica'),
    ('receipts', 'en', 'redes'),
    ('flop', 'en', 'critica'),
    ('cringe', 'en', 'critica'),
    ('cringe', 'en', 'emocao'),
    ('yikes', 'en', 'emocao'),
    ('oof', 'en', 'emocao'),
    ('sus', 'en', 'descricao'),
    ('simp', 'en', 'relacionamento'),
    ('simp', 'en', 'critica'),
    ('ick', 'en', 'relacionamento'),
    ('situationship', 'en', 'relacionamento'),
    ('breadcrumbing', 'en', 'relacionamento'),
    ('breadcrumbing', 'en', 'atencao'),
    ('love bombing', 'en', 'relacionamento'),
    ('love bombing', 'en', 'atencao'),
    ('gaslighting', 'en', 'relacionamento'),
    ('gaslighting', 'en', 'atencao'),
    ('boundaries', 'en', 'relacionamento'),
    ('closure', 'en', 'relacionamento'),
    ('closure', 'en', 'emocao'),
    ('healing', 'en', 'emocao'),
    ('era', 'en', 'descricao'),
    ('romanticize', 'en', 'emocao'),
    ('delulu', 'en', 'humor'),
    ('glow up', 'en', 'descricao'),
    ('glow up', 'en', 'elogio'),
    ('flex', 'en', 'critica'),
    ('drip', 'en', 'elogio'),
    ('drip', 'en', 'descricao'),
    ('fit', 'en', 'descricao'),
    ('clean', 'en', 'elogio'),
    ('lowkey', 'en', 'descricao'),
    ('highkey', 'en', 'descricao'),
    ('deadass', 'en', 'descricao'),
    ('bussin', 'en', 'elogio'),
    ('bussin', 'en', 'comida'),
    ('mid', 'en', 'critica'),
    ('ratio', 'en', 'redes'),
    ('ratio', 'en', 'critica'),
    ('based', 'en', 'elogio'),
    ('touch grass', 'en', 'critica'),
    ('touch grass', 'en', 'humor'),
    ('chronically online', 'en', 'critica'),
    ('doomscrolling', 'en', 'atencao'),
    ('doomscrolling', 'en', 'emocao'),
    ('brain rot', 'en', 'critica'),
    ('brain rot', 'en', 'humor'),
    ('goblin mode', 'en', 'humor'),
    ('goblin mode', 'en', 'descricao'),
    ('parasocial', 'en', 'redes'),
    ('parasocial', 'en', 'atencao'),
    ('npc behavior', 'en', 'critica'),
    ('npc behavior', 'en', 'humor'),
    ('core memory', 'en', 'emocao'),
    ('unhinged', 'en', 'descricao'),
    ('unhinged', 'en', 'humor'),
    ('feral', 'en', 'emocao'),
    ('feral', 'en', 'humor'),
    ('obsessed', 'en', 'elogio'),
    ('obsessed', 'en', 'emocao'),
    ('living for', 'en', 'elogio'),
    ('not me', 'en', 'humor'),
    ('the way', 'en', 'humor'),
    ('caught in 4k', 'en', 'humor'),
    ('understood the assignment', 'en', 'elogio'),
    ('rent free', 'en', 'humor'),
    ('it s giving', 'en', 'descricao'),
    ('material girl', 'en', 'descricao'),
    ('material girl', 'en', 'humor'),
    ('girl dinner', 'en', 'comida'),
    ('girl dinner', 'en', 'humor'),
    ('hot girl walk', 'en', 'emocao'),
    ('self care', 'en', 'emocao'),
    ('touch base', 'en', 'trabalho'),
    ('quiet quitting', 'en', 'trabalho'),
    ('side hustle', 'en', 'trabalho'),
    ('ceo of', 'en', 'humor'),
    ('villain era', 'en', 'humor'),
    ('villain era', 'en', 'emocao'),
    ('green screen', 'en', 'redes'),
    ('duet', 'en', 'redes'),
    ('fyp', 'en', 'redes'),
    ('algospeak', 'en', 'redes'),
    ('unalive', 'en', 'redes'),
    ('unalive', 'en', 'atencao'),
    ('seggs', 'en', 'redes'),
    ('corecore', 'en', 'redes'),
    ('ragebait', 'en', 'redes'),
    ('ragebait', 'en', 'critica'),
    ('engagement farming', 'en', 'redes'),
    ('engagement farming', 'en', 'critica'),
    ('ai slop', 'en', 'redes'),
    ('ai slop', 'en', 'critica'),
    ('deepfake', 'en', 'redes'),
    ('deepfake', 'en', 'atencao'),
    ('prompt', 'en', 'redes')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

