-- ---------------------------------------------------------------------------
-- corpo aparencia e saude mental
--
-- 99 verbetes, 100 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('shape', 'shape', 'shape', 'en', FALSE, FALSE),
    ('bombado', 'bombado', 'bombado', 'pt-BR', FALSE, FALSE),
    ('trincado', 'trincado', 'trincado', 'pt-BR', FALSE, FALSE),
    ('seco', 'seco', 'seco', 'pt-BR', FALSE, FALSE),
    ('bulking', 'bulking', 'bulking', 'en', FALSE, FALSE),
    ('cutting', 'cutting', 'cutting', 'en', FALSE, FALSE),
    ('treino', 'treino', 'treino', 'pt-BR', FALSE, FALSE),
    ('no pain no gain', 'no pain no gain', 'no pain no gain', 'en', FALSE, FALSE),
    ('gordofobia', 'gordofobia', 'gordofobia', 'pt-BR', FALSE, FALSE),
    ('body positive', 'body positive', 'body positive', 'en', FALSE, FALSE),
    ('padrão', 'padrao', 'padrao', 'pt-BR', FALSE, FALSE),
    ('autoestima', 'autoestima', 'autoestima', 'pt-BR', FALSE, FALSE),
    ('ansiedade', 'ansiedade', 'ansiedade', 'pt-BR', FALSE, FALSE),
    ('crise', 'crise', 'crise', 'pt-BR', FALSE, FALSE),
    ('burnout', 'burnout', 'burnout', 'en', FALSE, FALSE),
    ('sobrecarga', 'sobrecarga', 'sobrecarga', 'pt-BR', FALSE, FALSE),
    ('terapia', 'terapia', 'terapia', 'pt-BR', FALSE, FALSE),
    ('psicólogo', 'psicologo', 'psicologo', 'pt-BR', FALSE, FALSE),
    ('surto', 'surto', 'surto', 'pt-BR', FALSE, FALSE),
    ('sofrência', 'sofrencia', 'sofrencia', 'pt-BR', FALSE, FALSE),
    ('carente', 'carente', 'carente', 'pt-BR', FALSE, FALSE),
    ('coração partido', 'coracao partido', 'coracao partido', 'pt-BR', FALSE, FALSE),
    ('luto', 'luto', 'luto', 'pt-BR', FALSE, FALSE),
    ('gatilhado', 'gatilhado', 'gatilhado', 'pt-BR', FALSE, FALSE),
    ('validar', 'validar', 'validar', 'pt-BR', FALSE, FALSE),
    ('acolher', 'acolher', 'acolher', 'pt-BR', FALSE, FALSE),
    ('descarrego', 'descarrego', 'descarrego', 'pt-BR', FALSE, FALSE),
    ('tá difícil', 'ta dificil', 'ta dificil', 'pt-BR', FALSE, FALSE),
    ('no limite', 'no limite', 'no limite', 'pt-BR', FALSE, FALSE),
    ('respira', 'respira', 'respira', 'pt-BR', FALSE, FALSE),
    ('presente', 'presente', 'presente', 'pt-BR', FALSE, FALSE),
    ('chorar as pitangas', 'chorar as pitangas', 'chorar as pitangas', 'pt-BR', FALSE, FALSE),
    ('engolir sapo', 'engolir sapo', 'engolir sapo', 'pt-BR', FALSE, FALSE),
    ('de saco cheio', 'de saco cheio', 'de saco cheio', 'pt-BR', FALSE, FALSE),
    ('revoltado', 'revoltado', 'revoltado', 'pt-BR', FALSE, FALSE),
    ('indignado', 'indignado', 'indignado', 'pt-BR', FALSE, FALSE),
    ('frustrado', 'frustrado', 'frustrado', 'pt-BR', FALSE, FALSE),
    ('aliviado', 'aliviado', 'aliviado', 'pt-BR', FALSE, FALSE),
    ('empolgado', 'empolgado', 'empolgado', 'pt-BR', FALSE, FALSE),
    ('orgulhoso', 'orgulhoso', 'orgulhoso', 'pt-BR', FALSE, FALSE),
    ('grato', 'grato', 'grato', 'pt-BR', FALSE, FALSE),
    ('leve', 'leve', 'leve', 'pt-BR', FALSE, FALSE),
    ('sono atrasado', 'sono atrasado', 'sono atrasado', 'pt-BR', FALSE, FALSE),
    ('insônia', 'insonia', 'insonia', 'pt-BR', FALSE, FALSE),
    ('procrastinar', 'procrastinar', 'procrastinar', 'pt-BR', FALSE, FALSE),
    ('foco', 'foco', 'foco', 'pt-BR', FALSE, FALSE),
    ('disciplina', 'disciplina', 'disciplina', 'pt-BR', FALSE, FALSE),
    ('rotina', 'rotina', 'rotina', 'pt-BR', FALSE, FALSE),
    ('produtividade', 'produtividade', 'produtividade', 'pt-BR', FALSE, FALSE),
    ('pomodoro', 'pomodoro', 'pomodoro', 'en', FALSE, FALSE),
    ('hiperfoco', 'hiperfoco', 'hiperfoco', 'pt-BR', FALSE, FALSE),
    ('tdah', 'tdah', 'tdah', 'pt-BR', FALSE, FALSE),
    ('neurodivergente', 'neurodivergente', 'neurodivergente', 'pt-BR', FALSE, FALSE),
    ('espectro', 'espectro', 'espectro', 'pt-BR', FALSE, FALSE),
    ('mascarar', 'mascarar', 'mascarar', 'pt-BR', FALSE, FALSE),
    ('socializar', 'socializar', 'socializar', 'pt-BR', FALSE, FALSE),
    ('introvertido', 'introvertido', 'introvertido', 'pt-BR', FALSE, FALSE),
    ('sociável', 'sociavel', 'sociavel', 'pt-BR', FALSE, FALSE),
    ('vergonha alheia', 'vergonha alheia', 'vergonha alheia', 'pt-BR', FALSE, FALSE),
    ('constrangido', 'constrangido', 'constrangido', 'pt-BR', FALSE, FALSE),
    ('sem graça', 'sem graca', 'sem graca', 'pt-BR', FALSE, FALSE),
    ('gelado', 'gelado', 'gelado', 'pt-BR', FALSE, FALSE),
    ('arrepiar', 'arrepiar', 'arrepiar', 'pt-BR', FALSE, FALSE),
    ('borboletas no estômago', 'borboletas no estomago', 'borboletas no estomago', 'pt-BR', FALSE, FALSE),
    ('friozinho na barriga', 'friozinho na barriga', 'friozinho na barriga', 'pt-BR', FALSE, FALSE),
    ('nó na garganta', 'no na garganta', 'no na garganta', 'pt-BR', FALSE, FALSE),
    ('peso no peito', 'peso no peito', 'peso no peito', 'pt-BR', FALSE, FALSE),
    ('vazio', 'vazio', 'vazio', 'pt-BR', FALSE, FALSE),
    ('cansaço', 'cansaco', 'cansaco', 'pt-BR', FALSE, FALSE),
    ('recarregar', 'recarregar', 'recarregar', 'pt-BR', FALSE, FALSE),
    ('pausa', 'pausa', 'pausa', 'pt-BR', FALSE, FALSE),
    ('desacelerar', 'desacelerar', 'desacelerar', 'pt-BR', FALSE, FALSE),
    ('desapegar', 'desapegar', 'desapegar', 'pt-BR', FALSE, FALSE),
    ('seguir em frente', 'seguir em frente', 'seguir em frente', 'pt-BR', FALSE, FALSE),
    ('virar a página', 'virar a pagina', 'virar a pagina', 'pt-BR', FALSE, FALSE),
    ('recomeçar', 'recomecar', 'recomecar', 'pt-BR', FALSE, FALSE),
    ('resiliência', 'resiliencia', 'resiliencia', 'pt-BR', FALSE, FALSE),
    ('vitimismo', 'vitimismo', 'vitimismo', 'pt-BR', FALSE, FALSE),
    ('mimimi', 'mimimi', 'mimimi', 'pt-BR', FALSE, FALSE),
    ('frescura', 'frescura', 'frescura', 'pt-BR', FALSE, FALSE),
    ('drama', 'drama', 'drama', 'pt-BR', FALSE, FALSE),
    ('climão', 'climao', 'climao', 'pt-BR', FALSE, FALSE),
    ('paz', 'paz', 'paz', 'pt-BR', FALSE, FALSE),
    ('energia', 'energia', 'energia', 'pt-BR', FALSE, FALSE),
    ('presença', 'presenca', 'presenca', 'pt-BR', FALSE, FALSE),
    ('postura', 'postura', 'postura', 'pt-BR', FALSE, FALSE),
    ('atitude', 'atitude', 'atitude', 'pt-BR', FALSE, FALSE),
    ('personalidade', 'personalidade', 'personalidade', 'pt-BR', FALSE, FALSE),
    ('vaidoso', 'vaidoso', 'vaidoso', 'pt-BR', FALSE, FALSE),
    ('produzida', 'produzida', 'produzida', 'pt-BR', FALSE, FALSE),
    ('natural', 'natural', 'natural', 'pt-BR', FALSE, FALSE),
    ('filtro', 'filtro', 'filtro', 'pt-BR', FALSE, FALSE),
    ('photoshop', 'photoshop', 'photoshop', 'en', FALSE, FALSE),
    ('sarado', 'sarado', 'sarado', 'pt-BR', FALSE, FALSE),
    ('magrelo', 'magrelo', 'magrelo', 'pt-BR', FALSE, FALSE),
    ('gostoso', 'gostoso', 'gostoso', 'pt-BR', FALSE, FALSE),
    ('cheiroso', 'cheiroso', 'cheiroso', 'pt-BR', FALSE, FALSE),
    ('arrumadinho', 'arrumadinho', 'arrumadinho', 'pt-BR', FALSE, FALSE),
    ('descabelado', 'descabelado', 'descabelado', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('shape', 'en', 'A forma física do corpo de alguém.', '"Tá com shape" elogia quem está em boa forma. Termo vindo da academia e espalhado pelas redes.', 'forma física'),
    ('bombado', 'pt-BR', 'Pessoa muito musculosa.', '"Bombar" também significa fazer sucesso: "o vídeo bombou". Os dois sentidos convivem sem confusão.', 'musculoso'),
    ('trincado', 'pt-BR', 'Corpo com músculos muito definidos.', 'Vem da imagem de linhas marcadas na pele. Elogio comum em contexto de academia.', 'definido'),
    ('seco', 'pt-BR', 'Corpo magro e definido, com pouca gordura.', '"Secar" é o processo de perder gordura. Fora do contexto de corpo, "seco" tem outros sentidos.', 'magro e definido'),
    ('bulking', 'en', 'Fase de comer mais para ganhar massa muscular.', 'O oposto é "cutting", fase de perder gordura. Vocabulário de academia que virou comum entre jovens.', 'ganho de massa'),
    ('cutting', 'en', 'Fase de comer menos para perder gordura.', 'Cuidado: em outros contextos, "cutting" em inglês se refere a automutilação. No vocabulário de academia, não tem essa relação.', 'perda de gordura'),
    ('treino', 'pt-BR', 'Exercício físico feito com regularidade.', '"Malhar" é o termo mais informal. "Dia de perna" e "dia de braço" dividem os treinos por parte do corpo.', 'exercício'),
    ('no pain no gain', 'en', 'Frase que diz que sem esforço não há resultado.', 'Bordão de academia dos anos 80. Hoje é criticado por incentivar treino além do limite seguro.', 'sem esforço não há resultado'),
    ('gordofobia', 'pt-BR', 'Preconceito contra pessoas gordas.', 'Inclui piadas, exclusão e tratamento médico que atribui qualquer sintoma ao peso. Termo usado em discussões sobre saúde e direitos.', 'preconceito por peso'),
    ('body positive', 'en', 'Movimento que defende aceitar o próprio corpo como ele é.', 'Surgiu como reação a padrões de beleza inatingíveis. "Body neutrality" é uma variação: em vez de amar o corpo, apenas não pensar tanto nele.', 'aceitação corporal'),
    ('padrao', 'pt-BR', 'O modelo de aparência que a sociedade trata como ideal.', '"Fora do padrão" descreve quem não corresponde a esse modelo. Discussão central em conversas sobre autoestima.', 'padrão estético'),
    ('autoestima', 'pt-BR', 'O quanto a pessoa se valoriza e se sente bem consigo mesma.', 'Diferente de vaidade: envolve como a pessoa se enxerga, não como quer ser vista.', 'autoestima'),
    ('ansiedade', 'pt-BR', 'Preocupação intensa e antecipada com o que pode acontecer.', 'A palavra virou gíria: "tô ansiosa" muitas vezes é só expectativa. O transtorno de ansiedade é outra coisa, e envolve sintomas físicos e prejuízo na rotina. Vale prestar atenção quando é constante.', 'ansiedade'),
    ('crise', 'pt-BR', 'Episódio agudo de ansiedade, com sintomas físicos fortes.', 'Envolve coração acelerado, falta de ar e sensação de perigo iminente. Quem está em crise precisa de calma e ar, não de conselhos. Se for frequente, pede acompanhamento profissional.', 'crise de ansiedade'),
    ('burnout', 'en', 'Esgotamento profundo causado por excesso de trabalho.', 'Reconhecido pela Organização Mundial da Saúde como fenômeno ocupacional. Não é apenas cansaço: envolve exaustão, distanciamento do trabalho e queda de desempenho.', 'esgotamento profissional'),
    ('sobrecarga', 'pt-BR', 'Ter mais responsabilidades do que consegue dar conta.', 'Diferente de burnout, que é o esgotamento já instalado. A sobrecarga é o estágio anterior, ainda reversível.', 'excesso de demandas'),
    ('terapia', 'pt-BR', 'Acompanhamento com psicólogo para cuidar da saúde mental.', '"Vai fazer terapia" às vezes é usado como ofensa na internet, o que reforça estigma. Buscar terapia é cuidado, não fraqueza.', 'psicoterapia'),
    ('psicologo', 'pt-BR', 'Profissional que ajuda com questões emocionais por meio de conversa.', 'Diferente do psiquiatra, que é médico e pode receitar remédio. Muita gente acompanha com os dois.', 'psicólogo'),
    ('surto', 'pt-BR', 'Reação emocional muito intensa.', 'Na internet quase sempre é empolgação exagerada. No sentido clínico, é episódio grave que precisa de atendimento. O contexto separa, e vale prestar atenção quando a conversa é séria.', 'reação intensa'),
    ('sofrencia', 'pt-BR', 'Sofrimento amoroso vivido de forma dramática, quase como espetáculo.', 'Junção de "sofrer" com "carência". Virou nome de um estilo de sertanejo, e o termo é usado com humor.', 'sofrimento amoroso'),
    ('carente', 'pt-BR', 'Pessoa que está precisando de atenção e afeto.', 'Usado com naturalidade e sem ofensa: "tô carente" é reconhecimento tranquilo do próprio estado.', 'necessitado de afeto'),
    ('coracao partido', 'pt-BR', 'Estado de tristeza depois de um término amoroso.', 'Expressão antiga que a internet manteve viva, muitas vezes com humor.', 'desgosto amoroso'),
    ('luto', 'pt-BR', 'O processo de sofrer uma perda importante.', 'Não se aplica só a morte: também se fala em luto por fim de relação, mudança de cidade ou perda de emprego.', 'luto'),
    ('gatilhado', 'pt-BR', 'Ter uma reação emocional forte despertada por algo.', 'Do inglês "triggered". Palavra de origem clínica que virou uso comum, às vezes com exagero. Quando a reação é intensa e recorrente, pede acompanhamento.', 'emocionalmente ativado'),
    ('validar', 'pt-BR', 'Reconhecer que o sentimento da outra pessoa faz sentido.', '"Buscar validação" é depender demais da aprovação alheia. "Validar o sentimento" é o contrário: acolher sem julgar.', 'reconhecer'),
    ('acolher', 'pt-BR', 'Receber alguém com atenção e sem julgamento.', 'Vocabulário de cuidado que passou da área da saúde para o uso comum.', 'acolher'),
    ('descarrego', 'pt-BR', 'Falar sobre o que está incomodando, para aliviar.', '"Posso desabafar?" é pedido comum. Quem escuta geralmente não precisa resolver nada, só ouvir.', 'desabafo'),
    ('ta dificil', 'pt-BR', 'Jeito de dizer que a situação está complicada.', '"Tá osso" é a versão mais informal, e serve tanto para dificuldade real quanto para reclamação leve.', 'está difícil'),
    ('no limite', 'pt-BR', 'Perto de não aguentar mais.', 'Costuma ser desabafo passageiro. Quando aparece com frequência e junto de isolamento, vale conversar com atenção.', 'no limite'),
    ('respira', 'pt-BR', 'Conselho para se acalmar antes de reagir.', 'Simples e literal: respirar devagar reduz de fato os sintomas físicos de ansiedade.', 'acalme-se'),
    ('presente', 'pt-BR', 'Estar de fato ali, com atenção, e não só de corpo.', '"Estar presente" virou tema de conversas sobre atenção e uso de celular.', 'atento'),
    ('chorar as pitangas', 'pt-BR', 'Reclamar muito, lamentando-se.', 'Expressão antiga, usada com humor. Não indica choro de verdade.', 'lamentar-se'),
    ('engolir sapo', 'pt-BR', 'Aguentar algo desagradável sem poder reclamar.', 'Muito usado em contexto de trabalho, sobre situações que a pessoa suporta por necessidade.', 'suportar em silêncio'),
    ('de saco cheio', 'pt-BR', 'Cansado e irritado com uma situação que se repete.', 'Expressão informal comum, mais forte que "cansado" e mais leve que "revoltado".', 'farto'),
    ('revoltado', 'pt-BR', 'Muito indignado com algo considerado injusto.', 'Diferente de "bravo": a revolta envolve senso de injustiça, não apenas irritação.', 'indignado'),
    ('indignado', 'pt-BR', 'Reação forte diante de algo considerado errado.', 'Palavra formal que circula normalmente em conversa comum, principalmente sobre notícias.', 'indignado'),
    ('frustrado', 'pt-BR', 'Decepcionado por algo que não saiu como esperava.', 'Diferente de triste: a frustração vem especificamente da expectativa não atendida.', 'frustrado'),
    ('aliviado', 'pt-BR', 'Sensação boa de quando uma preocupação passa.', '"Que alívio" é reação comum a boa notícia depois de espera tensa.', 'aliviado'),
    ('empolgado', 'pt-BR', 'Muito animado com algo que vai acontecer.', 'Equivalente brasileiro de "hyped". "Empolgação" também pode ser crítica: "empolgou demais".', 'animado'),
    ('orgulhoso', 'pt-BR', 'Sentimento bom por algo que a pessoa ou alguém próximo conseguiu.', '"Tô orgulhosa de você" é elogio afetivo. Diferente de arrogância, que é outro sentido de orgulho.', 'orgulhoso'),
    ('grato', 'pt-BR', 'Sentimento de agradecimento.', '"Gratidão" sozinha virou forma de encerrar mensagem, e às vezes é criticada por parecer automática.', 'agradecido'),
    ('leve', 'pt-BR', 'Sensação boa de quando o peso emocional diminui.', '"Fica leve" é conselho para não levar algo a sério demais.', 'tranquilo'),
    ('sono atrasado', 'pt-BR', 'O acúmulo de noites mal dormidas.', 'Não se recupera totalmente dormindo mais no fim de semana, ao contrário do que se acredita. Falta crônica de sono afeta humor e concentração.', 'privação de sono'),
    ('insonia', 'pt-BR', 'Dificuldade persistente para dormir.', 'Quando dura semanas e atrapalha o dia seguinte, deixa de ser noite ruim e vira questão de saúde que pede avaliação.', 'insônia'),
    ('procrastinar', 'pt-BR', 'Adiar o que precisa ser feito, mesmo sabendo que vai fazer falta.', 'Muitas vezes não é preguiça: pode vir de ansiedade em relação à tarefa. Assunto comum em conversas sobre estudo e trabalho.', 'adiar'),
    ('foco', 'pt-BR', 'Concentração em uma coisa só.', '"Foco, força e fé" é bordão de motivação. "Perdi o foco" descreve distração.', 'concentração'),
    ('disciplina', 'pt-BR', 'Manter uma rotina mesmo sem vontade.', '"Disciplina supera motivação" é frase comum em conteúdo de produtividade, e resume a ideia de não depender do ânimo do dia.', 'disciplina'),
    ('rotina', 'pt-BR', 'A sequência de coisas que a pessoa faz todo dia.', '"Montar uma rotina" é assunto frequente em conteúdo sobre organização e saúde mental.', 'rotina'),
    ('produtividade', 'pt-BR', 'O quanto a pessoa consegue realizar num tempo.', 'Virou tema de uma indústria inteira de conteúdo, e também alvo de crítica por transformar descanso em culpa.', 'produtividade'),
    ('pomodoro', 'en', 'Técnica de estudo que alterna 25 minutos de trabalho com 5 de pausa.', 'Nome vindo do timer de cozinha em forma de tomate usado pelo criador da técnica nos anos 80.', 'técnica pomodoro'),
    ('hiperfoco', 'pt-BR', 'Concentração intensa em uma coisa só, a ponto de perder a noção do tempo.', 'Termo muito associado a discussões sobre TDAH, mas usado também no sentido comum de estar absorto.', 'concentração intensa'),
    ('tdah', 'pt-BR', 'Condição que afeta atenção, organização e controle de impulsos.', 'Transtorno do Déficit de Atenção com Hiperatividade. O termo virou piada na internet ("meu TDAH falou mais alto"), o que banaliza um diagnóstico que precisa de avaliação profissional.', 'TDAH'),
    ('neurodivergente', 'pt-BR', 'Pessoa cujo funcionamento mental difere do considerado típico.', 'Inclui autismo, TDAH e outras condições. "Neurotípico" é o termo para quem não é. Vocabulário criado pela própria comunidade.', 'neurodivergente'),
    ('espectro', 'pt-BR', 'Referência ao transtorno do espectro autista.', '"No espectro" é como muita gente se refere ao próprio diagnóstico. "Autista" usado como ofensa na internet é discriminação, não gíria.', 'espectro autista'),
    ('mascarar', 'pt-BR', 'Esconder características próprias para parecer com os outros.', 'Do inglês "masking". Muito usado por pessoas autistas para descrever o esforço de se adaptar socialmente, que é exaustivo.', 'camuflagem social'),
    ('socializar', 'pt-BR', 'Conviver com outras pessoas.', '"Bateria social acabou" descreve o cansaço de quem precisa de tempo sozinho depois de conviver muito.', 'conviver'),
    ('introvertido', 'pt-BR', 'Pessoa que recarrega as energias ficando sozinha.', 'Não é o mesmo que tímido: um introvertido pode ser sociável e ainda assim precisar de tempo sozinho para descansar.', 'introvertido'),
    ('sociavel', 'pt-BR', 'Pessoa que se relaciona bem com os outros.', 'Diferente de extrovertido: dá para ser sociável e ainda assim precisar de silêncio depois.', 'sociável'),
    ('vergonha alheia', 'pt-BR', 'Desconforto sentido por causa do constrangimento de outra pessoa.', 'É o mesmo sentimento que o inglês chama de "cringe", e o português tem nome próprio para ele há muito tempo.', 'vergonha alheia'),
    ('constrangido', 'pt-BR', 'Sem graça, desconfortável numa situação.', '"Constrangimento" também tem sentido legal, quando alguém é forçado a fazer algo contra a vontade.', 'constrangido'),
    ('sem graca', 'pt-BR', 'Envergonhado, sem saber como agir.', 'Também significa monótono, falando de coisas: "a festa tava sem graça".', 'envergonhado'),
    ('gelado', 'pt-BR', 'Reação de susto que paralisa a pessoa por um instante.', '"Gelei" descreve o momento em que a pessoa fica sem reação diante de uma notícia ruim.', 'paralisado de susto'),
    ('arrepiar', 'pt-BR', 'Reação física a algo muito emocionante ou muito bonito.', '"Me arrepiei" quase sempre é elogio: indica que aquilo emocionou de verdade.', 'emocionar'),
    ('borboletas no estomago', 'pt-BR', 'Sensação de frio na barriga causada por nervosismo ou paixão.', 'Expressão internacional, presente em várias línguas com a mesma imagem.', 'nervosismo'),
    ('friozinho na barriga', 'pt-BR', 'Sensação de expectativa ou medo leve.', 'Versão brasileira das "borboletas no estômago". Serve para paixão, prova e altura.', 'nervosismo'),
    ('no na garganta', 'pt-BR', 'Sensação de aperto que vem quando a pessoa segura o choro.', 'Descrição física de emoção contida, comum em relatos de momentos difíceis.', 'emoção contida'),
    ('peso no peito', 'pt-BR', 'Sensação física de angústia.', 'Quando é constante e vem sem motivo aparente, pode ser sinal de ansiedade ou depressão, e vale procurar avaliação.', 'angústia'),
    ('vazio', 'pt-BR', 'Sensação de falta de sentido ou de ausência de emoção.', 'Diferente de tristeza, que se sente. O vazio é a ausência do sentir, e quando persiste é sinal que pede atenção. O CVV atende de graça pelo 188.', 'vazio emocional'),
    ('cansaco', 'pt-BR', 'Falta de energia física ou mental.', '"Cansaço que dormir não resolve" é a forma como muita gente descreve exaustão emocional, diferente do cansaço físico.', 'cansaço'),
    ('recarregar', 'pt-BR', 'Descansar para recuperar disposição.', 'Metáfora de bateria, que ficou natural depois que todo mundo passou a carregar celular todo dia.', 'descansar'),
    ('pausa', 'pt-BR', 'Intervalo para descansar no meio de uma atividade.', '"Dar uma pausa" também se aplica a relacionamento, com sentido bem diferente.', 'intervalo'),
    ('desacelerar', 'pt-BR', 'Diminuir o ritmo da vida ou do trabalho.', 'Conselho comum em conversas sobre esgotamento, e mais fácil de dar do que de seguir.', 'reduzir o ritmo'),
    ('desapegar', 'pt-BR', 'Deixar ir algo ou alguém a que se estava preso.', 'Também usado literalmente para objetos: "desapego" é o nome dado a vendas de coisas usadas nas redes.', 'desapegar'),
    ('seguir em frente', 'pt-BR', 'Superar algo e continuar a vida.', '"Move on" é a versão em inglês, também usada no Brasil.', 'superar'),
    ('virar a pagina', 'pt-BR', 'Deixar um assunto para trás e começar outra fase.', 'Metáfora de livro. Mais definitivo que "seguir em frente": sugere encerramento consciente.', 'recomeçar'),
    ('recomecar', 'pt-BR', 'Começar de novo depois de uma perda ou mudança.', 'Palavra comum em conversas sobre mudança de cidade, de carreira ou fim de relação.', 'recomeçar'),
    ('resiliencia', 'pt-BR', 'Capacidade de se recuperar depois de algo difícil.', 'Termo da física que passou para a psicologia. É criticado quando usado para exigir que a pessoa aguente condições ruins em vez de mudá-las.', 'resiliência'),
    ('vitimismo', 'pt-BR', 'Acusação de que alguém exagera o próprio sofrimento para conseguir algo.', 'Termo usado com frequência para desqualificar queixas legítimas, então merece atenção quando aparece numa discussão.', 'exagero de sofrimento'),
    ('mimimi', 'pt-BR', 'Forma debochada de chamar uma reclamação de exagerada.', 'Imita o som de choro. Costuma ser usado para encerrar discussão sem responder ao argumento.', 'reclamação'),
    ('frescura', 'pt-BR', 'Exigência considerada desnecessária.', 'Muito usado para desqualificar necessidades reais, como restrição alimentar ou limite pessoal.', 'exigência excessiva'),
    ('drama', 'pt-BR', 'Reação exagerada a algo pequeno.', 'Pode ser brincadeira entre amigos ou crítica séria. "Drama" também nomeia a confusão em si: "o drama da semana".', 'exagero'),
    ('climao', 'pt-BR', 'Clima constrangedor depois de algo desagradável.', '"Ficou um climão" descreve o silêncio incômodo que se instala num grupo.', 'constrangimento'),
    ('paz', 'pt-BR', 'Estado de tranquilidade emocional.', '"Não mexe com a minha paz" virou frase comum sobre proteger o próprio bem-estar.', 'tranquilidade'),
    ('energia', 'pt-BR', 'A sensação que uma pessoa ou lugar transmite.', 'Uso sem conotação necessariamente espiritual: descreve impressão subjetiva, como "vibe".', 'clima'),
    ('presenca', 'pt-BR', 'Qualidade de quem chama atenção ao entrar num lugar.', 'Elogio sobre carisma e postura, não sobre aparência.', 'carisma'),
    ('postura', 'pt-BR', 'O jeito como a pessoa se comporta diante dos outros.', '"Falta de postura" é crítica ao comportamento, não ao corpo.', 'comportamento'),
    ('atitude', 'pt-BR', 'Coragem para agir em vez de só reclamar.', '"Falta atitude" cobra ação. Diferente do sentido comum da palavra, que é apenas comportamento.', 'iniciativa'),
    ('personalidade', 'pt-BR', 'Ter opinião própria e não seguir a maioria por seguir.', '"Tem personalidade" é elogio à independência, e não descrição neutra do caráter.', 'independência'),
    ('vaidoso', 'pt-BR', 'Quem se preocupa muito com a própria aparência.', 'Nem sempre é crítica: cuidar de si é visto como positivo, e o excesso é o que gera o julgamento.', 'vaidoso'),
    ('produzida', 'pt-BR', 'Arrumada com capricho para uma ocasião.', '"Se produzir" é o ato de se arrumar bem. Elogio quando dito com admiração.', 'arrumado'),
    ('natural', 'pt-BR', 'Sem maquiagem ou edição.', '"Sem filtro" ganhou peso com as redes sociais, onde a edição virou padrão.', 'sem edição'),
    ('filtro', 'pt-BR', 'Efeito que muda a aparência da foto ou do vídeo.', 'Os filtros que alteram o rosto são discutidos por afetarem a autoimagem, principalmente de adolescentes.', 'efeito de imagem'),
    ('photoshop', 'en', 'Imagem alterada por programa de edição.', 'Nome de um programa que virou verbo. "Photoshopado" acusa a foto de não corresponder à realidade.', 'imagem editada'),
    ('sarado', 'pt-BR', 'Pessoa com corpo atlético e definido.', 'Termo mais antigo que "shape" e "trincado", com o mesmo sentido.', 'atlético'),
    ('magrelo', 'pt-BR', 'Pessoa muito magra.', 'Pode ser apelido carinhoso entre próximos ou comentário indesejado sobre o corpo alheio, dependendo de quem fala.', 'muito magro'),
    ('gostoso', 'pt-BR', 'Elogio à aparência física de alguém.', 'Dito a desconhecidos na rua, deixa de ser elogio e passa a ser importunação sexual, que é crime no Brasil desde 2018.', 'atraente'),
    ('gostoso', 'pt-BR', 'Falando de comida, quer dizer saboroso.', 'É o sentido original e o mais comum. O contexto separa sem dificuldade.', 'saboroso'),
    ('cheiroso', 'pt-BR', 'Que tem cheiro bom.', 'Usado como elogio afetuoso, principalmente com crianças e pessoas próximas.', 'perfumado'),
    ('arrumadinho', 'pt-BR', 'Bem apresentado, com aparência cuidada.', 'Diminutivo afetuoso, usado principalmente por gerações mais velhas.', 'bem apresentado'),
    ('descabelado', 'pt-BR', 'Com o cabelo bagunçado.', 'Também usado em sentido figurado para quem está atarefado: "cheguei descabelada de tanta correria".', 'despenteado')
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('shape', 'en', 'shapinho', 'shapinho', 'shapinho'),
    ('bombado', 'pt-BR', 'bombada', 'bombada', 'bombada'),
    ('bombado', 'pt-BR', 'bombar', 'bombar', 'bombar'),
    ('trincado', 'pt-BR', 'trincada', 'trincada', 'trincada'),
    ('seco', 'pt-BR', 'secar', 'secar', 'secar'),
    ('bulking', 'en', 'bulk', 'bulk', 'bulk'),
    ('treino', 'pt-BR', 'treinar', 'treinar', 'treinar'),
    ('treino', 'pt-BR', 'malhar', 'malhar', 'malhar'),
    ('body positive', 'en', 'corpo livre', 'corpo livre', 'corpo livre'),
    ('padrao', 'pt-BR', 'fora do padrão', 'fora do padrao', 'fora do padrao'),
    ('padrao', 'pt-BR', 'padrão de beleza', 'padrao de beleza', 'padrao de beleza'),
    ('ansiedade', 'pt-BR', 'ansioso', 'ansioso', 'ansioso'),
    ('ansiedade', 'pt-BR', 'ansiosa', 'ansiosa', 'ansiosa'),
    ('crise', 'pt-BR', 'crise de ansiedade', 'crise de ansiedade', 'crise de ansiedade'),
    ('crise', 'pt-BR', 'ataque de pânico', 'ataque de panico', 'ataque de panico'),
    ('sobrecarga', 'pt-BR', 'sobrecarregado', 'sobrecarregado', 'sobrecarregado'),
    ('terapia', 'pt-BR', 'fazer terapia', 'fazer terapia', 'fazer terapia'),
    ('terapia', 'pt-BR', 'terapeuta', 'terapeuta', 'terapeuta'),
    ('psicologo', 'pt-BR', 'psi', 'psi', 'psi'),
    ('psicologo', 'pt-BR', 'psicologa', 'psicologa', 'psicologa'),
    ('surto', 'pt-BR', 'surtar', 'surtar', 'surtar'),
    ('surto', 'pt-BR', 'surtei', 'surtei', 'surtei'),
    ('carente', 'pt-BR', 'carência', 'carencia', 'carencia'),
    ('coracao partido', 'pt-BR', 'heartbroken', 'heartbroken', 'heartbroken'),
    ('gatilhado', 'pt-BR', 'me gatilhou', 'me gatilhou', 'me gatilhou'),
    ('validar', 'pt-BR', 'validação', 'validacao', 'validacao'),
    ('acolher', 'pt-BR', 'acolhimento', 'acolhimento', 'acolhimento'),
    ('descarrego', 'pt-BR', 'desabafo', 'desabafo', 'desabafo'),
    ('descarrego', 'pt-BR', 'desabafar', 'desabafar', 'desabafar'),
    ('ta dificil', 'pt-BR', 'ta osso', 'ta osso', 'ta osso'),
    ('ta dificil', 'pt-BR', 'tá osso', 'ta osso', 'ta osso'),
    ('no limite', 'pt-BR', 'no meu limite', 'no meu limite', 'no meu limite'),
    ('respira', 'pt-BR', 'respira fundo', 'respira fundo', 'respira fundo'),
    ('presente', 'pt-BR', 'estar presente', 'estar presente', 'estar presente'),
    ('de saco cheio', 'pt-BR', 'saco cheio', 'saco cheio', 'saco cheio'),
    ('revoltado', 'pt-BR', 'revoltada', 'revoltada', 'revoltada'),
    ('revoltado', 'pt-BR', 'revolta', 'revolta', 'revolta'),
    ('frustrado', 'pt-BR', 'frustração', 'frustracao', 'frustracao'),
    ('aliviado', 'pt-BR', 'alívio', 'alivio', 'alivio'),
    ('empolgado', 'pt-BR', 'empolgação', 'empolgacao', 'empolgacao'),
    ('empolgado', 'pt-BR', 'animado', 'animado', 'animado'),
    ('orgulhoso', 'pt-BR', 'orgulho', 'orgulho', 'orgulho'),
    ('grato', 'pt-BR', 'gratidão', 'gratidao', 'gratidao'),
    ('grato', 'pt-BR', 'grata', 'grata', 'grata'),
    ('leve', 'pt-BR', 'leveza', 'leveza', 'leveza'),
    ('leve', 'pt-BR', 'mais leve', 'mais leve', 'mais leve'),
    ('sono atrasado', 'pt-BR', 'dívida de sono', 'divida de sono', 'divida de sono'),
    ('procrastinar', 'pt-BR', 'procrastinação', 'procrastinacao', 'procrastinacao'),
    ('foco', 'pt-BR', 'focar', 'focar', 'focar'),
    ('foco', 'pt-BR', 'focado', 'focado', 'focado'),
    ('rotina', 'pt-BR', 'rotininha', 'rotininha', 'rotininha'),
    ('produtividade', 'pt-BR', 'produtivo', 'produtivo', 'produtivo'),
    ('tdah', 'pt-BR', 'déficit de atenção', 'deficit de atencao', 'deficit de atencao'),
    ('neurodivergente', 'pt-BR', 'neuroatípico', 'neuroatipico', 'neuroatipico'),
    ('espectro', 'pt-BR', 'tea', 'tea', 'tea'),
    ('espectro', 'pt-BR', 'autista', 'autista', 'autista'),
    ('mascarar', 'pt-BR', 'masking', 'masking', 'masking'),
    ('socializar', 'pt-BR', 'bateria social', 'bateria social', 'bateria social'),
    ('introvertido', 'pt-BR', 'intro', 'intro', 'intro'),
    ('introvertido', 'pt-BR', 'extrovertido', 'extrovertido', 'extrovertido'),
    ('sociavel', 'pt-BR', 'gente boa de rolê', 'gente boa de role', 'gente boa de role'),
    ('vergonha alheia', 'pt-BR', 'cringe', 'cringe', 'cringe'),
    ('constrangido', 'pt-BR', 'constrangimento', 'constrangimento', 'constrangimento'),
    ('gelado', 'pt-BR', 'gelei', 'gelei', 'gelei'),
    ('arrepiar', 'pt-BR', 'arrepiou', 'arrepiou', 'arrepiou'),
    ('arrepiar', 'pt-BR', 'arrepio', 'arrepio', 'arrepio'),
    ('vazio', 'pt-BR', 'me sinto vazio', 'me sinto vazio', 'me sinto vazio'),
    ('cansaco', 'pt-BR', 'cansada', 'cansada', 'cansada'),
    ('cansaco', 'pt-BR', 'exausto', 'exausto', 'exausto'),
    ('recarregar', 'pt-BR', 'recarregar as energias', 'recarregar as energias', 'recarregar as energias'),
    ('pausa', 'pt-BR', 'dar uma pausa', 'dar uma pausa', 'dar uma pausa'),
    ('desapegar', 'pt-BR', 'desapego', 'desapego', 'desapego'),
    ('seguir em frente', 'pt-BR', 'move on', 'move on', 'move on'),
    ('recomecar', 'pt-BR', 'recomeço', 'recomeco', 'recomeco'),
    ('resiliencia', 'pt-BR', 'resiliente', 'resiliente', 'resiliente'),
    ('vitimismo', 'pt-BR', 'se vitimizar', 'se vitimizar', 'se vitimizar'),
    ('frescura', 'pt-BR', 'fresco', 'fresco', 'fresco'),
    ('frescura', 'pt-BR', 'frescurite', 'frescurite', 'frescurite'),
    ('drama', 'pt-BR', 'dramática', 'dramatica', 'dramatica'),
    ('drama', 'pt-BR', 'fazer drama', 'fazer drama', 'fazer drama'),
    ('paz', 'pt-BR', 'em paz', 'em paz', 'em paz'),
    ('paz', 'pt-BR', 'minha paz', 'minha paz', 'minha paz'),
    ('energia', 'pt-BR', 'boa energia', 'boa energia', 'boa energia'),
    ('energia', 'pt-BR', 'energia ruim', 'energia ruim', 'energia ruim'),
    ('presenca', 'pt-BR', 'ter presença', 'ter presenca', 'ter presenca'),
    ('atitude', 'pt-BR', 'ter atitude', 'ter atitude', 'ter atitude'),
    ('personalidade', 'pt-BR', 'ter personalidade', 'ter personalidade', 'ter personalidade'),
    ('vaidoso', 'pt-BR', 'vaidade', 'vaidade', 'vaidade'),
    ('produzida', 'pt-BR', 'produzido', 'produzido', 'produzido'),
    ('produzida', 'pt-BR', 'se produzir', 'se produzir', 'se produzir'),
    ('natural', 'pt-BR', 'sem filtro', 'sem filtro', 'sem filtro'),
    ('photoshop', 'en', 'photoshopado', 'photoshopado', 'photoshopado'),
    ('photoshop', 'en', 'editado', 'editado', 'editado'),
    ('sarado', 'pt-BR', 'sarada', 'sarada', 'sarada'),
    ('magrelo', 'pt-BR', 'magricela', 'magricela', 'magricela'),
    ('gostoso', 'pt-BR', 'gostosa', 'gostosa', 'gostosa'),
    ('cheiroso', 'pt-BR', 'cheirosa', 'cheirosa', 'cheirosa')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('shape', 'en', 'descricao'),
    ('bombado', 'pt-BR', 'descricao'),
    ('trincado', 'pt-BR', 'descricao'),
    ('seco', 'pt-BR', 'descricao'),
    ('bulking', 'en', 'descricao'),
    ('cutting', 'en', 'descricao'),
    ('treino', 'pt-BR', 'esporte'),
    ('no pain no gain', 'en', 'esporte'),
    ('gordofobia', 'pt-BR', 'descricao'),
    ('gordofobia', 'pt-BR', 'atencao'),
    ('body positive', 'en', 'descricao'),
    ('padrao', 'pt-BR', 'descricao'),
    ('padrao', 'pt-BR', 'critica'),
    ('autoestima', 'pt-BR', 'emocao'),
    ('ansiedade', 'pt-BR', 'emocao'),
    ('ansiedade', 'pt-BR', 'atencao'),
    ('crise', 'pt-BR', 'emocao'),
    ('crise', 'pt-BR', 'atencao'),
    ('burnout', 'en', 'emocao'),
    ('burnout', 'en', 'trabalho'),
    ('burnout', 'en', 'atencao'),
    ('sobrecarga', 'pt-BR', 'emocao'),
    ('sobrecarga', 'pt-BR', 'trabalho'),
    ('terapia', 'pt-BR', 'emocao'),
    ('psicologo', 'pt-BR', 'emocao'),
    ('surto', 'pt-BR', 'emocao'),
    ('surto', 'pt-BR', 'atencao'),
    ('sofrencia', 'pt-BR', 'emocao'),
    ('sofrencia', 'pt-BR', 'musica'),
    ('sofrencia', 'pt-BR', 'humor'),
    ('carente', 'pt-BR', 'emocao'),
    ('coracao partido', 'pt-BR', 'emocao'),
    ('coracao partido', 'pt-BR', 'relacionamento'),
    ('luto', 'pt-BR', 'emocao'),
    ('gatilhado', 'pt-BR', 'emocao'),
    ('gatilhado', 'pt-BR', 'atencao'),
    ('validar', 'pt-BR', 'emocao'),
    ('acolher', 'pt-BR', 'emocao'),
    ('descarrego', 'pt-BR', 'emocao'),
    ('ta dificil', 'pt-BR', 'emocao'),
    ('no limite', 'pt-BR', 'emocao'),
    ('no limite', 'pt-BR', 'atencao'),
    ('respira', 'pt-BR', 'emocao'),
    ('presente', 'pt-BR', 'emocao'),
    ('chorar as pitangas', 'pt-BR', 'emocao'),
    ('chorar as pitangas', 'pt-BR', 'humor'),
    ('engolir sapo', 'pt-BR', 'emocao'),
    ('de saco cheio', 'pt-BR', 'emocao'),
    ('revoltado', 'pt-BR', 'emocao'),
    ('indignado', 'pt-BR', 'emocao'),
    ('frustrado', 'pt-BR', 'emocao'),
    ('aliviado', 'pt-BR', 'emocao'),
    ('empolgado', 'pt-BR', 'emocao'),
    ('orgulhoso', 'pt-BR', 'emocao'),
    ('grato', 'pt-BR', 'emocao'),
    ('leve', 'pt-BR', 'emocao'),
    ('sono atrasado', 'pt-BR', 'tempo'),
    ('sono atrasado', 'pt-BR', 'atencao'),
    ('insonia', 'pt-BR', 'atencao'),
    ('procrastinar', 'pt-BR', 'acao'),
    ('foco', 'pt-BR', 'acao'),
    ('disciplina', 'pt-BR', 'acao'),
    ('rotina', 'pt-BR', 'tempo'),
    ('produtividade', 'pt-BR', 'trabalho'),
    ('pomodoro', 'en', 'escolar'),
    ('pomodoro', 'en', 'trabalho'),
    ('hiperfoco', 'pt-BR', 'emocao'),
    ('tdah', 'pt-BR', 'atencao'),
    ('neurodivergente', 'pt-BR', 'descricao'),
    ('espectro', 'pt-BR', 'descricao'),
    ('mascarar', 'pt-BR', 'descricao'),
    ('mascarar', 'pt-BR', 'emocao'),
    ('socializar', 'pt-BR', 'emocao'),
    ('introvertido', 'pt-BR', 'descricao'),
    ('sociavel', 'pt-BR', 'descricao'),
    ('vergonha alheia', 'pt-BR', 'emocao'),
    ('constrangido', 'pt-BR', 'emocao'),
    ('sem graca', 'pt-BR', 'emocao'),
    ('gelado', 'pt-BR', 'emocao'),
    ('arrepiar', 'pt-BR', 'emocao'),
    ('borboletas no estomago', 'pt-BR', 'emocao'),
    ('borboletas no estomago', 'pt-BR', 'relacionamento'),
    ('friozinho na barriga', 'pt-BR', 'emocao'),
    ('no na garganta', 'pt-BR', 'emocao'),
    ('peso no peito', 'pt-BR', 'emocao'),
    ('peso no peito', 'pt-BR', 'atencao'),
    ('vazio', 'pt-BR', 'emocao'),
    ('vazio', 'pt-BR', 'atencao'),
    ('cansaco', 'pt-BR', 'emocao'),
    ('recarregar', 'pt-BR', 'emocao'),
    ('pausa', 'pt-BR', 'tempo'),
    ('desacelerar', 'pt-BR', 'acao'),
    ('desapegar', 'pt-BR', 'acao'),
    ('desapegar', 'pt-BR', 'emocao'),
    ('seguir em frente', 'pt-BR', 'acao'),
    ('virar a pagina', 'pt-BR', 'acao'),
    ('recomecar', 'pt-BR', 'acao'),
    ('resiliencia', 'pt-BR', 'descricao'),
    ('vitimismo', 'pt-BR', 'critica'),
    ('mimimi', 'pt-BR', 'critica'),
    ('frescura', 'pt-BR', 'critica'),
    ('drama', 'pt-BR', 'critica'),
    ('drama', 'pt-BR', 'humor'),
    ('climao', 'pt-BR', 'emocao'),
    ('paz', 'pt-BR', 'emocao'),
    ('energia', 'pt-BR', 'emocao'),
    ('presenca', 'pt-BR', 'descricao'),
    ('postura', 'pt-BR', 'descricao'),
    ('atitude', 'pt-BR', 'descricao'),
    ('personalidade', 'pt-BR', 'descricao'),
    ('vaidoso', 'pt-BR', 'descricao'),
    ('produzida', 'pt-BR', 'descricao'),
    ('natural', 'pt-BR', 'descricao'),
    ('filtro', 'pt-BR', 'redes'),
    ('photoshop', 'en', 'redes'),
    ('sarado', 'pt-BR', 'descricao'),
    ('magrelo', 'pt-BR', 'descricao'),
    ('gostoso', 'pt-BR', 'descricao'),
    ('cheiroso', 'pt-BR', 'descricao'),
    ('arrumadinho', 'pt-BR', 'descricao'),
    ('descabelado', 'pt-BR', 'descricao'),
    ('descabelado', 'pt-BR', 'humor')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

