-- ---------------------------------------------------------------------------
-- girias de familia e casa
--
-- 41 verbetes, 41 sentidos.
--
-- GERADO por curadoria/gerar-migracao.mjs. Nao edite este arquivo a mao:
-- mexa na fonte em curadoria/termos/ e gere de novo. Depois de aplicada,
-- a migracao e imutavel como qualquer outra, e termo novo entra em
-- migracao nova.
--
-- As chaves de busca (termo_normalizado, termo_colapsado) sao calculadas
-- pela mesma regra de Normalizador.java. ConsistenciaDoSeedIT confere no
-- banco que elas batem.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, termo_colapsado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.norm, t.colapsado, i.id, t.nsfw, t.risco
FROM (VALUES
    ('sogrão', 'sograo', 'sograo', 'pt-BR', FALSE, FALSE),
    ('tio do pavê', 'tio do pave', 'tio do pave', 'pt-BR', FALSE, FALSE),
    ('agregado', 'agregado', 'agregado', 'pt-BR', FALSE, FALSE),
    ('xodó', 'xodo', 'xodo', 'pt-BR', FALSE, FALSE),
    ('caçula', 'cacula', 'cacula', 'pt-BR', FALSE, FALSE),
    ('puxar ao pai', 'puxar ao pai', 'puxar ao pai', 'pt-BR', FALSE, FALSE),
    ('dar bronca', 'dar bronca', 'dar bronca', 'pt-BR', FALSE, FALSE),
    ('de castigo', 'de castigo', 'de castigo', 'pt-BR', FALSE, FALSE),
    ('mesada', 'mesada', 'mesada', 'pt-BR', FALSE, FALSE),
    ('fazer feira', 'fazer feira', 'fazer feira', 'pt-BR', FALSE, FALSE),
    ('apertar o cinto', 'apertar o cinto', 'apertar o cinto', 'pt-BR', FALSE, FALSE),
    ('quebrar um galho', 'quebrar um galho', 'quebrar um galho', 'pt-BR', FALSE, FALSE),
    ('meter o bedelho', 'meter o bedelho', 'meter o bedelho', 'pt-BR', FALSE, FALSE),
    ('casa caindo', 'casa caindo', 'casa caindo', 'pt-BR', FALSE, FALSE),
    ('botar ordem na casa', 'botar ordem na casa', 'botar ordem na casa', 'pt-BR', FALSE, FALSE),
    ('república', 'republica', 'republica', 'pt-BR', FALSE, FALSE),
    ('dividir apê', 'dividir ape', 'dividir ape', 'pt-BR', FALSE, FALSE),
    ('sair da casa dos pais', 'sair da casa dos pais', 'sair da casa dos pais', 'pt-BR', FALSE, FALSE),
    ('almoço de domingo', 'almoco de domingo', 'almoco de domingo', 'pt-BR', FALSE, FALSE),
    ('esquenta', 'esquenta', 'esquenta', 'pt-BR', FALSE, FALSE),
    ('puxa-saco', 'puxa saco', 'puxa saco', 'pt-BR', FALSE, FALSE),
    ('queridinho', 'queridinho', 'queridinho', 'pt-BR', FALSE, FALSE),
    ('levar na esportiva', 'levar na esportiva', 'levar na esportiva', 'pt-BR', FALSE, FALSE),
    ('fazer as pazes', 'fazer as pazes', 'fazer as pazes', 'pt-BR', FALSE, FALSE),
    ('abrir o jogo', 'abrir o jogo', 'abrir o jogo', 'pt-BR', FALSE, FALSE),
    ('dar o braço a torcer', 'dar o braco a torcer', 'dar o braco a torcer', 'pt-BR', FALSE, FALSE),
    ('pegar no pé', 'pegar no pe', 'pegar no pe', 'pt-BR', FALSE, FALSE),
    ('chegar junto', 'chegar junto', 'chegar junto', 'pt-BR', FALSE, FALSE),
    ('dar uma força', 'dar uma forca', 'dar uma forca', 'pt-BR', FALSE, FALSE),
    ('puxar assunto', 'puxar assunto', 'puxar assunto', 'pt-BR', FALSE, FALSE),
    ('pôr na mesa', 'por na mesa', 'por na mesa', 'pt-BR', FALSE, FALSE),
    ('ficar de cara', 'ficar de cara', 'ficar de cara', 'pt-BR', FALSE, FALSE),
    ('dar trela', 'dar trela', 'dar trela', 'pt-BR', FALSE, FALSE),
    ('casa da mãe joana', 'casa da mae joana', 'casa da mae joana', 'pt-BR', FALSE, FALSE),
    ('criado solto', 'criado solto', 'criado solto', 'pt-BR', FALSE, FALSE),
    ('de porteira fechada', 'de porteira fechada', 'de porteira fechada', 'pt-BR', FALSE, FALSE),
    ('vaquinha', 'vaquinha', 'vaquinha', 'pt-BR', FALSE, FALSE),
    ('ajeitar a casa', 'ajeitar a casa', 'ajeitar a casa', 'pt-BR', FALSE, FALSE),
    ('criançada', 'criancada', 'criancada', 'pt-BR', FALSE, FALSE),
    ('casa de vó', 'casa de vo', 'casa de vo', 'pt-BR', FALSE, FALSE),
    ('estar de mudança', 'estar de mudanca', 'estar de mudanca', 'pt-BR', FALSE, FALSE)
) AS t(termo, norm, colapsado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma
ON CONFLICT (termo_normalizado, idioma_id) DO NOTHING;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('sograo', 'pt-BR', 'O sogro ou a sogra, dito com humor.', 'O aumentativo aqui é brincadeira, não tamanho. Aparece muito em conversa de casal sobre a família do outro.', NULL),
    ('tio do pave', 'pt-BR', 'O parente que conta a mesma piada sem graça toda festa.', 'Vem da piada "é pavê ou pá comê?". Virou o nome de um tipo: o adulto que repete trocadilhos velhos e ri sozinho. É dito com carinho.', NULL),
    ('agregado', 'pt-BR', 'Quem não é da família mas vive junto e é tratado como se fosse.', 'Namorado de longa data, amigo que mora perto, afilhado. "Ele é agregado aqui em casa" é aceitação, não crítica.', NULL),
    ('xodo', 'pt-BR', 'A pessoa preferida de alguém, tratada com carinho especial.', '"O neto é o xodó da avó." Palavra antiga e ainda muito usada, sobretudo no Nordeste.', 'preferido'),
    ('cacula', 'pt-BR', 'O filho ou a filha mais nova da família.', 'Carrega a fama de ser o mais mimado, e a piada em cima disso é constante entre irmãos.', 'filho mais novo'),
    ('puxar ao pai', 'pt-BR', 'Parecer com o pai ou com a mãe, na aparência ou no jeito.', '"Puxou a mãe na teimosia" fala do temperamento, não do rosto. É o que se diz olhando criança pequena.', NULL),
    ('dar bronca', 'pt-BR', 'Repreender alguém por alguma coisa que fez de errado.', '"Levei bronca" é ter sido repreendido. Entre adultos, vira jeito leve de contar que foi cobrado no trabalho.', 'repreender'),
    ('de castigo', 'pt-BR', 'Proibido de fazer alguma coisa como punição.', 'Hoje o castigo mais comum é ficar sem o celular, e é assim que a palavra aparece nas conversas de adolescente.', NULL),
    ('mesada', 'pt-BR', 'Dinheiro que os pais dão ao filho todo mês.', 'Serve para a criança aprender a se organizar. Entre adultos, vira piada sobre quem ainda depende dos pais.', NULL),
    ('fazer feira', 'pt-BR', 'Fazer as compras grandes do mês.', 'Vem da feira livre, mas hoje se usa igual para supermercado. "A feira tá cara" é queixa sobre o preço da comida.', 'compras do mês'),
    ('apertar o cinto', 'pt-BR', 'Gastar menos porque o dinheiro está curto.', '"Vamos ter que apertar o cinto esse mês" avisa que a casa vai cortar despesas.', 'economizar'),
    ('quebrar um galho', 'pt-BR', 'Ajudar alguém, ou resolver de um jeito provisório.', '"Quebra um galho pra mim" é pedir um favor. "Isso quebra o galho" é dizer que serve por enquanto, sem ser o ideal.', NULL),
    ('meter o bedelho', 'pt-BR', 'Se meter em assunto que não é seu.', 'Queixa clássica sobre parente que opina na vida dos outros sem ter sido chamado.', NULL),
    ('casa caindo', 'pt-BR', 'Situação em que tudo dá errado ao mesmo tempo.', '"A casa caiu" também quer dizer que alguém foi descoberto fazendo alguma coisa escondida.', NULL),
    ('botar ordem na casa', 'pt-BR', 'Organizar uma situação que estava bagunçada.', 'Raramente é sobre arrumar cômodos: quase sempre é sobre disciplina, regras ou contas.', NULL),
    ('republica', 'pt-BR', 'Casa dividida por vários estudantes.', 'Comum em cidade universitária. Cada um paga uma parte do aluguel e todos dividem as tarefas, em teoria.', 'moradia estudantil'),
    ('dividir ape', 'pt-BR', 'Morar com outra pessoa e rachar as despesas.', '"Apê" é apartamento. É como muita gente jovem consegue sair da casa dos pais numa cidade cara.', NULL),
    ('sair da casa dos pais', 'pt-BR', 'Passar a morar sozinho ou com outras pessoas.', '"Saiu de casa" sozinho pode ter os dois sentidos: mudança planejada ou briga. O contexto separa.', NULL),
    ('almoco de domingo', 'pt-BR', 'A refeição em que a família se reúne toda semana.', 'Instituição brasileira. Nas conversas dos netos costuma aparecer como compromisso do qual não dá para escapar.', NULL),
    ('esquenta', 'pt-BR', 'Encontro pequeno na casa de alguém antes da festa de verdade.', '"Vai ter esquenta lá em casa" é o convite para o começo da noite, geralmente entre poucos amigos.', NULL),
    ('puxa saco', 'pt-BR', 'Quem elogia demais alguém para conseguir vantagem.', 'Entre irmãos, é a acusação de estar agradando os pais de propósito. No trabalho, de estar agradando o chefe.', 'bajulador'),
    ('queridinho', 'pt-BR', 'O favorito de alguém, dito com uma ponta de ciúme.', '"É o queridinho da mãe" raramente é elogio: é reclamação de quem se sente menos preferido.', NULL),
    ('levar na esportiva', 'pt-BR', 'Não levar a mal, encarar com bom humor.', '"Leva na esportiva" é o pedido para não se ofender com uma brincadeira.', NULL),
    ('fazer as pazes', 'pt-BR', 'Voltar a se falar depois de uma briga.', 'Vale para irmãos, casais e amigos. É a expressão que fecha uma discussão.', 'reconciliar-se'),
    ('abrir o jogo', 'pt-BR', 'Contar a verdade sobre alguma coisa que estava escondida.', '"Vou abrir o jogo com você" anuncia uma conversa franca, quase sempre difícil.', 'ser franco'),
    ('dar o braco a torcer', 'pt-BR', 'Admitir que estava errado.', 'Quase sempre aparece na negativa: "ele não dá o braço a torcer", ou seja, não reconhece o erro de jeito nenhum.', 'reconhecer o erro'),
    ('pegar no pe', 'pt-BR', 'Ficar cobrando ou implicando com alguém sem parar.', 'Reclamação clássica de filho para pai ou mãe. Não é agressão: é insistência que cansa.', 'importunar'),
    ('chegar junto', 'pt-BR', 'Aparecer para ajudar quando alguém precisa.', '"Ele chegou junto" é um elogio grande: quer dizer que a pessoa apareceu na hora difícil.', 'apoiar'),
    ('dar uma forca', 'pt-BR', 'Ajudar alguém em alguma coisa.', 'Pedido comum e informal. "Me dá uma força aí" é "me ajuda".', 'ajudar'),
    ('puxar assunto', 'pt-BR', 'Começar uma conversa com alguém.', 'Normalmente para quebrar o silêncio ou para se aproximar de alguém.', 'iniciar conversa'),
    ('por na mesa', 'pt-BR', 'Trazer um assunto para ser conversado abertamente.', '"Vamos pôr isso na mesa" é propor falar de um problema em vez de fingir que ele não existe.', 'trazer para discussão'),
    ('ficar de cara', 'pt-BR', 'Ficar surpreso, quase sempre negativamente.', '"Fiquei de cara com o que ele disse" mistura surpresa e decepção. Diferente de "de cara" sozinho, que quer dizer "logo de início".', NULL),
    ('dar trela', 'pt-BR', 'Dar atenção a alguém, geralmente atenção demais.', '"Não dá trela pra ele" é um conselho para não alimentar uma conversa ou uma provocação.', 'dar atenção'),
    ('casa da mae joana', 'pt-BR', 'Lugar sem regra nenhuma, onde cada um faz o que quer.', '"Isto aqui não é a casa da mãe Joana" é a frase que um adulto usa para dizer que existem regras ali.', NULL),
    ('criado solto', 'pt-BR', 'Pessoa que cresceu sem limites, e que se comporta assim.', 'É crítica ao comportamento de adulto, com a explicação atribuída à criação. Dito por parentes, costuma ser meio brincadeira e meio queixa.', NULL),
    ('de porteira fechada', 'pt-BR', 'Aceitar alguém junto com os filhos que essa pessoa já tem.', 'Expressão do interior, hoje usada em todo o país. Diz que o compromisso inclui a família inteira do outro.', NULL),
    ('vaquinha', 'pt-BR', 'Juntar dinheiro entre várias pessoas para um objetivo comum.', '"Vamos fazer uma vaquinha pro presente" é cada um dar uma parte. Virou também o nome das campanhas de arrecadação na internet.', 'coleta coletiva'),
    ('ajeitar a casa', 'pt-BR', 'Arrumar a casa, deixar tudo no lugar.', 'Vale também no sentido figurado: organizar a própria vida antes de encarar outra coisa.', NULL),
    ('criancada', 'pt-BR', 'O conjunto das crianças de uma casa ou de um lugar.', '"Chama a criançada pra comer" fala com todas de uma vez.', 'as crianças'),
    ('casa de vo', 'pt-BR', 'Lugar onde se come bem e ninguém tem pressa.', 'Virou expressão para qualquer lugar acolhedor: "esse restaurante é tipo casa de vó".', NULL),
    ('estar de mudanca', 'pt-BR', 'Estar trocando de casa.', '"Tô de mudança" quer dizer que a pessoa está no processo, que costuma levar dias.', NULL)
) AS d(norm, idioma, simples, detalhada, formal)
JOIN idioma i ON i.codigo = d.idioma
JOIN giria g ON g.termo_normalizado = d.norm AND g.idioma_id = i.id;

INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada,
                            variacao_colapsada)
SELECT g.id, v.variacao, v.norm, v.colapsado
FROM (VALUES
    ('sograo', 'pt-BR', 'sogrona', 'sogrona', 'sogrona'),
    ('sograo', 'pt-BR', 'sograo', 'sograo', 'sograo'),
    ('sograo', 'pt-BR', 'sogrinha', 'sogrinha', 'sogrinha'),
    ('tio do pave', 'pt-BR', 'tio do pave', 'tio do pave', 'tio do pave'),
    ('tio do pave', 'pt-BR', 'piada de tio', 'piada de tio', 'piada de tio'),
    ('agregado', 'pt-BR', 'agregada', 'agregada', 'agregada'),
    ('agregado', 'pt-BR', 'agregados', 'agregados', 'agregados'),
    ('xodo', 'pt-BR', 'xodo', 'xodo', 'xodo'),
    ('xodo', 'pt-BR', 'xodozinho', 'xodozinho', 'xodozinho'),
    ('cacula', 'pt-BR', 'cacula', 'cacula', 'cacula'),
    ('cacula', 'pt-BR', 'caçulinha', 'caculinha', 'caculinha'),
    ('puxar ao pai', 'pt-BR', 'puxou a mae', 'puxou a mae', 'puxou a mae'),
    ('puxar ao pai', 'pt-BR', 'puxou ao pai', 'puxou ao pai', 'puxou ao pai'),
    ('puxar ao pai', 'pt-BR', 'puxar a mãe', 'puxar a mae', 'puxar a mae'),
    ('dar bronca', 'pt-BR', 'levou bronca', 'levou bronca', 'levou bronca'),
    ('dar bronca', 'pt-BR', 'tomar bronca', 'tomar bronca', 'tomar bronca'),
    ('de castigo', 'pt-BR', 'ficar de castigo', 'ficar de castigo', 'ficar de castigo'),
    ('de castigo', 'pt-BR', 'botar de castigo', 'botar de castigo', 'botar de castigo'),
    ('mesada', 'pt-BR', 'mesadinha', 'mesadinha', 'mesadinha'),
    ('fazer feira', 'pt-BR', 'fazendo feira', 'fazendo feira', 'fazendo feira'),
    ('fazer feira', 'pt-BR', 'feira do mês', 'feira do mes', 'feira do mes'),
    ('apertar o cinto', 'pt-BR', 'apertando o cinto', 'apertando o cinto', 'apertando o cinto'),
    ('quebrar um galho', 'pt-BR', 'quebra um galho', 'quebra um galho', 'quebra um galho'),
    ('quebrar um galho', 'pt-BR', 'quebrou o galho', 'quebrou o galho', 'quebrou o galho'),
    ('meter o bedelho', 'pt-BR', 'metendo o bedelho', 'metendo o bedelho', 'metendo o bedelho'),
    ('casa caindo', 'pt-BR', 'a casa caiu', 'a casa caiu', 'a casa caiu'),
    ('botar ordem na casa', 'pt-BR', 'pôr ordem na casa', 'por ordem na casa', 'por ordem na casa'),
    ('republica', 'pt-BR', 'republica', 'republica', 'republica'),
    ('republica', 'pt-BR', 'rep', 'rep', 'rep'),
    ('dividir ape', 'pt-BR', 'dividir ape', 'dividir ape', 'dividir ape'),
    ('dividir ape', 'pt-BR', 'dividir apartamento', 'dividir apartamento', 'dividir apartamento'),
    ('dividir ape', 'pt-BR', 'rolê de ape', 'role de ape', 'role de ape'),
    ('sair da casa dos pais', 'pt-BR', 'saiu de casa', 'saiu de casa', 'saiu de casa'),
    ('almoco de domingo', 'pt-BR', 'almoco de domingo', 'almoco de domingo', 'almoco de domingo'),
    ('esquenta', 'pt-BR', 'esquentinha', 'esquentinha', 'esquentinha'),
    ('puxa saco', 'pt-BR', 'puxa saco', 'puxa saco', 'puxa saco'),
    ('puxa saco', 'pt-BR', 'puxasaco', 'puxasaco', 'puxasaco'),
    ('puxa saco', 'pt-BR', 'puxar saco', 'puxar saco', 'puxar saco'),
    ('queridinho', 'pt-BR', 'queridinha', 'queridinha', 'queridinha'),
    ('queridinho', 'pt-BR', 'queridinhos', 'queridinhos', 'queridinhos'),
    ('levar na esportiva', 'pt-BR', 'leva na esportiva', 'leva na esportiva', 'leva na esportiva'),
    ('fazer as pazes', 'pt-BR', 'fez as pazes', 'fez as pazes', 'fez as pazes'),
    ('abrir o jogo', 'pt-BR', 'abriu o jogo', 'abriu o jogo', 'abriu o jogo'),
    ('dar o braco a torcer', 'pt-BR', 'deu o braco a torcer', 'deu o braco a torcer', 'deu o braco a torcer'),
    ('pegar no pe', 'pt-BR', 'pegar no pe', 'pegar no pe', 'pegar no pe'),
    ('pegar no pe', 'pt-BR', 'pegando no pe', 'pegando no pe', 'pegando no pe'),
    ('chegar junto', 'pt-BR', 'chegou junto', 'chegou junto', 'chegou junto'),
    ('chegar junto', 'pt-BR', 'chega junto', 'chega junto', 'chega junto'),
    ('dar uma forca', 'pt-BR', 'deu uma forca', 'deu uma forca', 'deu uma forca'),
    ('dar uma forca', 'pt-BR', 'dar forca', 'dar forca', 'dar forca'),
    ('puxar assunto', 'pt-BR', 'puxou assunto', 'puxou assunto', 'puxou assunto'),
    ('por na mesa', 'pt-BR', 'por na mesa', 'por na mesa', 'por na mesa'),
    ('por na mesa', 'pt-BR', 'botar na mesa', 'botar na mesa', 'botar na mesa'),
    ('ficar de cara', 'pt-BR', 'fiquei de cara', 'fiquei de cara', 'fiquei de cara'),
    ('dar trela', 'pt-BR', 'deu trela', 'deu trela', 'deu trela'),
    ('dar trela', 'pt-BR', 'dando trela', 'dando trela', 'dando trela'),
    ('casa da mae joana', 'pt-BR', 'casa da mae joana', 'casa da mae joana', 'casa da mae joana'),
    ('criado solto', 'pt-BR', 'criada solta', 'criada solta', 'criada solta'),
    ('de porteira fechada', 'pt-BR', 'porteira fechada', 'porteira fechada', 'porteira fechada'),
    ('vaquinha', 'pt-BR', 'fazer vaquinha', 'fazer vaquinha', 'fazer vaquinha'),
    ('vaquinha', 'pt-BR', 'vakinha', 'vakinha', 'vakinha'),
    ('ajeitar a casa', 'pt-BR', 'ajeitando a casa', 'ajeitando a casa', 'ajeitando a casa'),
    ('criancada', 'pt-BR', 'criancada', 'criancada', 'criancada'),
    ('casa de vo', 'pt-BR', 'casa de vo', 'casa de vo', 'casa de vo'),
    ('casa de vo', 'pt-BR', 'comida de vo', 'comida de vo', 'comida de vo'),
    ('estar de mudanca', 'pt-BR', 'de mudanca', 'de mudanca', 'de mudanca'),
    ('estar de mudanca', 'pt-BR', 'em mudanca', 'em mudanca', 'em mudanca')
) AS v(termo_norm, idioma, variacao, norm, colapsado)
JOIN idioma i ON i.codigo = v.idioma
JOIN giria g ON g.termo_normalizado = v.termo_norm AND g.idioma_id = i.id
ON CONFLICT (variacao_normalizada, giria_id) DO NOTHING;

INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('sograo', 'pt-BR', 'familia'),
    ('sograo', 'pt-BR', 'humor'),
    ('tio do pave', 'pt-BR', 'familia'),
    ('tio do pave', 'pt-BR', 'humor'),
    ('agregado', 'pt-BR', 'familia'),
    ('xodo', 'pt-BR', 'familia'),
    ('xodo', 'pt-BR', 'relacionamento'),
    ('cacula', 'pt-BR', 'familia'),
    ('puxar ao pai', 'pt-BR', 'familia'),
    ('puxar ao pai', 'pt-BR', 'descricao'),
    ('dar bronca', 'pt-BR', 'familia'),
    ('dar bronca', 'pt-BR', 'critica'),
    ('de castigo', 'pt-BR', 'familia'),
    ('mesada', 'pt-BR', 'familia'),
    ('mesada', 'pt-BR', 'trabalho'),
    ('fazer feira', 'pt-BR', 'familia'),
    ('fazer feira', 'pt-BR', 'comida'),
    ('apertar o cinto', 'pt-BR', 'familia'),
    ('apertar o cinto', 'pt-BR', 'trabalho'),
    ('quebrar um galho', 'pt-BR', 'familia'),
    ('quebrar um galho', 'pt-BR', 'acao'),
    ('meter o bedelho', 'pt-BR', 'familia'),
    ('meter o bedelho', 'pt-BR', 'critica'),
    ('casa caindo', 'pt-BR', 'familia'),
    ('casa caindo', 'pt-BR', 'humor'),
    ('botar ordem na casa', 'pt-BR', 'familia'),
    ('botar ordem na casa', 'pt-BR', 'acao'),
    ('republica', 'pt-BR', 'familia'),
    ('republica', 'pt-BR', 'escolar'),
    ('dividir ape', 'pt-BR', 'familia'),
    ('dividir ape', 'pt-BR', 'trabalho'),
    ('sair da casa dos pais', 'pt-BR', 'familia'),
    ('almoco de domingo', 'pt-BR', 'familia'),
    ('almoco de domingo', 'pt-BR', 'comida'),
    ('esquenta', 'pt-BR', 'familia'),
    ('esquenta', 'pt-BR', 'musica'),
    ('puxa saco', 'pt-BR', 'familia'),
    ('puxa saco', 'pt-BR', 'critica'),
    ('queridinho', 'pt-BR', 'familia'),
    ('queridinho', 'pt-BR', 'critica'),
    ('levar na esportiva', 'pt-BR', 'familia'),
    ('levar na esportiva', 'pt-BR', 'emocao'),
    ('fazer as pazes', 'pt-BR', 'familia'),
    ('fazer as pazes', 'pt-BR', 'relacionamento'),
    ('abrir o jogo', 'pt-BR', 'familia'),
    ('abrir o jogo', 'pt-BR', 'acao'),
    ('dar o braco a torcer', 'pt-BR', 'familia'),
    ('dar o braco a torcer', 'pt-BR', 'acao'),
    ('pegar no pe', 'pt-BR', 'familia'),
    ('pegar no pe', 'pt-BR', 'critica'),
    ('chegar junto', 'pt-BR', 'familia'),
    ('chegar junto', 'pt-BR', 'acao'),
    ('dar uma forca', 'pt-BR', 'familia'),
    ('dar uma forca', 'pt-BR', 'acao'),
    ('puxar assunto', 'pt-BR', 'familia'),
    ('puxar assunto', 'pt-BR', 'acao'),
    ('por na mesa', 'pt-BR', 'familia'),
    ('por na mesa', 'pt-BR', 'acao'),
    ('ficar de cara', 'pt-BR', 'familia'),
    ('ficar de cara', 'pt-BR', 'emocao'),
    ('dar trela', 'pt-BR', 'familia'),
    ('dar trela', 'pt-BR', 'acao'),
    ('casa da mae joana', 'pt-BR', 'familia'),
    ('casa da mae joana', 'pt-BR', 'critica'),
    ('criado solto', 'pt-BR', 'familia'),
    ('criado solto', 'pt-BR', 'critica'),
    ('de porteira fechada', 'pt-BR', 'familia'),
    ('de porteira fechada', 'pt-BR', 'relacionamento'),
    ('vaquinha', 'pt-BR', 'familia'),
    ('vaquinha', 'pt-BR', 'trabalho'),
    ('ajeitar a casa', 'pt-BR', 'familia'),
    ('ajeitar a casa', 'pt-BR', 'acao'),
    ('criancada', 'pt-BR', 'familia'),
    ('casa de vo', 'pt-BR', 'familia'),
    ('casa de vo', 'pt-BR', 'comida'),
    ('estar de mudanca', 'pt-BR', 'familia')
) AS gc(termo_norm, idioma, categoria)
JOIN idioma i ON i.codigo = gc.idioma
JOIN giria g ON g.termo_normalizado = gc.termo_norm AND g.idioma_id = i.id
JOIN categoria c ON c.slug = gc.categoria
ON CONFLICT DO NOTHING;

