-- ---------------------------------------------------------------------------
-- Seed inicial de verbetes curados.
--
-- As explicacoes simples sao escritas para a persona Marlene, 68 anos, sem
-- familiaridade com internet: frase curta, sem jargao, sem pressupor que a
-- pessoa saiba o que e Twitch, Discord ou emote. A explicacao detalhada e
-- que carrega a origem e a nuance, para quem quiser ir alem.
--
-- Os comentarios deste arquivo vao sem acento (consistencia com o restante
-- do codigo), mas o conteudo exibido ao usuario e acentuado corretamente:
-- e texto que a Marlene le na tela, nao identificador de codigo.
--
-- Este arquivo e o ponto de partida da curadoria, nao o dicionario final.
-- A cobertura cresce pelo ciclo termo_desconhecido -> curadoria -> verbete.
-- ---------------------------------------------------------------------------

INSERT INTO giria (termo, termo_normalizado, idioma_id, nsfw, risco_menor)
SELECT t.termo, t.normalizado, i.id, t.nsfw, t.risco
FROM (VALUES
    -- Transmissoes ao vivo e jogos (ingles)
    ('pog',       'pog',       'en',    false, false),
    ('poggers',   'poggers',   'en',    false, false),
    ('kekw',      'kekw',      'en',    false, false),
    ('copium',    'copium',    'en',    false, false),
    ('malding',   'malding',   'en',    false, false),
    ('clutch',    'clutch',    'en',    false, false),
    ('gg',        'gg',        'en',    false, false),
    ('ez',        'ez',        'en',    false, false),
    ('afk',       'afk',       'en',    false, false),
    ('nerf',      'nerf',      'en',    false, false),
    ('buff',      'buff',      'en',    false, false),
    ('tilt',      'tilt',      'en',    false, false),
    ('smurf',     'smurf',     'en',    false, false),
    ('noob',      'noob',      'en',    false, false),
    ('lag',       'lag',       'en',    false, false),
    ('camper',    'camper',    'en',    false, false),
    ('raid',      'raid',      'en',    false, false),
    ('lurker',    'lurker',    'en',    false, false),
    -- Redes sociais (ingles)
    ('rizz',      'rizz',      'en',    false, false),
    ('cringe',    'cringe',    'en',    false, false),
    ('based',     'based',     'en',    false, false),
    ('sus',       'sus',       'en',    false, false),
    ('npc',       'npc',       'en',    false, false),
    ('mid',       'mid',       'en',    false, false),
    ('cap',       'cap',       'en',    false, false),
    ('ratio',     'ratio',     'en',    false, false),
    ('ghosting',  'ghosting',  'en',    false, false),
    ('simp',      'simp',      'en',    false, false),
    ('drip',      'drip',      'en',    false, false),
    ('flex',      'flex',      'en',    false, false),
    ('salty',     'salty',     'en',    false, false),
    ('stan',      'stan',      'en',    false, false),
    ('slay',      'slay',      'en',    false, false),
    ('skibidi',   'skibidi',   'en',    false, false),
    ('67',        '67',        'en',    false, false),
    -- Conversa e redes sociais (portugues)
    ('mds',       'mds',       'pt-BR', false, false),
    ('sqn',       'sqn',       'pt-BR', false, false),
    ('pdc',       'pdc',       'pt-BR', false, false),
    ('vlw',       'vlw',       'pt-BR', false, false),
    ('flw',       'flw',       'pt-BR', false, false),
    ('kkk',       'kkk',       'pt-BR', false, false),
    ('mano',      'mano',      'pt-BR', false, false),
    ('treta',     'treta',     'pt-BR', false, false),
    ('zoeira',    'zoeira',    'pt-BR', false, false),
    ('crush',     'crush',     'pt-BR', false, false),
    ('ranço',     'ranco',     'pt-BR', false, false),
    ('recalque',  'recalque',  'pt-BR', false, false),
    ('mitou',     'mitou',     'pt-BR', false, false),
    ('lacrar',    'lacrar',    'pt-BR', false, false),
    ('shippar',   'shippar',   'pt-BR', false, false),
    ('stalkear',  'stalkear',  'pt-BR', false, false),
    ('printar',   'printar',   'pt-BR', false, false),
    ('zap',       'zap',       'pt-BR', false, false),
    ('sextou',    'sextou',    'pt-BR', false, false),
    ('dar ruim',  'dar ruim',  'pt-BR', false, false),
    ('de boa',    'de boa',    'pt-BR', false, false),
    ('migué',     'migue',     'pt-BR', false, false),
    ('pistola',   'pistola',   'pt-BR', false, false),
    ('surtar',    'surtar',    'pt-BR', false, false),
    ('vish',      'vish',      'pt-BR', false, false),
    ('trairagem', 'trairagem', 'pt-BR', false, false),
    ('chorar',    'chorar',    'pt-BR', false, false),
    ('bomba',     'bomba',     'pt-BR', false, false)
) AS t(termo, normalizado, idioma, nsfw, risco)
JOIN idioma i ON i.codigo = t.idioma;

INSERT INTO definicao (giria_id, explicacao_simples, explicacao_detalhada,
                       equivalente_formal, fonte_id)
SELECT g.id, d.simples, d.detalhada, d.formal,
       (SELECT id FROM fonte WHERE tipo = 'CURADORIA')
FROM (VALUES
    ('pog', 'en', 'Jeito de dizer "que incrível!" quando algo muito bom acontece.',
     'Vem de "play of the game", a melhor jogada da partida. Ficou popular em transmissões de jogos ao vivo, onde o público escreve no chat quando alguém faz algo excepcional.',
     'que incrível'),
    ('poggers', 'en', 'O mesmo que "pog": empolgação com algo muito bom.',
     'Variação mais enfática de "pog", ligada a uma figurinha animada usada nos chats de transmissão ao vivo.',
     'que incrível'),
    ('kekw', 'en', 'Serve para dizer que algo foi muito engraçado, como um "kkkk".',
     'Nasceu em chats de transmissão ao vivo. O "kek" vem de comunidades de jogos e equivale ao nosso "kkk"; o "W" foi acrescentado pelo nome de uma figurinha de risada.',
     'que engraçado'),
    ('copium', 'en', 'Ironia com quem se ilude para não aceitar uma derrota.',
     'Junção de "cope" (aguentar, lidar) com o sufixo de remédio "-ium". A piada é tratar a negação como se fosse um calmante que a pessoa toma.',
     'autoengano'),
    ('malding', 'en', 'Alguém muito irritado com algo pequeno, geralmente num jogo.',
     'Junção de "mad" (bravo) com "balding" (ficando careca). A piada é que a pessoa se irrita tanto que perderia cabelo.',
     'irritado'),
    ('clutch', 'en', 'Ganhar quando já parecia perdido, na última hora.',
     'Do inglês "clutch", momento decisivo. No Brasil virou também verbo: "clutchou" quer dizer "salvou o jogo sozinho no fim".',
     'virada decisiva'),
    ('gg', 'en', 'Abreviação de "bom jogo", dita ao terminar uma partida.',
     'De "good game". É cumprimento de fim de partida; dependendo do tom, pode ser sincero ou irônico quando o resultado foi muito desigual.',
     'bom jogo'),
    ('ez', 'en', 'Modo abreviado e provocativo de dizer "fácil".',
     'De "easy". Escrito depois de vencer, costuma ser provocação com o adversário, e não apenas um comentário sobre a dificuldade.',
     'fácil'),
    ('afk', 'en', 'A pessoa se afastou e não está no computador agora.',
     'De "away from keyboard", longe do teclado. Usado para avisar ausência temporária em jogos e conversas.',
     'ausente no momento'),
    ('nerf', 'en', 'Quando algo em um jogo foi enfraquecido de propósito.',
     'Vem da marca de brinquedos Nerf, cujos dardos são de espuma. Enfraquecer algo é, na piada, "transformar em brinquedo".',
     'enfraquecimento'),
    ('buff', 'en', 'Quando algo em um jogo foi fortalecido de propósito.',
     'O oposto de "nerf". Também usado para um efeito temporário que deixa o personagem mais forte.',
     'fortalecimento'),
    ('tilt', 'en', 'Perder a calma e começar a jogar mal por causa da raiva.',
     'Vem do fliperama, em que sacudir a máquina acionava o aviso "tilt" e travava a partida. No pôquer e nos jogos, virou o estado emocional que faz a pessoa errar.',
     'descontrole emocional'),
    ('smurf', 'en', 'Jogador experiente que usa conta nova para enfrentar iniciantes.',
     'A prática é mal vista porque desequilibra as partidas de quem está começando.',
     'conta secundária'),
    ('noob', 'en', 'Pessoa iniciante, que ainda não sabe jogar.',
     'De "newbie", novato. Pode ser descrição neutra ou ofensa, dependendo do tom.',
     'iniciante'),
    ('lag', 'en', 'Travamento causado por internet lenta.',
     'É o atraso entre a ação do jogador e a resposta do jogo. "Lagou" quer dizer "travou".',
     'travamento'),
    ('camper', 'en', 'Jogador que fica parado esperando para surpreender os outros.',
     'De "camp", acampar. É permitido pelas regras, mas considerado chato por boa parte dos jogadores.',
     'jogador emboscado'),
    ('raid', 'en', 'Quando quem transmite envia sua plateia para outro canal.',
     'Prática comum ao encerrar uma transmissão ao vivo: é uma forma de apresentar um colega ao próprio público.',
     'envio de audiência'),
    ('lurker', 'en', 'Quem acompanha mas nunca escreve nada.',
     'De "lurk", espreitar. Não tem sentido negativo: é simplesmente quem assiste em silêncio.',
     'espectador silencioso'),
    ('rizz', 'en', 'Facilidade para conquistar alguém, ter charme na conversa.',
     'Encurtamento de "charisma", carisma. "Ter rizz" é saber puxar conversa e agradar; "no rizz" é o contrário.',
     'charme'),
    ('cringe', 'en', 'Vergonha alheia; algo tão constrangedor que dá desconforto.',
     'Em inglês, "cringe" é o gesto de encolher-se. Virou substantivo e adjetivo também em português: "que cringe", "isso é muito cringe".',
     'vergonha alheia'),
    ('based', 'en', 'Elogio a quem fala o que pensa sem se importar com a opinião alheia.',
     'Começou como gíria de rua nos Estados Unidos e foi ressignificado na internet. O oposto costuma ser "cringe".',
     'autêntico'),
    ('sus', 'en', 'Suspeito, algo que parece estranho.',
     'Encurtamento de "suspicious". Espalhou-se por um jogo em que os participantes acusam uns aos outros de traição.',
     'suspeito'),
    ('npc', 'en', 'Pessoa que age no automático, sem opinião própria.',
     'Nos jogos, NPC é um personagem controlado pelo computador, com falas repetidas. Aplicado a uma pessoa, é crítica.',
     'sem opinião própria'),
    ('mid', 'en', 'Mediano, nada demais.',
     'Do inglês "middle", meio. Usado para dizer que algo muito elogiado é, na verdade, comum.',
     'mediano'),
    ('cap', 'en', 'Mentira. "No cap" quer dizer "sem mentira, é sério".',
     'Vem da gíria norte-americana em que "capping" é exagerar ou mentir.',
     'mentira'),
    ('ratio', 'en', 'Aviso de que uma publicação recebeu mais críticas do que apoio.',
     'Refere-se à proporção entre respostas e curtidas: quando as respostas superam muito as curtidas, entende-se que a opinião foi mal recebida.',
     'rejeição pública'),
    ('ghosting', 'en', 'Sumir de alguém sem explicação, parando de responder.',
     'De "ghost", fantasma. Descreve o fim de um contato sem qualquer aviso.',
     'sumiço sem explicação'),
    ('simp', 'en', 'Alguém que se rebaixa demais tentando agradar uma pessoa.',
     'É usado quase sempre de forma pejorativa, e já foi criticado justamente por ridicularizar demonstrações de afeto.',
     'bajulador'),
    ('drip', 'en', 'Roupa de bom gosto, visual bem montado.',
     'Elogio à maneira de se vestir. "Ter drip" é ter estilo.',
     'estilo'),
    ('flex', 'en', 'Exibir algo para impressionar os outros.',
     'De "flex", flexionar o músculo. "Flexar" é ostentar.',
     'ostentar'),
    ('salty', 'en', 'Amargurado por ter perdido.',
     'Literalmente "salgado", pela associação com lágrimas. Descreve quem reclama depois de uma derrota.',
     'inconformado'),
    ('stan', 'en', 'Fã muito dedicado a alguém.',
     'Vem de uma música do ano 2000 que narra um fã obsessivo. Hoje é usado também como verbo: "eu stano".',
     'fã dedicado'),
    ('slay', 'en', 'Elogio forte: mandou muito bem, arrasou.',
     'Popularizado em comunidades de moda e música. Não tem relação com o sentido literal do verbo em inglês.',
     'arrasou'),
    ('skibidi', 'en', 'Palavra sem significado fixo, usada por humor entre adolescentes.',
     'Vem de uma série de vídeos curtos de humor absurdo. O sentido muda conforme a frase e, muitas vezes, é apenas piada sem conteúdo algum.',
     'sem sentido definido'),
    ('67', 'en', 'Número usado como piada entre adolescentes, sem significado próprio.',
     'Virou bordão a partir de vídeos curtos de humor. Fora desse contexto é apenas o número sessenta e sete: em uma conta de matemática ou em um endereço, não há gíria nenhuma.',
     'bordão de humor'),
    ('mds', 'pt-BR', 'Abreviação de "meu Deus", usada em espanto.',
     'Escrita rápida em conversas. Aparece com letras repetidas para reforçar o susto, como "mdsss".',
     'meu Deus'),
    ('sqn', 'pt-BR', 'Marca de ironia: significa "só que não".',
     'Escrito no fim da frase, avisa que o que veio antes era o contrário do que a pessoa pensa de verdade.',
     'só que não'),
    ('pdc', 'pt-BR', 'Abreviação de "pode crer", que quer dizer "concordo".',
     'Resposta curta de concordância em conversas escritas.',
     'pode crer'),
    ('vlw', 'pt-BR', 'Abreviação de "valeu", ou seja, obrigado.',
     'Costuma vir junto de "flw" no encerramento da conversa.',
     'obrigado'),
    ('flw', 'pt-BR', 'Abreviação de "falou", usada como tchau.',
     'Encerra a conversa. "Vlw, flw" quer dizer "obrigado, tchau".',
     'tchau'),
    ('kkk', 'pt-BR', 'Representa risada, como "hahaha".',
     'Quanto mais letras, maior a risada. É a forma mais comum de rir por escrito no Brasil.',
     'risada'),
    ('mano', 'pt-BR', 'Forma informal de chamar alguém, como "cara" ou "amigo".',
     'Serve também de interjeição no começo da frase, sem se dirigir a ninguém: "mano, que susto".',
     'cara'),
    ('treta', 'pt-BR', 'Briga, confusão ou desentendimento.',
     'Pode ser discussão na internet ou conflito real. "Dar treta" é virar briga.',
     'confusão'),
    ('zoeira', 'pt-BR', 'Brincadeira, gozação.',
     'Nem sempre é agressiva, mas o limite entre zoeira e ofensa é justamente o que costuma gerar treta.',
     'brincadeira'),
    ('crush', 'pt-BR', 'Pessoa por quem se está interessado romanticamente.',
     'Palavra inglesa incorporada ao português. Costuma indicar interesse ainda não declarado.',
     'paquera'),
    ('ranço', 'pt-BR', 'Antipatia persistente por alguém ou algo.',
     '"Ter ranço de alguém" é não suportar a pessoa, geralmente sem um motivo grave por trás.',
     'antipatia'),
    ('recalque', 'pt-BR', 'Inveja disfarçada de crítica.',
     'Acusar alguém de recalque é dizer que a crítica vem de inveja, e não de razão.',
     'inveja'),
    ('mitou', 'pt-BR', 'Fez algo excepcional, foi muito bem.',
     'De "mito". Elogio forte e muito comum em comentários.',
     'foi excelente'),
    ('lacrar', 'pt-BR', 'Dar uma resposta certeira que encerra a discussão.',
     'Usado como elogio por uns e como crítica por outros, quando se entende que a pessoa fala apenas para impressionar.',
     'arrasar'),
    ('shippar', 'pt-BR', 'Torcer para que duas pessoas fiquem juntas.',
     'Do inglês "relationship", relacionamento. Aplica-se a personagens de ficção e também a pessoas reais.',
     'torcer pelo casal'),
    ('stalkear', 'pt-BR', 'Vasculhar o perfil de alguém nas redes sociais.',
     'Do inglês "stalk", espreitar. No uso comum é apenas bisbilhotar publicações antigas, mas o termo original descreve perseguição.',
     'bisbilhotar'),
    ('printar', 'pt-BR', 'Salvar uma imagem do que está na tela.',
     'De "print screen". O resultado é o "print", usado como prova de uma conversa.',
     'capturar a tela'),
    ('zap', 'pt-BR', 'Apelido do aplicativo de mensagens WhatsApp.',
     'Também escrito "zap zap". "Manda no zap" quer dizer "envie pelo WhatsApp".',
     'WhatsApp'),
    ('sextou', 'pt-BR', 'Comemoração pela chegada da sexta-feira.',
     'Verbo inventado a partir do dia da semana. Marca o início do fim de semana.',
     'chegou a sexta-feira'),
    ('dar ruim', 'pt-BR', 'Algo dar errado, acabar mal.',
     'Usado tanto para problemas pequenos quanto para consequências sérias.',
     'dar errado'),
    ('de boa', 'pt-BR', 'Tranquilo, sem problema.',
     'Serve de resposta ("tá de boa") e de descrição de estado ("ele tá de boa").',
     'tranquilo'),
    ('migué', 'pt-BR', 'Desculpa inventada para escapar de algo.',
     '"Dar um migué" é enrolar, apresentar uma justificativa que ninguém acredita.',
     'desculpa esfarrapada'),
    ('pistola', 'pt-BR', 'Muito irritado.',
     '"Ficar pistola" é ficar bravo. Não tem relação com arma no uso corrente.',
     'irritado'),
    ('surtar', 'pt-BR', 'Reagir de forma exagerada, perder o controle.',
     'Usado com leveza para empolgação ("surtei com essa notícia") e também para crise emocional real. O contexto decide qual dos dois é.',
     'perder o controle'),
    ('vish', 'pt-BR', 'Interjeição de espanto ou de "agora complicou".',
     'Encurtamento de "vixe". Sinaliza que algo deu errado.',
     'que problema'),
    ('trairagem', 'pt-BR', 'Traição ou deslealdade com amigos.',
     'Formado de "trair" com o sufixo "-agem". Vale para relacionamento e também para amizade.',
     'deslealdade'),
    ('chorar', 'pt-BR', 'Reclamar de uma derrota em vez de aceitá-la.',
     'No contexto de jogos, "para de chorar" quer dizer "aceite que perdeu". Fora dele, mantém o sentido comum.',
     'reclamar'),
    ('bomba', 'pt-BR', 'Reprovação escolar; também algo que deu muito errado.',
     '"Tomei bomba" é "fui reprovado". Em outros contextos, é um problema herdado de alguém.',
     'reprovação')
) AS d(termo, idioma, simples, detalhada, formal)
JOIN giria g  ON g.termo = d.termo
JOIN idioma i ON i.id = g.idioma_id AND i.codigo = d.idioma;

-- Variacoes de escrita: apontam para o mesmo verbete em vez de duplica-lo.
INSERT INTO giria_variacao (giria_id, variacao, variacao_normalizada)
SELECT g.id, v.variacao, v.normalizada
FROM (VALUES
    ('pog',      'en',    'pogchamp',  'pogchamp'),
    ('kekw',     'en',    'kek',       'kek'),
    ('cringe',   'en',    'cringy',    'cringy'),
    ('cap',      'en',    'no cap',    'no cap'),
    ('mds',      'pt-BR', 'mdsss',     'mdsss'),
    ('kkk',      'pt-BR', 'kkkk',      'kkkk'),
    ('kkk',      'pt-BR', 'rsrs',      'rsrs'),
    ('zap',      'pt-BR', 'zap zap',   'zap zap'),
    ('crush',    'pt-BR', 'krush',     'krush')
) AS v(termo, idioma, variacao, normalizada)
JOIN giria g  ON g.termo_normalizado = v.termo
JOIN idioma i ON i.id = g.idioma_id AND i.codigo = v.idioma;

-- Categorias dos verbetes.
INSERT INTO giria_categoria (giria_id, categoria_id)
SELECT g.id, c.id
FROM (VALUES
    ('pog','streaming'),('poggers','streaming'),('kekw','streaming'),
    ('copium','streaming'),('malding','streaming'),('raid','streaming'),
    ('lurker','streaming'),
    ('clutch','gaming'),('gg','gaming'),('ez','gaming'),('afk','gaming'),
    ('nerf','gaming'),('buff','gaming'),('tilt','gaming'),('smurf','gaming'),
    ('noob','gaming'),('lag','gaming'),('camper','gaming'),('chorar','gaming'),
    ('rizz','redes'),('cringe','redes'),('based','redes'),('sus','redes'),
    ('npc','redes'),('mid','redes'),('cap','redes'),('ratio','redes'),
    ('ghosting','redes'),('simp','redes'),('drip','redes'),('flex','redes'),
    ('salty','redes'),('stan','redes'),('slay','redes'),('skibidi','redes'),
    ('67','redes'),('crush','redes'),('shippar','redes'),('stalkear','redes'),
    ('printar','redes'),('zap','redes'),('lacrar','redes'),('recalque','redes'),
    ('mds','abreviacao'),('sqn','abreviacao'),('pdc','abreviacao'),
    ('vlw','abreviacao'),('flw','abreviacao'),('kkk','abreviacao'),
    ('mano','rua'),('treta','rua'),('zoeira','rua'),('ranco','rua'),
    ('mitou','rua'),('sextou','rua'),('dar ruim','rua'),('de boa','rua'),
    ('migue','rua'),('pistola','rua'),('surtar','rua'),('vish','rua'),
    ('trairagem','rua'),
    ('bomba','escolar')
) AS gc(termo, categoria)
JOIN giria g     ON g.termo_normalizado = gc.termo
JOIN categoria c ON c.slug = gc.categoria;
